access/src/main/external/static/recordTransformations/modsToFullRecord.xsl
access/src/main/external/static/recordTransformations/scriptNames.xsl

Updates to the full record page xslt, which expand support for additional tags, better support for languages and scripts, reformats various fields.  It also removes all instances of frontin'.

Full record XSLT updates

---

fcrepo-cdr-fesl/pom.xml
fcrepo-cdr-fesl/src/main/java/edu/unc/lib/dl/security/CdrRIAttributeFinder.java
fcrepo-cdr-fesl/src/main/java/edu/unc/lib/dl/security/objecthandlers/AddRelationship.java
fcrepo-cdr-fesl/src/main/java/edu/unc/lib/dl/security/objecthandlers/PurgeRelationship.java
fcrepo-cdr-fesl/src/main/java/edu/unc/lib/dl/security/wshandlers/AddRelationshipHandler.java
fcrepo-cdr-fesl/src/main/java/edu/unc/lib/dl/security/wshandlers/PurgeRelationshipHandler.java
fcrepo-irods-storage/pom.xml
fcrepo-irods-storage/src/main/java/fedorax/server/module/storage/IrodsExternalContentManager.java
pom.xml

* Bump Fedora version
* Update import statements for new XACML package
* Use non-XML API for finding attributes
* Exclude log4j-over-slf4j to prevent infinite logger delegation loop problem

Updates for Fedora 3.8.x

---

access/src/main/webapp/WEB-INF/jsp/frontPage.jsp

Part of the front page layout was using the "thumbnail" class, but not for any actual styles. This conflicted with the new thumbnail/placeholder CSS.

Remove unused and conflicting "thumbnail" class from front page collection list

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/ManagementClient.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/OptimisticLockException.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/util/TripleStoreQueryService.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/util/TripleStoreQueryServiceMulgaraImpl.java
metadata/src/main/java/edu/unc/lib/dl/util/ContentModelHelper.java
metadata/src/main/java/edu/unc/lib/dl/util/DateTimeUtil.java
metadata/src/main/java/edu/unc/lib/dl/xml/JDOMQueryUtil.java
persistence/src/main/java/edu/unc/lib/dl/services/DigitalObjectManager.java
persistence/src/main/java/edu/unc/lib/dl/services/DigitalObjectManagerImpl.java
persistence/src/main/java/edu/unc/lib/dl/util/ContainerContentsHelper.java
persistence/src/test/java/edu/unc/lib/dl/services/DigitalObjectManagerImplTest.java
persistence/src/test/java/edu/unc/lib/dl/services/DigitalObjectManagerMoveTest.java
persistence/src/test/resources/fedora/containerRELSEXT1.xml
persistence/src/test/resources/fedora/containerRELSEXT2.xml
persistence/src/test/resources/fedora/containerRELSEXT3.xml
persistence/src/test/resources/fedora/mdContents1.xml
persistence/src/test/resources/service-context.xml
services/src/main/java/edu/unc/lib/dl/cdr/services/processing/MoveRollbackJob.java
services/src/main/webapp/WEB-INF/service-context.xml
services/src/main/webapp/WEB-INF/sword-servlet.xml

Refactored the move operation to happen as three RELS-EXT datastream updates instead of addRelationship/removeRelationship per item.  Implemented an automatic rollback mechanism that will attempt to undo the move, either immediately or after a server restart

Move operation refactor

---

access/src/main/external/static/css/admin/admin_forms.css
access/src/main/external/static/css/cdr_admin.css
access/src/main/external/static/js/admin/src/ResubmitPackageForm.js
access/src/main/external/static/js/admin/src/statusMonitor/DepositMonitor.js
access/src/main/external/static/js/admin/src/statusMonitor/StatusMonitorManager.js
access/src/main/external/static/js/admin/statusMonitor.js
access/src/main/external/static/js/cdr-admin.js
access/src/main/external/static/templates/admin/resubmitPackageForm.html
access/src/main/external/static/templates/admin/statusMonitor/depositMonitorJobDetails.html
admin/src/main/java/edu/unc/lib/dl/admin/controller/ResubmitIngestController.java
deposit/src/main/java/edu/unc/lib/deposit/PrepareResubmitJob.java
deposit/src/main/java/edu/unc/lib/deposit/fcrepo3/IngestDeposit.java
deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/main/resources/service-context.xml
fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/FedoraFaultMessageResolver.java
metadata/src/main/java/edu/unc/lib/dl/util/DepositConstants.java
metadata/src/main/java/edu/unc/lib/dl/util/RedisWorkerConstants.java

- Add ResubmitIngestController which checks resubmitted packages and saves them to the batch ingest directory
- Add PrepareResubmitJob which backs up the previous ingest, arranges the resubmitted ingest package for processing by the rest of the pipeline, and marks the deposit as a resubmission
- Modify IngestDeposit to consider "object exists" exceptions confirmation that the object has already been ingested when the deposit is marked as a resubmission
- Add ReingestPackageForm and "Reingest" link to details pane in status monitor

Introduce resubmitting ingests

---

access/src/main/external/static/js/public/fullRecord.js

Otherwise, we end up triggering the inline viewer when related items are clicked.

Trigger the inline viewer only when the thumbnail at the top of a full record page is clicked

---

deposit/src/main/java/edu/unc/lib/deposit/PrepareResubmitJob.java

- This fixes that resubmitted ingests would cause incorrect counts to appear in the status monitor and IngestDeposit to attempt to ingest the same object more than once

Destroy deposit model in PrepareResubmitJob

---

deposit/src/main/java/edu/unc/lib/deposit/work/DepositGraphUtils.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo3/IngestDepositTest.java

- Addresses an issue where IngestDeposit would ingest the same object twice if it appeared twice in a bag, which appears to occur if other jobs are run more than once.

Avoid adding duplicate PIDs in DepositGraphUtils

---

Capfile

- tomcat:restart is now restart:tomcat to match wording of other tasks
- added tail:deposit task

Flip noun-verb order in service tasks, add tailing of deposit log

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/ManagementClient.java
persistence/src/main/java/edu/unc/lib/dl/services/DigitalObjectManagerImpl.java

- Make sure the lastModifiedDate parameter is actually added when attempting to modify a datastream
- Retrieve a datastream's metadata before retrieving its content so that we have its last modified date to millisecond resolution, rather than second resolution as available from the Last-Modified header
- Clean up debug logging in move methods (removeChildren, addChildren, cleanupRemovedChildren)

Ensure that we are actually asking for optimistic locking for moves

---

persistence/src/test/java/edu/unc/lib/dl/services/DigitalObjectManagerMoveTest.java

DigitalObjectManagerImpl uses managementClient#getDatastream rather than tripleStoreQueryService#hasDisseminator now.

Fix move tests

---

solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/collection/RLASupplementalFilter.java

E.g. rather than looking for an identifier element with the ID attribute value "rla_catalog_number", just look for a top level element with that ID attribute value.

Use just the ID attribute to match RLA metadata elements

---

access-common/src/test/resources/search.properties
access/src/test/resources/search.properties
solr-search/src/main/java/edu/unc/lib/dl/search/solr/util/SolrSettings.java
solr-search/src/test/java/edu/unc/lib/dl/search/solr/util/SolrSettingsTest.java
solr-search/src/test/resources/search.properties

Not particularly elegant, but it seemed better to duplicate the solr parameter cleaning method minus the * character versus unescaping the character.

Wildcard searching

---

access/src/main/external/static/css/admin/admin_forms.css
access/src/main/external/static/css/cdr_admin.css
access/src/main/external/static/js/admin/src/ResultObjectActionMenu.js
access/src/main/external/static/js/admin/src/ResultView.js
access/src/main/external/static/js/admin/src/action/ExportMetadataXMLBatchAction.js
access/src/main/external/static/js/cdr-admin.js
access/src/main/external/static/templates/admin/exportMetadataForm.html
admin/src/main/java/edu/unc/lib/dl/admin/controller/ExportXMLController.java
admin/src/main/java/edu/unc/lib/dl/admin/controller/SearchController.java
admin/src/main/webapp/WEB-INF/uiapp-servlet.xml
fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/DatastreamDocument.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/ManagementClient.java
persistence/src/main/java/edu/unc/lib/dl/services/DigitalObjectManager.java
persistence/src/main/java/edu/unc/lib/dl/services/DigitalObjectManagerImpl.java
persistence/src/test/java/edu/unc/lib/dl/services/DigitalObjectManagerImplTest.java
persistence/src/test/java/edu/unc/lib/dl/services/DigitalObjectManagerMoveTest.java

Exports an XML document containing the MODS for a set of selected objects.  The set can either be specified as a tree starting from a selected folder or by selecting a set of specific objects via the admin interface.  The exported XML document is sent to the provided email address (or the user's default email address).
Moved getXMLDatastreamIfExists from DigitalObjectManager to ManagementClient so that it can be more broadly used, and because it's a more fitting home

Xml export

---

services/src/main/java/edu/unc/lib/dl/cdr/services/solr/EmbargoUpdateService.java
services/src/main/resources/edu/unc/lib/dl/cdr/services/solr/embargo-update-candidates.sparql
services/src/main/resources/scheduled-events.properties
services/src/main/webapp/WEB-INF/service-context.xml

Refactored embargo service to remove embargo relations when the embargo expires, and record the expired embargo in premis.  Processes all expired embargoes instead of those within a window to avoid the risk of embargoes never lifting

Embargo clearing

---

services/src/main/java/edu/unc/lib/dl/cdr/services/processing/SolrUpdateConductor.java

Switched fedora:ingest message indexing operation from recursive to single object indexing to prevent excessive indexing and prevent exceptions caused by trying to index children before their are ingested

Premature indexing

---

deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
metadata/src/main/java/edu/unc/lib/dl/util/DepositStatusFactory.java
metadata/src/main/java/edu/unc/lib/dl/util/RedisWorkerConstants.java

Whenever a deposit fails or finishes, a field in a hash with a key of today's date is incremented. The number of finished and failed deposits is recorded, along with counts per job class name.
To get metrics for a particular day:
> HGETALL deposit-metrics:2015-08-07
1) "finished"
2) "1"
3) "failed"
4) "2"
5) "failed-job:edu.unc.lib.deposit.normalize.CDRMETS2N3BagJob"
6) "1"
7) "failed-job:edu.unc.lib.deposit.validate.VirusScanJob"
8) "1"

Record deposit metrics.

---

deposit/src/main/java/edu/unc/lib/deposit/normalize/BioMedCentralExtrasJob.java

* Fixed bug where biomed titles weren't being assigned to files because the primary article XML filename ends with a S# suffix, which usually indicates supplemental files.  No longer depending on the filename of the file to determine if it is the primary article XML and instead checking mimetype and then inspecting the file.
* Using the filename as the label when no title is present.

Biomed title assignment issues

---

deposit/src/main/java/edu/unc/lib/deposit/work/DepositEmailHandler.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/main/resources/email_html.txt
deposit/src/main/resources/email_text.txt
fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/ManagementClient.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/util/VocabularyHelperManager.java

* Wait for the repository to become available before initializing the departments vocabulary to prevent VocabularyEnforcementJob from failing due to an NPE
* Store a failure message for non-JobFailureExceptions so that the mail sender will realize the job failed
* Check that the ingested count variable is set in deposit email template so that it won't throw an exception when the deposit fails before the ingest job

Fixes for deposit emails related to vocab enforcement failures

---

deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/main/resources/service-context.xml
deposit/src/test/resources/service-context.xml
metadata/src/main/java/edu/unc/lib/dl/util/RedisWorkerConstants.java

Verifying that jobs are not already queued for a deposit before resuming or re-enqueuing during service startup to prevent duplicate jobs being created

Prevent duplicate deposit jobs from enqueuing when resuming

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo3/IngestDeposit.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo3/IngestDepositTest.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/ManagementClient.java
metadata/src/main/java/edu/unc/lib/dl/xml/RDFXMLUtil.java
persistence/src/main/java/edu/unc/lib/dl/services/DigitalObjectManager.java
persistence/src/main/java/edu/unc/lib/dl/services/DigitalObjectManagerImpl.java
persistence/src/test/java/edu/unc/lib/dl/services/DigitalObjectManagerImplTest.java
persistence/src/test/java/edu/unc/lib/dl/services/DigitalObjectManagerMoveTest.java
services-worker/src/main/java/edu/unc/lib/dl/cdr/services/AbstractFedoraEnhancement.java
services-worker/src/main/java/edu/unc/lib/dl/cdr/services/imaging/ImageEnhancement.java
services-worker/src/main/java/edu/unc/lib/dl/cdr/services/imaging/ThumbnailEnhancement.java
services-worker/src/main/java/edu/unc/lib/dl/cdr/services/techmd/TechnicalMetadataEnhancement.java
services-worker/src/main/java/edu/unc/lib/dl/cdr/services/text/FullTextEnhancement.java
services-worker/src/main/resources/service-context.xml
services-worker/src/test/java/edu/unc/lib/dl/cdr/services/imaging/ImageEnhancementServiceITCase.java
services-worker/src/test/java/edu/unc/lib/dl/cdr/services/imaging/ThumbnailEnhancementServiceITCase.java
services-worker/src/test/java/edu/unc/lib/dl/cdr/services/techmd/TechnicalMetadataEnhancementServiceITCase.java
services-worker/src/test/java/edu/unc/lib/dl/cdr/services/techmd/TechnicalMetadataEnhancementTest.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/PublishRestController.java
services/src/main/webapp/WEB-INF/service-context.xml
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/managers/ContainerManagerImpl.java

* Created RDFXMLUtil to perform some of the basic RELS-EXT manipulation we frequently perform.
* Switched all relationship adding methods over to using optimstic locking.
* Removed relationship modifying methods from DigitalObjectManager, moved RELS-EXT updating method to ManagementClient.
* Normalized the parameters for relationship updating methods.
* Updated enhancements to use local client instead of referencing their services instance repeatedly, removed relationship setting methods, and switched to setting exclusive triples in a few cases where it makes more sense
* Removed some dead code and tests related to relationships

Relationship updating cleanup

---

admin/src/main/java/edu/unc/lib/dl/admin/controller/EditLabelController.java
admin/src/main/java/edu/unc/lib/dl/admin/controller/ExportXMLController.java
admin/src/main/webapp/WEB-INF/access-fedora-context.xml
admin/src/main/webapp/WEB-INF/uiapp-servlet.xml
fcrepo-clients/src/main/java/edu/unc/lib/dl/util/VocabularyHelperManager.java

Fixing an authorization exception in the admin ui which occurs when a user with insufficient privileges to access vocabulary objects is the first user to attempt to edit descriptions

Fix infinite authz exception in admin

---

access/src/main/webapp/WEB-INF/jsp/common/thumbnail.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/collectionRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/listAccessRecord.jsp

When there is no target specified for a thumbnail, default to setting the href to its record page. Provide a target for the fullRecord templates that were missing it.

Fix thumbnail links to front page

---

deposit/src/main/java/edu/unc/lib/deposit/work/DepositEmailHandler.java
deposit/src/main/resources/completed_html.txt
deposit/src/main/resources/completed_text.txt
deposit/src/main/resources/failed_html.txt
deposit/src/main/resources/failed_text.txt
deposit/src/main/resources/service-context.xml
deposit/src/test/resources/service-context.xml

- Link to materials if public, display the embargo date if embargoed, or note that the materials may need to be reviewed if not embargoed and not public. If there is more than one top-level object, we link to the container.
- Split the deposit email templates into "completed" and "failed".
- Send a message to the administrator when a deposit fails.

Include more information in deposit notification emails

---

access/src/main/webapp/WEB-INF/jsp/common/surveyBanner.jsp

"#" is relative to the base href, so use javascript:void(0) instead.

Avoid navigating away from the current page when the survey hide link is clicked.

---

static/js/public/src/JP2Viewer.js

Loading gif was never removed when an image loaded. However, without deferring its removal it never displayed.

Loading gif never removed when an image loaded

---

static/recordTransformations/modsToFullRecord.xsl

The group-by attribute of the for-each-group element in the "modsOriginDates" template incorrectly selected the displayLabel attribute on dateIssued, dateCreated, etc. elements, rather than on the originInfo element containing them.

Fix selector for @displayLabel on originInfo dates

---

admin/src/main/java/edu/unc/lib/dl/admin/controller/ExportController.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/BriefObjectMetadataBean.java

I have deployed to QA and the exported .csv file now has a column for content status that is populated with appropriate values.

Add mods column to csv export

---

deposit/pom.xml
deposit/src/main/java/edu/unc/lib/deposit/CleanupDepositJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/AbstractFileServerToBagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/DirectoryToBagJob.java
deposit/src/main/java/edu/unc/lib/deposit/staging/StagingException.java
deposit/src/main/java/edu/unc/lib/deposit/staging/StagingPolicy.java
deposit/src/main/java/edu/unc/lib/deposit/staging/StagingPolicyManager.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ValidateFileAvailabilityJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/VirusScanJob.java
deposit/src/test/java/edu/unc/lib/deposit/CleanupDepositJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/AbstractDepositJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/DirectoryToBagJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/staging/StagingPolicyManagerTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ValidateFileAvailabilityJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/VirusScanJobTest.java
deposit/src/test/resources/staging_config.json
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/FedoraPID.java
persistence/pom.xml
pom.xml

Removes staging areas module from usage in the CDR, adds new but significantly reduced staging policy classes to deposit app, updates deposit jobs and tests accordingly, adds missing unit tests for deposit jobs that involved staging.

Remove staging-areas module

---

static/css/cdr_common.css

added media query to fix word spacing bug in safari

Fix header word spacing for safari

---

access/src/main/webapp/WEB-INF/jsp/searchResults/browseResultEntry.jsp
access/src/main/webapp/WEB-INF/jsp/searchResults/searchResultEntry.jsp
access/src/main/webapp/WEB-INF/jsp/searchResults/selectedContainerEntry.jsp

While the issue was that the operator was backwards (|| instead of &&), it turns out that ONLY folders and collections were displaying last updated fields, so there's no reason to keep the code that displayed them in

Removed display of last modified field from result entries

---

solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetRelationsFilter.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetRelationsFilterTest.java

@ben let me know if you see any improvements i can make. i’ll be back in the office on 7/6 and can make tweaks before the sprint finishes.
in particular, i’m not clear if we want to throw an indexing exception when there is no primary object (e.g., if somehow a folder object were to be passed to the filter, which seems unlikely) or simply return, as i have it now.

Cdr 1858 update set relations filter

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ValidateContentModelJobTest.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/BinaryObject.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/ContentObject.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/DepositRecord.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/FileObject.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactory.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/WorkObject.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/BinaryObjectIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/BinaryObjectTest.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/FileObjectIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactoryIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactoryTest.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/WorkObjectIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/WorkObjectTest.java
pom.xml
services-camel/src/test/java/edu/unc/lib/dl/services/camel/GetBinaryProcessorIT.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/replication/ReplicationProcessorIT.java

NB: we have identified a Fedora bug that prevents md5 hashes from being stored inside a transaction, so getChecksums() in BinaryObject is not currently guaranteed to return all of the checksums attached to a file

Cdr 1931 binaries use md5

---

solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/indexing/SolrUpdateDriver.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/action/BaseEmbeddedSolrTest.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/action/IndexTreeInplaceActionTest.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/indexing/SolrUpdateDriverTest.java

Driver only checking req fields when indexing full doc.  Provides required fields info to tests that needed it.

Required fields followup

---

access/pom.xml
access/src/main/webapp/WEB-INF/access-fedora-context.xml
access/src/test/resources/service-context.xml
admin/pom.xml
deposit/src/main/webapp/WEB-INF/fcrepo-clients-context.xml
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/FcrepoClientFactory.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/TransactionalFcrepoClient.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/TransactionalFcrepoClientIT.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/move/MoveObjectsService.java
pom.xml
services-camel/src/main/webapp/WEB-INF/service-context.xml
services/src/main/resources/cdr-services.properties
services/src/main/webapp/WEB-INF/access-fedora-context.xml
services/src/main/webapp/WEB-INF/service-context.xml
services/src/main/webapp/WEB-INF/solr-search-context.xml
services/src/main/webapp/WEB-INF/sword-context.xml

Gets services webapp deployable on FES and deals with issues related to it being deployed in multi-server environment.
* Adds optional Host header to requests to Fedora to deal with cross domain requests (by default, fedora responds with URIs that match the URI it was addressed at.  So if one service addresses fedora at repo.example.com and another as localhost, they will get back different URIs and triples) that was impacting indexing to triple store.
* Adds missing initialization of move and acl retrieval services
* Adjusts property names to match deployed values

Bxc-2141-4 Services config fixes

---

access-common/src/main/java/edu/unc/lib/dl/ui/controller/AbstractSolrSearchController.java
access-common/src/main/java/edu/unc/lib/dl/ui/controller/AbstractStructureResultsController.java
access-common/src/main/java/edu/unc/lib/dl/ui/controller/StructureResultsController.java
access-common/src/main/java/edu/unc/lib/dl/ui/service/SolrQueryLayerService.java
access/src/main/java/edu/unc/lib/dl/ui/controller/SearchActionController.java
admin/src/main/java/edu/unc/lib/dl/admin/controller/DashboardController.java
admin/src/main/java/edu/unc/lib/dl/admin/controller/ExportController.java
admin/src/main/java/edu/unc/lib/dl/admin/controller/VocabularyController.java
etc/server.properties
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/SearchRestController.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/HierarchicalBrowseRequest.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/IdListRequest.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/SearchRequest.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/SimpleIdRequest.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/ObjectPathFactory.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/SolrSearchService.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/StructureQueryService.java
solr-search/src/test/java/edu/unc/lib/dl/search/solr/service/ObjectPathFactoryIT.java
solr-search/src/test/java/edu/unc/lib/dl/search/solr/service/StructureQueryServiceIT.java

* Fixes permission issue that was preventing filtering to specific containers from working
* Solr queries depending on search requests to provide access groups consistently
* Using PID class in solr search requests for better control over formatting of ids.
* Removed duplicate fcrepo.baseUri to fix issue retrieving info from fedora in access interface

Bxc-2166/2161 - Navigation issues

---

etc/services-camel.properties
services-camel/src/main/java/edu/unc/lib/dl/services/camel/BinaryMetadataProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/enhancements/EnhancementRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/fulltext/FulltextRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/images/ImageEnhancementsRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/routing/MetaServicesRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/util/CdrFcrepoHeaders.java
services-camel/src/main/webapp/WEB-INF/service-context.xml
services-camel/src/test/java/edu/unc/lib/dl/services/camel/BinaryMetadataProcessorTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/enhancements/EnhancementRouterIT.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/images/ImageEnhancementsRouterTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/routing/MetaServicesRouterTest.java
services-camel/src/test/resources/config.properties
services-camel/src/test/resources/enhancement-router-it-config.properties
services-camel/src/test/resources/enhancement-router-it-context.xml

Resolves issues with solr indexing of new items before they are indexed in the triple store by breaking enhancements off into a separate queue and using cloned asynchronous calls to trigger them. The effect is that triple indexing is prioritized and generally happens very quickly.
Lays groundwork for allowing subsets of enhancements to be run and for enhancements to be triggered by user requests.
Replication is disabled for the time being while we revisit our approach

Bxc 2190 - Prioritize triple indexing

---

solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/ChildrenCountService.java

Fixes a bug which matching child counts to result entries in a search result which is causing list and search views to fail.

Fix Count Matching Index

---

security/src/main/java/edu/unc/lib/dl/acl/filter/RequireLoginFilter.java
security/src/main/java/edu/unc/lib/dl/acl/filter/StoreUserAccessControlFilter.java
security/src/main/java/edu/unc/lib/dl/acl/util/RemoteUserUtil.java
security/src/test/java/edu/unc/lib/dl/acl/filter/StoreUserAccessControlFilterTest.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/filters/DepositorAccessControlFilter.java

User name was not able to be retrieved due to jetty setup, so user name is now retrieved from header when not available from request.

Fix retrieval of user in jetty without ajp

---

Makefile
access/pom.xml
access/src/main/webapp/WEB-INF/access-fedora-context.xml
admin/src/main/webapp/WEB-INF/service-context.xml
deposit/src/main/webapp/WEB-INF/fcrepo-clients-context.xml
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/FcrepoClientFactory.java
pom.xml
services-camel/src/main/java/edu/unc/lib/dl/services/camel/enhancements/EnhancementRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/routing/MetaServicesRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/util/EventTypes.java
services-camel/src/main/webapp/WEB-INF/service-context.xml
services-camel/src/test/java/edu/unc/lib/dl/services/camel/routing/MetaServicesRouterTest.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/ItemInfoRestController.java
services/src/main/webapp/WEB-INF/access-fedora-context.xml
services/src/main/webapp/WEB-INF/service-context.xml
services/src/main/webapp/WEB-INF/sword-context.xml
static/js/admin/src/CreateContainerForm.js

* Enables basic auth against fedora, which is now the default
* Renames the ROOT.war to access.war for consistency
* Updates camel dependencies and behaviors for fedora5
* Fix to allow creation of AdminUnits
* Updates to properties being used to eliminate some unused or duplicate properties.
This will not work on qa at the moment since it requires fedora 5

Fixes to work against dev vm/fedora 5

---

pom.xml

Downgrade camel to 2.20 since it is used by fcrepo-camel and 2.21+ renames a package, resulting in a class not found error on startup. Revisit once fcrepo-camel upgrades its dependency

Downgrade camel to 2.20 

---

static/js/admin/src/AbstractForm.js
static/js/admin/src/EditLabelForm.js
static/js/admin/src/RemoteStateChangeMonitor.js
static/templates/admin/editLabelForm.html

https://jira.lib.unc.edu/browse/BXC-2401
Gets basic edit label functionality working through the admin ui.
Could use some polish, in terms of how it should behave when MODS is present.
The refresh functionality is also not working, but that is a separate issue.

BXC-2401 - Edit label working

---

services/src/main/java/edu/unc/lib/dl/cdr/services/rest/ItemInfoRestController.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/ItemInfoRestControllerIT.java
services/src/test/resources/item-info-it-servlet.xml

https://jira.lib.unc.edu/browse/BXC-2398
Apparently the refresh function was already working, after some early fixes, was slow on the VM so I didn't notice. This PR makes the refresh method use real access controls, makes small improvements to its responses, and adds tests

BXC-2398 - Admin results automatic refreshing

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestDepositRecordJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/DepositRecord.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectDriver.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/DepositRecordIT.java
metadata/src/main/java/edu/unc/lib/dl/rdf/Cdr.java

* Switches to using cdr:originalDeposit relation to link to deposit records
* Deposit recorded created before content objects ingested, and originalDeposit link added during content ingest

BXC-2419 - Reverse deposit to object link direction

---

metadata/src/main/java/edu/unc/lib/dl/util/ResourceType.java

https://jira.lib.unc.edu/browse/BXC-2437
Change display order values for resource types so that works will appear before files, and to add more spacing in case more types are added in the future

BXC-2437 - Change display order values for resource types

---

access/src/main/webapp/WEB-INF/access-fedora-context.xml
admin/src/main/webapp/WEB-INF/access-fedora-context.xml
deposit/src/main/webapp/WEB-INF/service-context.xml
deposit/src/test/resources/spring-test/cdr-client-container.xml
fcrepo-clients/src/main/java/edu/unc/lib/dl/acl/fcrepo4/ObjectAclFactory.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectLoader.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/SanitizeServerManagedTriplesSelector.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/acl/fcrepo4/AccessControlServiceImplIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/acl/fcrepo4/ObjectACLFactoryTest.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/acl/fcrepo4/ObjectPermissionEvaluatorIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/test/AclModelBuilder.java
fcrepo-clients/src/test/resources/spring-test/cdr-client-container.xml
metadata/src/main/java/edu/unc/lib/dl/rdf/Memento.java
metadata/src/main/java/edu/unc/lib/dl/rdf/Premis.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/acl/StaffRoleAssignmentService.java
persistence/src/main/java/edu/unc/lib/dl/services/OperationsMessageSender.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/acl/StaffRoleAssignmentServiceIT.java
persistence/src/test/resources/spring-test/cdr-client-container.xml
persistence/src/test/resources/spring-test/staff-role-service-container.xml
security/src/main/java/edu/unc/lib/dl/acl/util/RoleAssignment.java
security/src/main/java/edu/unc/lib/dl/acl/util/UserRole.java
services-camel/src/main/webapp/WEB-INF/service-context.xml
services-camel/src/test/resources/solr-indexing-it-context.xml
services/src/main/webapp/WEB-INF/access-fedora-context.xml
services/src/test/resources/access-control-retrieval-it-servlet.xml

https://jira.lib.unc.edu/browse/BXC-2444
* Adds service for committing role assignments to fedora
* Refactors ObjectAclFactory to retrieve ACLs from fedora directly rather than triple store, in order to allow for immediate retrieval without waiting for reindexing
* Updates server managed triple sanitization to match the requirements of fedora 5
* Updates to UserRole class to calculate common values once.

BXC-2444 - Staff role assignment service

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/FedoraTransaction.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectLoader.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/acl/StaffRoleAssignmentService.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/acl/StaffRoleAssignmentServiceIT.java
security/src/main/java/edu/unc/lib/dl/acl/util/RoleAssignment.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/UpdateAccessControlController.java
services/src/main/webapp/WEB-INF/access-fedora-context.xml
services/src/main/webapp/WEB-INF/service-context.xml
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/UpdateStaffRolesIT.java
services/src/test/resources/update-access-it-servlet.xml

https://jira.lib.unc.edu/browse/BXC-2443
* Adds API endpoint for setting staff roles
* Updates staff role setting to take place in a transaction with its premis log updates
* Add method for cancelling transactions that doesn't throw an exception, so that we can throw the original unwrapped exception.

BXC-2443 - API For Updating Staff Roles

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/acl/fcrepo4/AclFactory.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/acl/fcrepo4/InheritedAclFactory.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/acl/fcrepo4/ObjectAclFactory.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/acl/fcrepo4/InheritedAclFactoryTest.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/acl/fcrepo4/ObjectACLFactoryTest.java
pom.xml
security/pom.xml
security/src/main/java/edu/unc/lib/dl/acl/util/RoleAssignment.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/AccessControlRetrievalController.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/UpdateAccessControlController.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/RetrieveStaffRolesIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/UpdateStaffRolesIT.java
static/js/admin/vue-permissions-editor/src/components/modalEditor.vue
static/js/admin/vue-permissions-editor/src/components/staffRoles.vue
static/js/admin/vue-permissions-editor/tests/unit/staffRoles.spec.js

https://jira.lib.unc.edu/browse/BXC-2453
* Returns the PID of the object where a role+principal is being assigned.
* After discussion, decided to leave multiple role assignments for the same principal in staff permission response since they now indicate where they are assigned.
* Explicitly disallow assigning multiple roles to a principal on the same object in the API, so it agrees with the UI.
* Some updates to java version setting and including javax stuff that causes problems if being built on system with java 11 installed.

BXC-2453 - Return id of the object a role is assigned to

---

fcrepo-clients/src/test/java/edu/unc/lib/dl/test/AclModelBuilder.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/AccessControlRetrievalController.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/UpdateAccessControlController.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/DatastreamRestControllerIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/RetrieveMODSIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/RetrievePatronRolesIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/RetrieveStaffRolesIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/AbstractAPIIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/AddContainerIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/EditLabelIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/ExportXMLIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/MarkForDeletionIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/MoveObjectsIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/SetAsPrimaryObjectIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/UpdateDescriptionIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/UpdateStaffRolesIT.java
static/js/admin/vue-permissions-editor/src/components/staffRoles.vue
static/js/admin/vue-permissions-editor/tests/unit/staffRoles.spec.js

https://jira.lib.unc.edu/browse/BXC-2442
* Adds API endpoint for getting patron access control details, in the form:
```
{
'inherited': {
'roles: [ { 'principal': 'someuser', 'role': 'somerole' } ],
'embargo': 'date',
'deleted': boolean
},
'assigned': {
'roles: [ { 'principal': 'someuser', 'role': 'somerole' } ],
'embargo': 'date',
'deleted': boolean
}
}
```
* Updates response and update request format for staff ACLs to be wrapped in an object with the 'roles' key to match the format of the patron response.
* Refactored API integration tests to move common needs into parent class

BXC-2442 - Retrieve patron access control info

---

Makefile
pom.xml
static/js/admin/vue-permissions-editor/package.json
static/js/vue-cdr-access/package.json

Add build type, so Vue debug extensions work in development, but are excluded in production environment.
Depends on https://gitlab.lib.unc.edu/cdr/boxc-ansible/merge_requests/23
https://jira.lib.unc.edu/browse/BXC-2500

Specify deploy type for Vue JS builds

---

.gitmodules
pom.xml
static/js/vue-cdr-access/tests/unit/worksOnly.spec.js

Maven central seems to have suddenly stopped working with http and the restlet repo appears to have moved. Needed to update the oai4solr plugin

Maven repository fixes

---

services/src/main/java/edu/unc/lib/dl/cdr/services/processing/AddContainerService.java
services/src/main/webapp/WEB-INF/service-context.xml
services/src/test/java/edu/unc/lib/dl/cdr/services/processing/AddContainerServiceTest.java
services/src/test/resources/add-container-it-servlet.xml

Fixes a bug that was preventing containers from being created due to trying to look up their storage location before they were fully ingested.

Assign a storage location to newly created containers

---

deposit/src/main/java/edu/unc/lib/deposit/normalize/AbstractFileServerToBagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/CDRMETS2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/NormalizeFileObjectsJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/VocabularyEnforcementJob.java
deposit/src/main/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ValidateDescriptionJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestDepositRecordJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/NormalizeFileObjectsJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/VocabularyEnforcementJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ValidateDescriptionJobTest.java

https://jira.lib.unc.edu/browse/BXC-2536
* PREMIS, MODS and FITS metadata files are now stored to and retrieved from hashed directories during deposit.
* Consolidated path generation for these files into common helper methods

BXC-2536 - Use hashed paths for deposit metadata files

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/event/RepositoryPremisLogger.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactory.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/persist/api/storage/StorageType.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/storage/HashedPosixStorageLocation.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/storage/StorageLocationManagerImpl.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/BinaryTransferSessionImpl.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/FSToFSTransferClient.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/FSToPosixTransferClient.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/StreamToFSTransferClient.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/StreamToPosixTransferClient.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/storage/HashedFilesystemStorageLocationTest.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/storage/HashedPosixStorageLocationTest.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/transfer/FSToFSTransferClientTest.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/transfer/FSToPosixTransferClientTest.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/transfer/StreamToFSTransferClientTest.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/transfer/StreamToPosixTransferClientTest.java

Resolves two separate issues that were causing premis updates to fail on dcr-test after the first modification
* Forces setting of size for premis log external binary as fedora was retrieving the incorrect size, only within this environment. There is a bug ticket to potentially try to investigate this further in the future.
* Adds support for posix based storage location that allows file permissions to be set on updated/created files.

Fix Premis updating

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
metadata/src/main/java/edu/unc/lib/dl/util/DepositMethod.java
metadata/src/main/java/edu/unc/lib/dl/util/PackagingType.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/BannerUtility.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/MigrationCLI.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/SubmitDepositCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/TransformContentCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerManager.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentTransformationService.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/DepositModelManager.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/DepositSubmissionService.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/fcrepo3/DatastreamVersion.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/fcrepo3/FoxmlDocumentHelpers.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/paths/PathIndex.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/deposit/DepositSubmissionServiceTest.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/fcrepo3/FoxmlDocumentBuilder.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/ingest/PreconstructedDepositHandler.java

https://jira.lib.unc.edu/browse/BXC-2541
This PR allows for content structures to be deposited into bxc, with the mods and filename info. There seem to be some indexing issues that generally required me to reindex the new collection after deposit completed which should be addressed separately.
Changes:
* Adds command for submitting deposits to the deposit pipeline
* adds service and deposit handler for submitting these types of deposits
* Adds option for the transform content job to immediately submit the result for ingest
* Populates the root deposit record entry for transformed deposits, which is required by the deposit pipeline
* Adds flag for generating new PIDs for transformed objects, allowing test sets to be ingested multiple times
* Sets a label (which serves as a fallback title …

BXC-2541 - Submit Migration Deposits

---

static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/src/components/worksOnly.vue
static/js/vue-cdr-access/tests/unit/displayWrapper.spec.js

* Have show works box stay visible, even if no search results are returned.
* Coerce work_only value on mounted()
https://jira.lib.unc.edu/browse/BXC-2569

Show works box stays visible, even if no search results are returned

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/acl/fcrepo4/ContentObjectAccessRestrictionValidator.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/acl/fcrepo4/ContentObjectAccessRestrictionValidatorTest.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ACLTransformationHelpers.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/fcrepo3/ContentModelHelper.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ACLTransformationHelpersTest.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java

https://jira.lib.unc.edu/browse/BXC-2532
https://jira.lib.unc.edu/browse/BXC-2533
See the Permissions Migration section of https://confluence.lib.unc.edu/display/RAT/Data+Migration+Planning for details.
* Migrates patron access controls for all content object types
* transforms non-role assignment settings (like publication status, inheritance flag) into role assignments.
* unit patron access assignments are moved to their child collections
* Migrates staff access controls
* Allows the canProcess role to be assigned during ingest.

BXC-2532/2533 - Migrate access controls

---

deposit/src/main/java/edu/unc/lib/deposit/normalize/DirectoryToBagJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositEmailHandler.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/DirectoryToBagJobTest.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/FSToPosixTransferClient.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/IngestSourceController.java

https://jira.lib.unc.edu/browse/BXC-2576
https://jira.lib.unc.edu/browse/BXC-2590
https://jira.lib.unc.edu/browse/BXC-2591
* Downgrades failure when unable to set file permissions after moving a file into a POSIX storage location during ingest to a debug rather than a thrown exception.
* Fixes a transaction failure when sending emails after completing a migration deposit
* Fixes bug which caused all directory deposits to fail because they were not expecting uris

BXC-2576/2590/2591 - Deposit bug fixes

---

access/src/main/webapp/WEB-INF/jsp/common/footer.jsp
access/src/main/webapp/WEB-INF/jsp/common/header.jsp
access/src/main/webapp/WEB-INF/jsp/common/headerSmall.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/fileRecord.jsp
admin/src/main/webapp/WEB-INF/jsp/common/header.jsp
admin/src/main/webapp/WEB-INF/jsp/edit/description.jsp
static/js/admin/src/ResultView.js

https://jira.lib.unc.edu/browse/BXC-2390
* Fixes double slash after application name in links between applications
* Resolves most cases where "access" shows up in urls. The Log on and Contact Us links are still incorrect until a separate ansible ticket is merged
* Removes the "Home" link from the front page (it was already gone from interior pages)

BXC-2390 - Links between apps and Header fixes

---

access-common/src/main/java/edu/unc/lib/dl/ui/service/FedoraContentService.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/model/DatastreamType.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/DatastreamController.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/DatastreamRestControllerIT.java
static/js/admin/src/ResultObjectActionMenu.js
static/js/admin/src/URLUtilities.js
static/js/admin/src/action/ChangeLocationAction.js

https://jira.lib.unc.edu/browse/BXC-2580
* Adds link to download premis log per object in the admin ui
* Updates datastream controller and supporting service to be able to return the premis

BXC-2580 - View premis log

---

static/js/admin/src/ResultTableView.js

https://jira.lib.unc.edu/browse/BXC-2596
Fix failure caused by getting the type of container when there is no container, which was causing searching "Everywhere" to result in a blank search in the admin ui.

BXC-2596 - Fix blank admin search

---

deposit/src/main/java/edu/unc/lib/deposit/validate/VirusScanJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/validate/VirusScanJobTest.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/event/FilePremisLogger.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/event/PremisEventBuilder.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/event/RepositoryPremisLogger.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/event/FilePremisLoggerTest.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/event/RepositoryPremisLoggerIT.java
metadata/src/main/java/edu/unc/lib/dl/rdf/Premis.java
metadata/src/main/java/edu/unc/lib/dl/rdf/Prov.java
metadata/src/test/java/edu/unc/lib/dl/sparql/SparqlUpdateHelperTest.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/premis/AbstractPremisToRdfTransformer.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/premis/ContentPremisToRdfTransformer.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/premis/AbstractPremisToRdfTransformerTest.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/premis/ContentPremisToRdfTransformerTest.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/premis/DepositRecordPremisToRdfTransformerTest.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/premis/TestPremisEventHelpers.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/premis/TransformContentPremisServiceTest.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/premis/TransformDepositPremisServiceTest.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/acl/PatronAccessAssignmentServiceIT.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/acl/StaffRoleAssignmentServiceIT.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/destroy/DestroyObjectsJobIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/DatastreamRestControllerIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/MarkForDeletionIT.java

https://jira.lib.unc.edu/browse/BXC-2557
https://jira.lib.unc.edu/browse/BXC-2558
https://jira.lib.unc.edu/browse/BXC-2559
This PR depends on https://github.com/UNC-Libraries/Carolina-Digital-Repository/pull/915
* All premis log files now include `rdf:type premis:Representation`
* premis:hasEvent has been replaced by two Prov relations
* Many agent and event properties have been replaced by RDF, RDFS, and FOAF properties based on https://docs.google.com/spreadsheets/d/1fQIsYbRYRNeDvSm_SKwjXVSrn18mXu3W96A-n5vVVCg/edit#
* Adds event outcomes

BXC-2557/2558/2559 - Update PREMIS properties

---

access-common/src/main/java/edu/unc/lib/dl/ui/service/FedoraContentService.java
access/src/main/java/edu/unc/lib/dl/ui/controller/FedoraContentController.java
access/src/main/java/edu/unc/lib/dl/ui/controller/FullRecordController.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/event/RepositoryPremisLogger.java
metadata/src/main/java/edu/unc/lib/dl/util/RDFModelUtil.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/edit/EditTitleService.java

https://jira.lib.unc.edu/browse/BXC-2577
* Close inputstreams from `BinaryObject.getBinaryStream` via `try` blocks to ensure they are not left open if clients abort the connection partway through reading.

BXC-2577 - Close binary object input streams

---

services-camel/src/main/java/edu/unc/lib/dl/services/camel/images/AddDerivativeProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/images/ImageDerivativeProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/images/ImageEnhancementsRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/util/CdrFcrepoHeaders.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/images/AddDerivativeProcessorTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/images/ImageEnhancementsRouterTest.java

https://jira.lib.unc.edu/browse/BXC-2564
* Special treatment for image files that have multiple layers
* Added exclusions for image mimetypes that should be processed
* Improved error logging for derivative failures

BXC-2564 - Image derivative fixes

---

persistence/src/main/java/edu/unc/lib/dl/services/RunEnhancementsMessageHelpers.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/BinaryEnhancementProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/enhancements/EnhancementRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/routing/MetaServicesRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/solr/SolrIngestProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/solr/SolrRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/solrUpdate/SolrUpdateRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/util/CdrFcrepoHeaders.java
services-camel/src/main/webapp/WEB-INF/solr-indexing-context.xml
services-camel/src/test/java/edu/unc/lib/dl/services/camel/BinaryEnhancementProcessorTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/enhancements/EnhancementRouterIT.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/routing/MetaServicesRouterTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/solr/SolrIngestProcessorIT.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/solr/SolrIngestProcessorTest.java
services-camel/src/test/resources/config.properties
services-camel/src/test/resources/metaservices-context.xml
services/src/main/java/edu/unc/lib/dl/cdr/services/processing/RunEnhancementsService.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/RunEnhancementsIT.java

https://jira.lib.unc.edu/browse/BXC-2606
* Improves handling of NotFoundExceptions during solr indexing, particular of newly ingested objects after running enhancements
* Should resolve issues where derivatives were not showing up for works, but were for the file where the derivatives came from
* Relies on enhancement pipeline to set mimetype header rather than receiving from run enhancements service
* Removes no longer needed intermediate route bridging fedora to enhancement queue

BXC-2606 - Solr indexing not found handling

---

deposit/src/main/java/edu/unc/lib/deposit/CleanupDepositJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ValidateFileAvailabilityJob.java
deposit/src/test/java/edu/unc/lib/deposit/CleanupDepositJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ValidateFileAvailabilityJobTest.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/persist/api/ingest/IngestSource.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/ingest/FilesystemIngestSource.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/ingest/FilesystemIngestSourceTest.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/ingest/IngestSourceManagerImplTest.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/ingest/IngestSourceTestHelper.java

https://jira.lib.unc.edu/browse/BXC-2624
* Resolves failures in the deposit cleanup job when a file record in a deposit does not exist, which is the result of the file having been moved during the transfer.
* Splits checking if a file exists within an ingest source out from checking if a uri is valid within that source. This is what caused the cleanup jobs to fail.
* Adds related testing.

BXC-2624 - Fix deposit cleanup failures

---

services/src/main/java/edu/unc/lib/dl/cdr/services/rest/TripleStoreMonitorRestController.java

Was throwing a configuration error when mulgara was down since the `@ExceptionHandler` requires parameter.

BXC3 - Exception handler fix

---

access/src/main/webapp/WEB-INF/access-fedora-context.xml
admin/src/main/webapp/WEB-INF/access-fedora-context.xml
deposit/src/main/webapp/WEB-INF/service-context.xml
deposit/src/test/resources/spring-test/cdr-client-container.xml
fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/ContentPathFactory.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fedora/ContentPathFactoryIT.java
fcrepo-clients/src/test/resources/spring-test/cdr-client-container.xml
metadata/src/main/java/edu/unc/lib/dl/exceptions/ObjectHierarchyException.java
migration-util/src/main/resources/spring/service-context.xml
migration-util/src/test/resources/spring-test/cdr-client-container.xml
persistence/src/test/resources/spring-test/acl-service-context.xml
persistence/src/test/resources/spring-test/staff-role-service-container.xml
services-camel/src/main/webapp/WEB-INF/service-context.xml
services-camel/src/main/webapp/WEB-INF/solr-indexing-context.xml
services-camel/src/test/java/edu/unc/lib/dl/services/camel/solr/AbstractSolrProcessorIT.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/solrUpdate/SolrUpdateProcessorIT.java
services-camel/src/test/resources/solr-indexing-it-context.xml
services/src/main/webapp/WEB-INF/access-fedora-context.xml
services/src/test/resources/edit-title-it-servlet.xml
services/src/test/resources/spring-test/acl-service-context.xml
services/src/test/resources/update-staff-it-servlet.xml
static/js/admin/src/action/MoveObjectsAction.js
static/js/admin/src/action/RefreshResultAction.js

https://jira.lib.unc.edu/browse/BXC-2647
* Fixes to move action in admin ui to fix error and cause refreshing/clearing of moved items
* Refactor of ContentPathFactory to pull parent info from fedora rather than triple store. Solr indexing after move operations was happening before the triple store was updated almost every time, resulting in needing to reindex objects for the move operation to appear complete.

BXC-2647 - Fix move operation

---

deposit/src/main/java/edu/unc/lib/deposit/validate/ValidateDestinationJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml
deposit/src/test/java/edu/unc/lib/deposit/validate/ValidateDestinationJobIT.java
deposit/src/test/resources/acl-global-config.properties
fcrepo-clients/src/main/java/edu/unc/lib/dl/acl/fcrepo4/InheritedPermissionEvaluator.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/acl/fcrepo4/InheritedPermissionEvaluatorTest.java

https://jira.lib.unc.edu/browse/BXC-2654
* Adds an early deposit job to make sure the selected destination can receive the deposit before we start transferring content/creating objects
* Fixes issue with getting inherit acls on the content root object which was impacting testing

BXC-2654 - Verify valid destination

---

static/js/vue-cdr-access/src/router.js

Have page scroll to the top when user goes to a new route. Most notably, clicking to the next page from the pagination component would leave you at the bottom of the page.

Have page scroll to the top when user goes to a new route

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/RegisterToLongleafJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/RegisterToLongleafJobTest.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/persist/api/ingest/DepositData.java
metadata/src/main/java/edu/unc/lib/dl/util/RedisWorkerConstants.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/MigrationConstants.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/DepositSubmissionService.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/deposit/DepositSubmissionServiceTest.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/ingest/AbstractDepositHandler.java

https://jira.lib.unc.edu/browse/BXC-2638
https://jira.lib.unc.edu/browse/BXC-2537
* Applies created/modified timestamps supplied in a deposit if the overrideTimestamps flag if provided
* Overrides the deposit record link on objects in an ingest if one was set in the deposit model
* fixes a bug where the deposit id had the wrong pid type
* Fixes issue with longleaf registration which occurs when a deposit does not create a deposit record

BXC-2537/2638 - Deposit migrated timestamps and deposit links

---

deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml
services-camel/pom.xml
services-camel/src/main/java/edu/unc/lib/dl/services/camel/BinaryMetadataProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/enhancements/EnhancementRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/LongleafAggregationStrategy.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/LongleafRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/RegisterToLongleafProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/routing/MetaServicesRouter.java
services-camel/src/main/webapp/WEB-INF/activemq-context.xml
services-camel/src/main/webapp/WEB-INF/service-context.xml
services-camel/src/test/java/edu/unc/lib/dl/services/camel/enhancements/EnhancementRouterIT.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/longleaf/RegisterToLongleafProcessorIT.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/longleaf/RegisterToLongleafProcessorTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/routing/MetaServicesRouterTest.java
services-camel/src/test/resources/enhancement-router-it-config.properties
services-camel/src/test/resources/enhancement-router-it-context.xml
services-camel/src/test/resources/logback-test.xml

https://jira.lib.unc.edu/browse/BXC-2622
* Support registration of binary updates and creations to longleaf via camel routes.
* Registration to longleaf performed in batches
* Deposit longleaf registration job switched into camel processor
Depends on:
https://github.com/UNC-Libraries/longleaf-preservation/pull/26

BXC-2622 - Register updates to longleaf 

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/FedoraTransaction.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/FedoraTransactionRefresher.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/FedoraTransactionRefresherTest.java

https://jira.lib.unc.edu/browse/BXC-2689
*  Perform periodic refresh of transactions during ingest of work objects to address timeouts during ingest of large files
* Adds an utility for refreshing transactions in a background thread

BXC-2689 - Refresh transactions

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactory.java

Add more detail to the error message for checksum mismatch errors when putting binaries to fedora

Improve error message for fixity mismatch

---

deposit/src/main/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/FixityCheckJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/AbstractDepositJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/FixityCheckJobTest.java
metadata/src/main/java/edu/unc/lib/dl/exceptions/InvalidChecksumException.java
metadata/src/main/java/edu/unc/lib/dl/exceptions/UnsupportedAlgorithmException.java
persistence/src/main/java/edu/unc/lib/dl/util/DigestAlgorithm.java
persistence/src/main/java/edu/unc/lib/dl/util/MultiDigestInputStreamWrapper.java

https://jira.lib.unc.edu/browse/BXC-2687
* Adds a specialized job for verifying fixity and generating a default digest for original files. 
* Removes fixity checking from technical metadata job
* Adds mechanism for preventing rollback of changes to the deposit model when a job fails. Enabled this for the transfer binaries job.

BXC-2687 - Deposit SHA1s

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/ClientFaultResolver.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/ConflictException.java
metadata/src/main/java/edu/unc/lib/dl/util/PackagingType.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/TransformContentCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerManager.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/DepositDirectoryManager.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/DepositModelManager.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/AbstractTransformationIT.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/TransformContentCommandIT.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/TransformDepositRecordsCommandIT.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/deposit/AbstractDepositRecordTransformationIT.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/deposit/DepositRecordTransformerIT.java

https://jira.lib.unc.edu/browse/BXC-2718
* Transformation option to generate referenced deposit records which don't exist as fedora objects
* Option for performing dry run of transformation
* Integration tests
* Minor updates for fedora fault resolution and new packaging type for migrations

BXC-2718 - Generate missing migrated deposit records

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/DepositRecordTransformer.java

https://jira.lib.unc.edu/browse/BXC-2713
To avoid concurrent object creation same name sibling issue in fedora, which seems to be commonly triggered by this use case

BXC-2713 - Remove transactions from deposit record transformer

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/StaffOnlyPermissionJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/AssignStorageLocationsJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/NormalizeFileObjectsJob.java
deposit/src/main/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ValidateContentModelJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ValidateDestinationJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/VerifyObjectsAreInFedoraService.java
deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositGraphUtils.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/action/UpdateObjectAction.java

https://jira.lib.unc.edu/browse/BXC-2712
* Only submits top level objects ingested as part of the post ingest ADD message, as each object included is recursively indexed, regardless of whether they contain each other.
* Move common method to helper class

BXC-2623 - Fix excessive indexing after ingest

---

persistence/src/main/java/edu/unc/lib/dl/persist/services/destroy/DestroyObjectsJob.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/destroy/DestroyObjectsJobIT.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/destroy/DestroyObjectsProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/AbstractLongleafProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/DeregisterLongleafProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/LongleafAggregationStrategy.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/LongleafRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/RegisterToLongleafProcessor.java
services-camel/src/main/webapp/WEB-INF/service-context.xml
services-camel/src/test/java/edu/unc/lib/dl/services/camel/destroy/DestroyObjectsRouterTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/longleaf/DeregisterLongleafRouteTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/longleaf/LongleafTestHelpers.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/longleaf/RegisterToLongleafProcessorIT.java
services-camel/src/test/resources/deregister-longleaf-router-config.properties
services-camel/src/test/resources/deregister-longleaf-router-context.xml
services-camel/src/test/resources/destroy-objects-context.xml
services-camel/src/test/resources/enhancement-router-it-context.xml

https://jira.lib.unc.edu/browse/BXC-2426
* Adds deregistration from longleaf of destroyed binaries.
* Implements bulk deregistration of binaries in longleaf
* Destroy job triggers deregistration from longleaf. Add more debug statements during destroy
* Allow longleaf message aggregator to get uri from body or header

BXC-2426 - Deregister destroyed files from longleaf

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/CDRMETS2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/DirectoryToBagJob.java
deposit/src/main/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/FixityCheckJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ValidateFileAvailabilityJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/VerifyObjectsAreInFedoraService.java
deposit/src/main/java/edu/unc/lib/deposit/validate/VirusScanJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/test/java/edu/unc/lib/deposit/CleanupDepositJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/AbstractDepositJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/AbstractFedoraDepositJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/NormalizeFileObjectsJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/FixityCheckJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ValidateContentModelJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ValidateFileAvailabilityJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/VirusScanJobTest.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/FSToFSTransferClient.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/transfer/FSToFSTransferClientTest.java

https://jira.lib.unc.edu/browse/BXC-2711
* Adds breakpoints in longer running deposit jobs, where the job checks to see if it has been paused or interrupted, and ends early if so.
* Switch binary transfer client to write using utility method which can be interrupted
* Adjustments to exception throwing, fix for virus scans, and cleanup of extraneous code

BXC-2711 - Improve deposit pausing

---

deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/main/webapp/WEB-INF/service-context.xml
deposit/src/test/java/edu/unc/lib/deposit/work/DepositSupervisorTest.java
deposit/src/test/resources/spring-test/cdr-client-container.xml
deposit/src/test/resources/spring-test/deposit-supervisor-test-context.xml
metadata/src/main/java/edu/unc/lib/dl/util/DepositPipelineStatusFactory.java
metadata/src/main/java/edu/unc/lib/dl/util/RedisWorkerConstants.java
metadata/src/test/java/edu/unc/lib/dl/util/DepositPipelineStatusFactoryIT.java
metadata/src/test/java/edu/unc/lib/dl/util/DepositStatusFactoryIT.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/DepositController.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/DepositPipelineController.java
services/src/main/webapp/WEB-INF/deposits-context.xml
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/DepositPipelineControllerIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/AbstractAPIIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/IngestControllerIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/IngestFromSourcesIT.java
services/src/test/resources/deposit-pipeline-it-servlet.xml
services/src/test/resources/ingest-it-servlet.xml
services/src/test/resources/spring-test/redis-server-context.xml
static/css/admin/cdradmin.css
static/js/admin/src/action/AjaxCallbackAction.js
static/js/admin/src/action/ChangeDepositPipelineStateAction.js
static/js/admin/src/statusMonitor/AbstractStatusMonitor.js
static/js/admin/src/statusMonitor/DepositMonitor.js
static/js/admin/statusMonitor.js
static/templates/admin/statusMonitor/overview.html

https://jira.lib.unc.edu/browse/BXC-2732
* Adds buttons to the status monitor for changing the state of the pipeline.
* Adds API endpoints for requesting these changes, and functionality in deposit pipeline to execute the changes
* Implements the following actions for Admin users:
* Quiet action - Stops processing of new deposit jobs, pauses any active jobs. Perform
* Unquiet action - Resumes processing of new deposit jobs, resumes jobs paused by quieting
* Stop action - Stops processing of new deposit jobs, interrupts any active jobs. Deposit service must be restarted to resume.
* Adds tests for some portions of the DepositSupervisor, and refactors the class to allow for more testing

BXC-2732 - Quiet/Unquiet/Stop deposit pipeline

---

deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/AbstractDepositJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/AbstractFedoraDepositJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestDepositRecordJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/DirectoryToBagJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/FixityCheckJobTest.java
deposit/src/test/resources/spring-test/cdr-client-container.xml
deposit/src/test/resources/spring-test/deposit-supervisor-test-context.xml

https://jira.lib.unc.edu/browse/BXC-2745
* Expand interruption handling to seek out interruption related root causes, so they can be rethrown as interruptions and handled correctly. 
* Add tests to trigger interruptions in deposit jobs, switch to using on disk tdb persistence for tests to more accurately reflect production

BXC-2745 - Expand interruption of deposit jobs

---

persistence/src/main/java/edu/unc/lib/dl/persist/services/importxml/ImportXMLService.java

* to avoid permissions failure caused by issues with mounted storage, which is causing startup errors.

Check that xml import dir exists before creating

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java

https://jira.lib.unc.edu/browse/BXC-2753
* Prevent setting mimetype in deposit if it matches the pattern for FITS errors
* Update transformation tests to check for mimetype setting

BXC-2753 - Prevent storage of FITS error mimetypes in transformations

---

deposit/src/main/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJob.java
deposit/src/test/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJobTest.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/persist/api/storage/BinaryDetails.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/persist/api/transfer/BinaryTransferClient.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/persist/api/transfer/BinaryTransferSession.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/persist/api/transfer/StreamTransferClient.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/storage/BinaryDetailsImpl.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/BinaryTransferSessionImpl.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/FSToFSTransferClient.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/FileSystemTransferHelpers.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/StreamToFSTransferClient.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/transfer/BinaryTransferServiceImplIT.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/transfer/FSToFSTransferClientTest.java

https://jira.lib.unc.edu/browse/BXC-2744
* Binary transfer job handles three error cases when a transfer runs into an existing file at the destination
1. The file has already been transferred, but the storage uri was lost due to an error or the jvm shutting down. In this case, no transfer occurs, and the storage uri is recorded
2. The file was partially transferred due to interruption. In this case, the file will be overwritten
3. The pid of the file overlaps with an object in the repository, and therefore they have the same file uri. In this case, the deposit fails
* Removed redis tracking of binary transfers as having the JVM terminate will result in losing storage uris recorded in jena, which would be skipped during resumption, ultimately causing IngestContentJob to fail

BXC-2744 - Improve recovery of binary transfer jobs

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/TransformContentCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerManager.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentTransformationOptions.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentTransformationService.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/TransformContentCommandIT.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java

https://jira.lib.unc.edu/browse/BXC-2765
* To support migrating units without their contents, adds a `--skip-members` option for the migrate content command which causes just the specified object to be migrated without its children
* Refactors the content transformation options into an object to pass around rather than separate setters per option, since there was getting to be a lot of them.
* Removes an unused parameter

BXC-2765 - Skip migration of members

---

fcrepo-clients/src/test/java/edu/unc/lib/dl/event/RepositoryPremisLoggerIT.java
fcrepo-clients/src/test/resources/logback-test.xml
services-camel/src/test/java/edu/unc/lib/dl/services/camel/enhancements/EnhancementRouterIT.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/longleaf/DeregisterLongleafRouteTest.java
services-camel/src/test/resources/enhancement-router-it-context.xml
services-camel/src/test/resources/logback-test.xml
services-camel/src/test/resources/spring-test/jms-context.xml

https://jira.lib.unc.edu/browse/BXC-2773
https://jira.lib.unc.edu/browse/BXC-2774
* Fixes three flapping tests
* Reduces log spam a little by tuning fedora logging to error (for frequent property namespace error) and by controlling activemq broker/camel context shutdown order for one of the tests.

BXC-2773/2774 - Fix Flapping tests

---

access/src/main/webapp/WEB-INF/service-context.xml
admin/src/main/webapp/WEB-INF/service-context.xml
persistence/src/main/java/edu/unc/lib/dl/persist/services/importxml/ImportXMLJob.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/importxml/ImportXMLJobTest.java
security/src/main/java/edu/unc/lib/dl/acl/filter/SpoofShibbolethFilter.java
security/src/main/java/edu/unc/lib/dl/acl/filter/SpoofShibbolethRequestWrapper.java
services/src/main/webapp/WEB-INF/service-context.xml

https://jira.lib.unc.edu/browse/BXC-2761
* Sets up spoofed email address header so that services can send emails when shibboleth is not being used
* Ensures that file inputstream gets closed, to avoid issues where leftover file handles linger after the xml import files are deleted
* Adds debug logging to xml import jobs

BXC-2761 - Fix XML import emails and leftover files

---

services-camel/src/main/java/edu/unc/lib/dl/services/camel/images/AddDerivativeProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/images/ImageEnhancementsRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/util/CdrFcrepoHeaders.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/images/ImageEnhancementsRouterTest.java

https://jira.lib.unc.edu/browse/BXC-2751
* Cleanup image derivatives in the case of exceptions
* Using a different uuid generator so that overlapping file names shouldnt' be possible between restarts (in case the app does not shut down gracefully)

BXC-2751 - Cleanup image derivatives in the case of exception

---

pom.xml

https://jira.lib.unc.edu/browse/BXC-2756
* This should resolve the `Resource [logback-test.xml] occurs multiple times on the classpath.` style messages being logged for every test, but only when running tests via maven or travis

BXC-2756 - Exclude logback-test.xml from test-jars

---

services-camel/src/main/java/edu/unc/lib/dl/services/camel/AddFailedRouteProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/AbstractLongleafProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/DeregisterLongleafProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/LongleafAggregationStrategy.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/LongleafRouter.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/RegisterToLongleafProcessor.java
services-camel/src/main/webapp/WEB-INF/activemq-context.xml
services-camel/src/main/webapp/WEB-INF/service-context.xml
services-camel/src/test/java/edu/unc/lib/dl/services/camel/longleaf/AbstractLongleafRouteTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/longleaf/DeregisterLongleafRouteTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/longleaf/LongleafTestHelpers.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/longleaf/RegisterLongleafRouteTest.java
services-camel/src/test/resources/deregister-longleaf-router-config.properties
services-camel/src/test/resources/enhancement-router-it-config.properties
services-camel/src/test/resources/longleaf-router-config.properties
services-camel/src/test/resources/register-longleaf-router-context.xml

https://jira.lib.unc.edu/browse/BXC-2690
* Failed longleaf batch messages will be sent to a longleaf dead letter queue
* If some files were successfully (de)registered within a batch, they are trimmed from the message before it is retried or sent to the dead letter queue
* Extends longleaf aggregation strategy to allow for incoming messages containing lists of files, as is the case when requeuing a failed deregister message
* definition of longleaf batch endpoints moved to a property rather than creating separate properties for each config option
* adjustments to activemq config, including removing a duplicate connection pool and allowing for Lists to be serialized
* Adds a test for longleaf registrations routes
To requeue failed longleaf messages that have run out of retries, at the …

BXC-2690 - Longleaf recovery

---

services-camel/src/main/webapp/WEB-INF/service-context.xml
services/src/main/webapp/WEB-INF/service-context.xml

Followup for BXC-2790 to fix null versions showing up for embargo service. Sets application version number for services and services-camel

Set cdr version for software agents in services apps

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobTest.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/test/RepositoryObjectTreeIndexer.java

https://jira.lib.unc.edu/browse/BXC-2811
* Immediately increment ingested count for file is the file is at the root of the deposit instead of in a work
* Add child ingested event to the destination objects log directly, fixing a bug which caused the event to be lost on the destination object
* Fixes unclosed object warning on premis logger
* Allow individual object models to be indexed in tests.

BXC-2811 - Ingest count for simple file deposit, fix destination log events

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/PIDs.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/PIDsTest.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/triplesReindexing/IndexingMessageProcessor.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/triplesReindexing/TriplesReindexingRouterIT.java

Handle root pid parsing as a qualified ID. Add test to verify that triples indexing can reindex the repo root

Allow for triple store indexing of repo root

---

metadata/src/main/java/edu/unc/lib/dl/util/RDFModelUtil.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/MigrationCLI.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/RecalculateDigestsCommand.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/RecalculateDigestsCommandIT.java
migration-util/src/test/resources/spring-test/recalculate-digests-command-it.xml

Used to address https://jira.lib.unc.edu/browse/BXC-2844 in already ingested objects
* Adds a commandline tool for recalculating and storing SHA1 digests of metadata files, to fix issue where digest is out of sync with the file

BXC-2844 - Tool for recalcuating metadata digests

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/RecalculateDigestsCommand.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/RecalculateDigestsCommandIT.java

https://jira.lib.unc.edu/browse/BXC-2846

BXC-2846 - Include deposit manifests in recalculation script

---

access-common/src/main/java/edu/unc/lib/dl/ui/access/StoreAccessLevelFilter.java
access-common/src/main/java/edu/unc/lib/dl/ui/controller/AbstractSolrSearchController.java
access-common/src/main/java/edu/unc/lib/dl/ui/controller/StructureResultsController.java
access-common/src/main/java/edu/unc/lib/dl/ui/service/SolrQueryLayerService.java
access/src/main/java/edu/unc/lib/dl/ui/controller/AdvancedSearchFormController.java
access/src/main/java/edu/unc/lib/dl/ui/controller/FrontPageController.java
admin/src/main/java/edu/unc/lib/dl/admin/controller/MODSController.java
admin/src/main/java/edu/unc/lib/dl/admin/controller/ResultEntryController.java
admin/src/main/java/edu/unc/lib/dl/admin/controller/VocabularyController.java
security/src/main/java/edu/unc/lib/dl/acl/util/GroupsThreadStore.java
security/src/test/java/edu/unc/lib/dl/acl/filter/StoreUserAccessControlFilterTest.java
services/src/main/java/edu/unc/lib/dl/cdr/services/processing/XMLExportService.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/SearchRestController.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/StructureQueryService.java

https://jira.lib.unc.edu/browse/BXC-2856
* Make sure that the user principal is provided for most ACL checks by using getAgentPrincipal instead of getGroups.
* Store agent principals in the group thread store rather than regenerating on each method call.
* Fix NPE when accessing structure browse in admin interface with no permissions to the content root

BXC-2856 - Fix user based permissions issues

---

deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java

https://jira.lib.unc.edu/browse/BXC-2876
* Interpret InterruptedExceptions causes as JobInterruptedExceptions, as these are thrown if an interrupt occurs while committing to tdb

BXC-2876 - Fix flapping test: DirectoryToBagJobTest.interruptionTest

---

access-common/src/main/java/edu/unc/lib/dl/ui/access/StoreAccessLevelFilter.java
access-common/src/main/java/edu/unc/lib/dl/ui/service/SolrQueryLayerService.java
access-common/src/main/java/edu/unc/lib/dl/ui/util/SerializationUtil.java
access-common/src/test/java/edu/unc/lib/dl/ui/service/StoreAccessLevelFilterTest.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/acl/PatronAccessAssignmentServiceIT.java
security/src/main/java/edu/unc/lib/dl/acl/util/AccessPrincipalConstants.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessControlFilter.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/indexing/DocumentIndexingPackage.java
static/js/admin/src/ResultObjectActionMenu.js

https://jira.lib.unc.edu/browse/BXC-2873
* Addresses issue where users that only have staff permissions on a collection can't navigate to that collection
* Fixes error that caused the structure browse not to appear in these scenarios
* Introduces an admin_access group, which is granted to users with admin access
* This group is granted non-inheriting, view only access to the collections root and all units
* Adjusts query for determining admin ui access to make it safer from user error, only check collections/units for permission grants, and to only consider staff principals.
* Hides "Export as CSV" and "View event log" actions when users don't have sufficient permission to perform them
* During solr indexing, holds a reference to the ContentObject with the DocumentIndexingPackage so it …

BXC-2873 - Allow visibility of root and unit objects for all admin users

---

deposit/pom.xml
metadata/pom.xml
pom.xml
services/pom.xml

Related to https://jira.lib.unc.edu/browse/BXC-2888.
Jesque 2.x is not compatible with Jedis 3, so only a minor upgrade

Minor jedis and embedded redis updates

---

deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java

Skip adding size property during migration, check some other values for nulls before adding to model. Add more details to exceptions thrown while pulling original binary list

Prevent migration failure when property is not set

---

deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
migration-util/pom.xml
migration-util/src/main/java/edu/unc/lib/dcr/migration/CleanupDepositsCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/MigrationCLI.java
migration-util/src/main/resources/spring/cleanup-deposits-context.xml
migration-util/src/test/java/edu/unc/lib/dcr/migration/CleanupDepositsCommandIT.java
migration-util/src/test/resources/spring-test/jedis-context.xml
persistence/src/main/java/edu/unc/lib/dl/persist/services/deposit/DepositDirectoryManager.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/deposit/DepositModelManager.java

https://jira.lib.unc.edu/browse/BXC-2938
Adds a command for cleaning up one or more deposits. This includes removing the deposit directory, redis data, and jena TDB data. This command has no affect on objects already ingested into the repository, and is intended for use in cleaning up failed deposits.
This is very similar, but not quite the same as CleanupDepositJob, which also cleans up staged files.

BXC-2938 - Command for cleaning up deposits

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectCacheLoader.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/images/AddDerivativeProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/solr/SolrIngestProcessor.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/images/AddDerivativeProcessorTest.java
services-camel/src/test/resources/convert/ignore_tag_stderr.txt

https://jira.lib.unc.edu/browse/BXC-2947
https://jira.lib.unc.edu/browse/BXC-2948
* Prevent running out of fedora connections by avoiding opening a connection inside of a connection
* Ignore some errors from imagemagick which don't appear to impact the derivative created

BXC-2947/2948 - Fedora connection and imagemagick error fixes

---

services-camel/src/main/resources/solr.properties
services/src/main/java/edu/unc/lib/dl/cdr/services/processing/RunEnhancementsService.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/AbstractQueryService.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/NeighborQueryService.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/SolrSearchService.java

https://jira.lib.unc.edu/browse/BXC-2968
* Add a default set of solr result fields when none is provided, to avoid returning OOM issues caused by returning fields intended for searching.
* Set list of result fields for run enhancements query

BXC-2968 - Avoid returning full text field in queries

---

deposit/src/main/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJob.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJobTest.java
deposit/src/test/resources/fitsReports/textReport.xml
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactory.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/util/MimetypeHelpers.java

https://jira.lib.unc.edu/browse/BXC-2970
* Override provided mimetype in a deposit with FITS mimetype if the latter is more meaningful. 
* Ranks mimetypes, with text/plain ranked lower than most other mimetypes
* Adds utility class for mimetypes

BXC-2970 - Override provided mimetype in a deposit

---

deposit/src/main/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJob.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJobTest.java

https://jira.lib.unc.edu/browse/BXC-2974
* Favor the FITS generated mimetype over the provided mimetype in case they are of equivalent rank

BXC-2974 - Favor the FITS generated mimetype over the provided mimetype 

---

deposit/src/main/java/edu/unc/lib/deposit/validate/FixityCheckJob.java
deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml
deposit/src/test/java/edu/unc/lib/deposit/validate/FixityCheckJobTest.java

https://jira.lib.unc.edu/browse/BXC-2959
* Refactors FixityCheckJob to run fixity check jobs in parallel
* Each fixity check job runs in a separate worker thread using a pool thread
* Updates to the deposit model and PREMIS logs are flushed ever ~2 seconds to reduce the number of transactions against jena TDB
* Fixity check jobs are gradually submitted to the queue for execution in order to prevent one deposit from taking over all the workers for a long time, which would delay the other deposits.
* Has its own thread pool for the moment since VirusScanJob is not currently setup to play nice with other jobs in terms of number of tasks queued at once.

BXC-2959 - Refactor fixity check job to run checks in parallel

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/FedoraTransaction.java

* Fixes issue where we were not receiving the actual error causing deposits to fail. Also, this is the intent of the method.

Swallow tx errors in FedoraTransaction.cancelAndIgnore

---

deposit/src/main/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml
deposit/src/test/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJobTest.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/deposit/DepositModelManager.java

https://jira.lib.unc.edu/browse/BXC-2961
* Refactors binary transfers job to perform transfers in parallel to each, following a similar setup to https://github.com/UNC-Libraries/Carolina-Digital-Repository/pull/1164
* All transfers per object happen in the same runnable executed in a thread pool
* Updates to the deposit model every few seconds to reduce the number of write transactions against jena TDB
* jobs are gradually submitted to the queue for execution in order to prevent one deposit from taking over all the workers for a long time, which would delay the other deposits.
* Due to needing to read from the jena tdb model in multiple threads, a read transaction must be opened in each transfer worker.
* Refactored job to process objects needing transfers based off a single query of the …

BXC-2961 - Parallel Binary Transfers

---

deposit/src/main/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/FixityCheckJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/VirusScanJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/AbstractConcurrentDepositJob.java
deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml
deposit/src/test/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJobTest.java

https://jira.lib.unc.edu/browse/BXC-2960
* Performs FITS runs in parallel during deposits, in the same fashion as https://github.com/UNC-Libraries/Carolina-Digital-Repository/pull/1174 and https://github.com/UNC-Libraries/Carolina-Digital-Repository/pull/1164
* Refactors the common concurrent task behaviors for these deposit jobs into a parent class
* Updates the VirusScanJob to also use this parent class, although it does not use the flushing aspect of it.
* Combines executorServices for VirusScanJob and FixityCheckJob now that virus scan job plays nice

BXC-2960 - Parallel FITS runs

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryInitializer.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/routing/FedoraIdFilters.java

Allow content root object to be indexed, prevent processing of fedora:timemap uris, add logging for initializer

Fix filtering/indexing issues with content root object and fedora:timemap

---

.gitmodules
Makefile
access/pom.xml
checkstyle-suppressions.xml
deposit/pom.xml
fcrepo-clients/pom.xml
migration-util/pom.xml
persistence/pom.xml
pom.xml
services-camel/pom.xml
services-camel/src/test/java/edu/unc/lib/dl/services/camel/triplesReindexing/TriplesReindexingRouterIT.java
services/pom.xml

Updates from jena 3.9.0 to 3.17.0 in order to help with data corruption issue with jena tdb.
* In order to do this, adds fcrepo 5.2.0-SNAPSHOT as a submodule temporarily to make sure it is present during builds and tests. Should remove once a new fcrepo release is published.
* Adds make tasks to just build bxc projects (since building fcrepo triples the build/test time): `make build-bxc` and `make verify-bxc`
* Updates other dependencies that changed with the fcrepo update

Update jena version and fcrepo

---

metadata/src/main/java/edu/unc/lib/dl/util/AbstractJedisFactory.java
metadata/src/main/java/edu/unc/lib/dl/util/DepositStatusFactory.java
metadata/src/main/java/edu/unc/lib/dl/util/JobStatusFactory.java
metadata/src/test/java/edu/unc/lib/dl/util/JobStatusFactoryTest.java

https://jira.lib.unc.edu/browse/BXC-2995
Should attempt to retry redis operations when a socket timeout occurs, which is the primary jedis related cause of deposit failures.

BXC-2995 - Redis connection retries

---

deposit/src/main/java/edu/unc/lib/deposit/work/AbstractConcurrentDepositJob.java
deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml
deposit/src/main/webapp/WEB-INF/service-context.xml
deposit/src/test/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJobTest.java

Fixes two concurrency issues in the deposit pipeline:
* allows for more connections to FITS webapp, which was preventing more than 2 connections to it at a time
* calls `get` on futures when clearing them from queue of jobs so that any exceptions thrown by worker threads will be rethrown during `waitForQueueCapacity`

Concurrency fixes

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/MigrationCLI.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/SendMessageCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/SendSolrMessageCommand.java
migration-util/src/main/resources/spring/send-solr-message-context.xml
services-camel/src/main/java/edu/unc/lib/dl/services/camel/solrUpdate/SolrUpdatePreprocessor.java

https://jira.lib.unc.edu/browse/BXC-2972
* Adds a CLI for producing solr indexing messages from lists of object ids. Allows for all supported indexing actions to be submitted
* Allows the UPDATE_FULL_TEXT solr action to be specified again.
* Adds flag to fedora message sending command to allow it to keep going even if it encounters IDs that don't exist

BXC-2972 - Send indexing messages for lists of items

---

metadata/src/main/java/edu/unc/lib/dl/util/IndexingActionType.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/DestroyObjectsCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/MigrationCLI.java
migration-util/src/main/resources/spring/destroy-objects-context.xml
migration-util/src/main/resources/spring/send-message-context.xml
migration-util/src/main/resources/spring/send-solr-message-context.xml
persistence/src/main/java/edu/unc/lib/dl/persist/services/destroy/AbstractDestroyObjectsJob.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/destroy/DestroyObjectsCompletelyJob.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/destroy/DestroyObjectsHelper.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/destroy/DestroyObjectsJob.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/destroy/DestroyObjectsRequest.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/destroy/DestroyObjectsService.java
persistence/src/main/java/edu/unc/lib/dl/services/DestroyObjectsMessageHelpers.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/destroy/DestroyObjectsCompletelyJobIT.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/destroy/DestroyObjectsJobIT.java
persistence/src/test/resources/spring-test/destroy-completely-it-context.xml
services-camel/src/main/java/edu/unc/lib/dl/services/camel/destroy/DestroyObjectsProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/destroyDerivatives/DestroyedMsgProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/GetUrisProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/routing/MetaServicesRouter.java

https://jira.lib.unc.edu/browse/BXC-3024
* Adds Destroy Completely job, which completely removes objects from the repository, without leaving behind metadata or a tombstone
* Adds commandline interface for destroying objects
* An option may be provided to completely destroy the objects
* Adds more restrictions on what objects can be targeted by destroy operations
* Allows destroy messages to list more than one binary
* Attempts to suppress some of the log spam from the triple store indexing service caused by objects being destroyed, although there is still some from within the triple store indexing service itself.
* Removes an unused solr indexing delete action

BXC-3024 - Action/utility to completely remove objects

---

services-camel/src/main/java/edu/unc/lib/dl/services/camel/images/AddDerivativeProcessor.java

Catch file exists exceptions. It's possible in some circumstances for "notExists" to report a file doesn't exist when it actually does, such as when the file is locked by another process.
https://jira.lib.unc.edu/browse/BXC-3036

Derivative regeneration without the force flag

---

access-common/src/main/java/edu/unc/lib/dl/ui/service/FindingAidUrlService.java
access-common/src/test/java/edu/unc/lib/dl/ui/service/FindingAidUrlServiceTest.java
access/src/main/java/edu/unc/lib/dl/ui/controller/FullRecordController.java
access/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/collectionRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/fileRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/folderRecord.jsp
access/src/main/webapp/WEB-INF/service-context.xml
access/src/main/webapp/WEB-INF/solr-search-context.xml
fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/ContentPathFactory.java
metadata/src/main/java/edu/unc/lib/dl/util/ContentPathConstants.java
services-camel/src/test/resources/config/access/conf/schema.xml
services/src/test/resources/config/access/conf/schema.xml
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetCollectionSupplementalInformationFilter.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetDescriptiveMetadataFilter.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetPathFilter.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetDescriptiveMetadataFilterTest.java
solr-ingest/src/test/resources/config/access/conf/schema.xml
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/GetCollectionIdService.java
solr-search/src/test/java/edu/unc/lib/dl/search/solr/service/GetCollectionIdServiceIT.java
solr-search/src/test/java/edu/unc/lib/dl/search/solr/test/TestCorpus.java
solr-search/src/test/resources/logback-test.xml

https://jira.lib.unc.edu/browse/BXC-3015
* Collection numbers are looked up via solr from any ancestor (except the unit or root)
* Finding aid URLs are constructed from the collection number
* Checks to make sure the finding aid is available before returning link
* Outcome for whether the finding aid exists will be cached for some time, per collection number
* "-z" suffixes are trimmed off of collection numbers for the finding aid URL, but retained for displaying the collection number
* Finding aid url no longer indexed
* Moves constants for where object types appear in terms of hierarchy depth to their own class

BXC-3015 - Inherit collection numbers and finding aid URLs

---

.github/workflows/build.yml
deposit/src/main/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/FixityCheckJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/AbstractConcurrentDepositJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/JobPausedException.java
deposit/src/test/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/FixityCheckJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/VirusScanJobTest.java

https://jira.lib.unc.edu/browse/BXC-3033
https://jira.lib.unc.edu/browse/BXC-3045
* Adds helper method to await the registrar thread finishing, which is called by concurrent deposit jobs before exiting the run method whether or not the job was interrupted. This means that the registrar flushing thread will be done before tests continue on to do a second run.
* Deposit interruptions due to pausing quit more gently, so that the changes to the deposit model are more likely to get saved, to prevent duplicate work
* Registrar thread will attempt to flush one last time in the case of interruption
* Adds some missing resets and job reinitializations which could cause counts to sometimes be off
* Addresses bonus TransferBinariesToStorageJobTest.depositLotsOfFiles flapping test

WIP: BXC-3033/3045 - Flapping Deposit tests

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ACLTransformationHelpers.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ACLTransformationHelpersTest.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java

https://jira.lib.unc.edu/browse/BXC-2874
https://jira.lib.unc.edu/browse/BXC-2934
* Removes Content migration functionality which copied ACLs from units to their children collections, since the migration is complete and this never ended up being used anyways. This was causing tests to flap because the unit and collection could be processed concurrently, so the unit info was not available for the collection transformation.
* Removes migration code which transformed staff roles, since this was not used either

BXC-2874/2934 - Flapping ContentObjectTransformerTest

---

services-camel/src/test/java/edu/unc/lib/dl/services/camel/solrUpdate/SolrUpdateProcessorIT.java
services-camel/src/test/resources/datastreams/modsWithRla.xml
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetCollectionSupplementalInformationFilter.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/collection/RLASupplementalFilter.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/indexing/SolrUpdateDriver.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/BriefObjectMetadata.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/GroupedMetadataBean.java

https://jira.lib.unc.edu/browse/BXC-3065
* Index dynamic fields during update operations, is provided.
* Collection indexing filter applies to collection objects now too, not just their children
* Exposed identifierSort field via BriefObjectMetadata interface.
* Add tests of collection/rla indexing workflow

BXC-3065 - Collection filter indexing and dynamic field fixes

---

access-common/src/main/java/edu/unc/lib/dl/ui/controller/structure/StructureResultsController.java
admin/src/main/webapp/WEB-INF/service-context.xml
admin/src/main/webapp/WEB-INF/uiapp-servlet.xml

Move structure browse into its own package, only include it in the admin ui since the other controllers are not used. Remove loris beans from admin

Remove Loris from Admin UI

---

services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/DeregisterLongleafProcessor.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/longleaf/AbstractLongleafRouteTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/longleaf/DeregisterLongleafRouteTest.java

https://jira.lib.unc.edu/browse/BXC-3069
* Converts content URIs of binaries being destroyed into base form before submission to longleaf, as longleaf requires the logical path of the file.
* During deregistration, filters out content URIs which are not file paths. There have been instances in the past where PIDs were being supplied as content URIs, causing deregistration to fail.

BXC-3069 - Deregistration content URI patterns

---

metadata/src/main/java/edu/unc/lib/dl/util/DescriptionConstants.java
services/src/main/java/edu/unc/lib/dl/cdr/services/processing/AddContainerService.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/AddContainerController.java
services/src/main/webapp/WEB-INF/service-context.xml
services/src/test/java/edu/unc/lib/dl/cdr/services/processing/AddContainerServiceTest.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/AddContainerIT.java
services/src/test/resources/add-container-it-servlet.xml
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetDescriptiveMetadataFilter.java
static/js/admin/src/CreateContainerForm.js
static/templates/admin/createContainerForm.html

https://jira.lib.unc.edu/browse/BXC-3043
* In the Add Container workflow, the label field is now added to a mods:titleInfo/mods:title field in addition to the dc:title rdf field
* When creating a collection, the user may optionally add a Collection Number field.
* Refactored AddContainerService and controller to take a AddContainerRequest object, since the number of parameters was getting excessive.

BXC-3043 - MODS Title and Collection Number in Add Container

---

services/src/main/java/edu/unc/lib/dl/cdr/services/processing/ExportCsvService.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/ExportCsvController.java
services/src/main/webapp/WEB-INF/service-context.xml
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/ExportCsvIT.java
services/src/test/resources/export-csv-it-servlet.xml
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/ChildrenCountService.java
static/js/admin/src/ResultObjectActionMenu.js

https://jira.lib.unc.edu/browse/BXC-2997
* Break CSV export query result into pages, streaming results page by page.
* Split CSV export into a separate service class.
* Reenabled CSV export for all collection sizes

BXC-2997 - CSV Export of large sets

---

access-common/src/main/java/edu/unc/lib/dl/ui/util/DatastreamUtil.java
access-common/src/main/resources/META-INF/cdrUI.tld
access/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/fileRecord.jsp
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetContentTypeFilter.java
solr-ingest/src/main/resources/edu/unc/lib/dl/data/ingest/solr/filter/toContentType.properties
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetContentTypeFilterTest.java

https://jira.lib.unc.edu/browse/BXC-3096
* Checks mimetype to determine if pdf and mp3 viewers should be shown
* contentType field now indexes appledouble files as "unknown" category rather than the type of the actual file the sidecar file is describing
* Fixes bug where mimetype to content type category mapping was being overridden by extension to category mapping.
* Tidies up code and removes duplication

BXC-3096 - Skip viewers for Appledouble files

---

pom.xml

https://jira.lib.unc.edu/browse/BXC-3109
* Update fcrepo-java-client to 5.0.0 to pull in fix for encoding of spaces in filenames

BXC-3109 - Filename space encoding

---

deposit/src/main/java/edu/unc/lib/deposit/normalize/AbstractFileServerToBagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/DirectoryToBagJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/VirusScanJob.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/DirectoryToBagJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/VirusScanJobTest.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/FSToFSTransferClient.java

https://jira.lib.unc.edu/browse/BXC-3143
* File server deposits (Directory and Bagit) should now succeed when containing files or folders that have unicode characters in their filenames
* Switches to using NIO during deposit jobs and file transfers, as the older java.io utilities are not reliable with their encoding when listing file names
* During fits extract, use a symlink pointing to the file if its path contains any unicode characters, as the FITS webapp cannot access these files
* During virus scanning, scan by streaming content instead of by file path if the path contains any unicode, as clamd does not appear to work with these paths (regular clamscan does, clamdscan gives an unspecified error)

BXC-3143 - Unicode filenames in file server deposits

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/acl/fcrepo4/InheritedAclFactory.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObject.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectDriver.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/Tombstone.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/test/AclModelBuilder.java
security/src/main/java/edu/unc/lib/dl/acl/util/AccessPrincipalConstants.java
security/src/main/java/edu/unc/lib/dl/acl/util/UserRole.java
solr-ingest/pom.xml
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessStatusFilter.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessStatusFilterTest.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/util/FacetConstants.java
static/js/admin/src/ResultObject.js

https://jira.lib.unc.edu/browse/BXC-3148
* Add tag and access status facet for objects which inherit patron access restrictions.
* Reworked access status filter to use real acl factories, as the mocked outcomes of some tests were not possible. 
* Move patron role precedence constant to location where it can be referenced more broadly, add more constants.

BXC-3148 - Inherited patron restrictions tag

---

solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/MultiSelectFacetListService.java
solr-search/src/test/java/edu/unc/lib/dl/search/solr/service/MultiSelectFacetListServiceIT.java
solr-search/src/test/java/edu/unc/lib/dl/search/solr/test/TestCorpus.java

https://jira.lib.unc.edu/browse/BXC-3180
* Exclude file objects from facet counts to bring facet and search result counts closer to being in line.
* Test corpus indexing content type of child files onto works

BXC-3180 - Exclude file objects from facet counts

---

deposit/src/main/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJob.java
deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml
deposit/src/test/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJobTest.java

https://jira.lib.unc.edu/browse/BXC-3206
* Add executor service to limit the number of files the BagVerifier checks for at once, to prevent it from opening thousands of file handles simultaneously

BXC-3206 - Bag Deposit too many file handles

---

persistence/src/main/java/edu/unc/lib/dl/persist/services/importxml/ImportXMLJob.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/importxml/ImportXMLJobIT.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/importxml/ImportXMLJobTest.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/importxml/ImportXMLProcessor.java
services-camel/src/main/webapp/WEB-INF/service-context.xml

https://jira.lib.unc.edu/browse/BXC-3201
* Separate admin email from reply email address for MODS imports, send MODS import emails to admin instead of reply email
* Improve error handling and consistency of messages

BXC-3201 - Send MODS import emails to admin users

---

auth-api/src/main/java/edu/unc/lib/boxc/auth/api/services/DatastreamPermissionUtil.java
deposit-utils/src/main/java/edu/unc/lib/boxc/deposit/impl/model/DepositDirectoryManager.java
deposit-utils/src/main/java/edu/unc/lib/boxc/deposit/impl/model/DepositModelHelpers.java
model-api/src/main/java/edu/unc/lib/boxc/model/api/DatastreamType.java
model-api/src/main/java/edu/unc/lib/boxc/model/api/rdf/CdrDeposit.java
model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/ids/DatastreamPids.java

This is a part of https://jira.lib.unc.edu/browse/BXC-3176 and needs to be merged before https://github.com/UNC-Libraries/cdm-to-boxc-migration-util/pull/6
* Add properties related to access copy datastreams.
* Expose method for getting path to mods file in deposit dir

BXC-3176 - Updates to support migration SIP generation

---

deposit/src/main/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJob.java
deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml
deposit/src/test/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJobTest.java

https://jira.lib.unc.edu/browse/BXC-3216
* FITS extract to be performed using commandline utility instead of webservice under certain conditions, currently based on characters in file path and size of the file

BXC-3216 - Conditionally run FITS CLI

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJob.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJobTest.java

https://jira.lib.unc.edu/browse/BXC-3240
* To avoid FITS web service crashing when processing certain .mov files in paralell, use FITS CLI for files based on extension, at the moment only .mov. Add name of file that failed fits processing to error message

BXC-3240 - Use FITS CLI for files based on extension

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/work/DepositFailedException.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/work/DepositSupervisor.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/work/DepositSupervisorTest.java

https://jira.lib.unc.edu/browse/BXC-3248
* Add check to verify that all of the listed successful jobs are valid jobs, to force regeneration or modification of deposit jobs in the case of classes being renamed so that jobs don't get run multiple times.
* Make DepositFailedException into a RuntimeException rather than a Throwable so it can be handled more normally.

BXC-3248 - Add check to verify that all of the listed successful jobs are valid

---

operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/exportxml/ExportXMLRequest.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/AbstractQueryService.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/SolrSearchService.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/exportxml/ExportXMLProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/exportxml/ExportXMLRouteIT.java
static/js/admin/src/action/ExportMetadataXMLBatchAction.js
static/templates/admin/exportMetadataForm.html

https://jira.lib.unc.edu/browse/BXC-3255
* Adds an option for excluding objects without mods from XML export
* Adds an email template for when no objects are being exported due to all pids being filtered out
* Exposes some protected methods as public which are useful for constructing and executing custom queries

BXC-3255 - Add option for excluding objects without mods from export

---

auth-api/src/main/java/edu/unc/lib/boxc/auth/api/services/DatastreamPermissionUtil.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/transfer/TransferBinariesToStorageJob.java
deposit-app/src/main/webapp/WEB-INF/deposit-jobs-context.xml
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/transfer/TransferBinariesToStorageJobTest.java
deposit-utils/src/main/java/edu/unc/lib/boxc/deposit/impl/model/DepositModelHelpers.java
model-api/src/main/java/edu/unc/lib/boxc/model/api/DatastreamType.java
model-api/src/main/java/edu/unc/lib/boxc/model/api/rdf/CdrDeposit.java
model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/ids/DatastreamPids.java
model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/services/DerivativeService.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/BinaryMetadataProcessor.java
services-camel-app/src/main/webapp/WEB-INF/service-context.xml
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/BinaryMetadataProcessorTest.java
services-camel-app/src/test/resources/enhancement-router-it-context.xml
services-camel-app/src/test/resources/spring-test/cdr-client-container.xml
services-camel-app/src/test/resources/spring-test/solr-indexing-context.xml

https://jira.lib.unc.edu/browse/BXC-3203
* Access surrogates provided to deposit pipeline will be copied to derivatives directory
* BinaryMetadataProcessor will use the path and mimetype of the access surrogate if one is detected
* Since there is nowhere to store it, the mimetype of the access surrogate is determined using tika
* Renames access_copy to  access_surrogate in most places for clarity/consistency
* access_surrogate datastream is implicitly indexed to solr, along with all other external datastreams.

BXC-3203 - Access surrogates support

---

model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/ids/DatastreamPids.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/exportxml/BulkXMLConstants.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/exportxml/ExportXMLRequest.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/importxml/ImportXMLJob.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/importxml/ImportXMLJobIT.java
operations/src/test/java/edu/unc/lib/boxc/operations/test/ModsTestHelper.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/exportxml/ExportXMLProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/exportxml/ExportXMLRouteIT.java
static/js/admin/src/ResultObjectActionMenu.js
static/js/admin/src/ResultView.js
static/js/admin/src/action/ExportMetadataXMLBatchAction.js
static/templates/admin/exportMetadataForm.html
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/ExportXMLIT.java

https://jira.lib.unc.edu/browse/BXC-3256
* Allows for FITS, FITS History, MODS History, and PREMIS Event Logs to be included in the XML export
* Renames the `object/update` tag to `object/datastream`, with an optional `operation="update"` attribute
* Refactored out constants for xml import and export operations
* Updates to DatastreamPids helper methods
* Renamed "Export MODS" to "Export Metadata". Still named "Import MODS" since that is the only importable datastream at present.

BXC-3256 - Additional Metadata Types in XML Export

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJob.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJobTest.java

https://jira.lib.unc.edu/browse/BXC-3314
* Skip wrapping file path in quotes when running FITS CLI since the FITS script also causes all arguments to be wrapped in quotes, resulting it being double wrapped and therefore not wrapped. 
* Minor refactoring of CLI executing code to improve reporting

BXC-3314 - FITS failure for .mov file in path containing parentheses

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJob.java

https://jira.lib.unc.edu/browse/BXC-3369
* Using array for passing params to FITS CLI. For paths with unicode, use a symlink

BXC-3369 - FITS file path issues

---

static/css/cdrui_styles.css
static/css/sass/cdr_ui_styles.scss

https://jira.lib.unc.edu/browse/BXC-3377
* Set height of UV to 90% of window. 
* Remove unneeded rules, merge together jp2_imageviewer_window rules which were in different files

BXC-3377 - I wish boxy was a little bit taller

---

operations/src/main/java/edu/unc/lib/boxc/operations/impl/edit/UpdateDescriptionService.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/importxml/ImportXMLJob.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/versioning/VersionedDatastreamService.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/importxml/ImportXMLJobIT.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/exportxml/ExportXMLProcessor.java

https://jira.lib.unc.edu/browse/BXC-3295
* Implements support for optimistic locking for bulk MODS imports
* This means that if a "lastModified" timestamp is present for a datastream in the import document and the timestamp listed is older than the timestamp of the MODS datastream in fedora, then the update will be rejected. See an example document below which contains the lastModified attributes
* To support this, the EditDescription and VersionedDatastreamService were updated to support optimistic locking
* XML Exports now return the lastModified attribute in ISO8601 format (previously it was using default java Date format)
* Some refactoring of import document parsing, since all the additions to the original structure were getting unweildy
* Some fixes to tests which had hardcoded …

BXC-3295 - Optimistic locking for bulk metadata imports

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/SearchStateFactory.java
web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/AdvancedSearchFormController.java
web-access-app/src/main/webapp/WEB-INF/jsp/advancedSearch.jsp

* Fix bug with advanced search collection filter not working by adding parent collection filter via the standard 'collection' parameter rather than giving it special URL construction behaviors
* the issue was that the advanced search controller constructs a SearchState which gets passed to the regular search controller via the session, meanwhile the "collection" parameter was only being added to the URL which the advanced search forwards to. So when the regular search controller executes, it sees that a SearchState is already present and uses that rather than parsing the current URL, but the "collection" parameter is only in the URL and not the SearchState.

BXC-3392 - Fix bug with advanced search collection filter not working

---

indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/exception/RecoverableIndexingException.java
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/indexing/SolrUpdateDriver.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/solr/SolrRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateRouter.java
services-camel-app/src/main/webapp/WEB-INF/solr-indexing-context.xml

https://jira.lib.unc.edu/browse/BXC-3153
https://jira.lib.unc.edu/browse/BXC-3166
* Adjust error handling during solr indexing so that a smaller subset of potentially recoverable exceptions will get retried. 
* Unexpected or known unrecoverable exceptions would fail after the first try.
* Separate delay config for obj not found vs other recoverable errors
* Adds a RecoverableIndexingException to help differentiate

BXC-3153/3166 - Handling of indexing exceptions

---

.github/workflows/build.yml
deposit-app/pom.xml
fcrepo-utils/pom.xml
integration/pom.xml
operations/pom.xml
persistence/pom.xml
pom.xml
services-camel-app/pom.xml
web-access-app/pom.xml
web-admin-app/pom.xml
web-common/pom.xml
web-services-app/pom.xml
web-sword/pom.xml

https://jira.lib.unc.edu/browse/BXC-3313
* Updates compiler version to java 11
* Servlet version updated to 4
* Explicitly added jaxb dependencies, which are no longer built into java. Retaining older version of jaxb in a test scope for integration tests that involve fedora.

BXC-3313 - Java 11

---

web-common/src/main/java/edu/unc/lib/boxc/web/common/services/FindingAidUrlService.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/services/FindingAidUrlServiceTest.java

https://jira.lib.unc.edu/browse/BXC-3426
* Encode collection id in finding aid urls. 
* Add check to ensure that base url set

BXC-3426 - Prevent full record page error when illegal characters in collection id

---

indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentTypeFilter.java
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/indexing/DocumentIndexingPackage.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentTypeFilterTest.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetDatastreamFilterTest.java
integration/src/test/resources/spring-test/solr-indexing-context.xml
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/indexing/IndexingActionType.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/ContentObjectSolrRecord.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/solr/SolrIngestProcessor.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/solrUpdate/AggregateUpdateProcessor.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdatePreprocessor.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateProcessor.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/util/OrderedSetAggregationStrategy.java
services-camel-app/src/main/webapp/WEB-INF/solr-indexing-context.xml
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solr/SolrIngestProcessorIT.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solr/SolrIngestProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateProcessorIT.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateRouterTest.java
services-camel-app/src/test/resources/cdr-event-routing-it-config.properties
services-camel-app/src/test/resources/cdr-event-routing-it-context.xml
services-camel-app/src/test/resources/solr-indexing-it-context.xml
services-camel-app/src/test/resources/solr-update-config.properties
services-camel-app/src/test/resources/solr-update-context.xml
services-camel-app/src/test/resources/solr-update-processor-it-context.xml
services-camel-app/src/test/resources/spring-test/solr-indexing-context.xml
web-services-app/src/test/resources/spring-test/solr-indexing-context.xml

https://jira.lib.unc.edu/browse/BXC-3205
* Work object contentType field populated with contentType of all children file objects.
* Children contentType info is retrieved from solr records for the files (which should be more performant than using fedora or the triple store for large works)
* This approach should set us up for other similar aggregate info being added to works
* Refactored triggering indexing of works based on files:
* Now both ingest and a few update operations will trigger a partial reindex of the work. 
* The work indexing operations now go through a separate queue which gets deduplicated to reduce redundant indexing. 
* Previously the work was fully reindexed, and would be reindexed for every file added.
* Adds an "UPDATE_WORK_FILES" indexing operation, which performs …

BXC-3205 - Index contentType of all children files onto work

---

indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetDatastreamFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetDatastreamFilterTest.java
indexing-solr/src/test/resources/datastream/techmdImageNoDimensions.xml

https://jira.lib.unc.edu/browse/BXC-3451
This will resolve issues where the datastream extent field gets set to `nullxnull` for images when no height or width field is present in the FITS image tag, for objects that have already been ingested.
* Prevent setting of extent subfield for datastreams if width or height is missing from FITS, or not numbers

BXC-3451 - Fix indexing of extent for images without dimension data

---

deposit-app/src/main/webapp/WEB-INF/service-context.xml
model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/sparql/FusekiSparqlQueryServiceImpl.java
pom.xml
services-camel-app/pom.xml
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/util/OrderedSetAggregationStrategy.java
services-camel-app/src/main/webapp/WEB-INF/service-context.xml
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/triplesReindexing/TriplesReindexingRouterIT.java
services-camel-app/src/test/resources/triples-reindexing-it-context.xml
web-access-app/src/main/webapp/WEB-INF/access-fedora-context.xml
web-admin-app/src/main/webapp/WEB-INF/access-fedora-context.xml
web-services-app/src/main/webapp/WEB-INF/access-fedora-context.xml

* Update jena to 4.4.0 to address security issue and use java 11 version. Adjustments to address changes in api.

BXC-3449 - Update to jena 4.4.0

---

web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/SearchActionController.java

Don't exclude file objects when performing a list query and rollup is turned off, otherwise can't list children in works. This was a side effect of https://github.com/UNC-Libraries/box-c/pull/1334

Fix bug preventing file list from populating

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/config/SearchSettings.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/SearchStateFactory.java
web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/SearchActionController.java

Prevent all collections from SearchSettings from being modifiable, and initialize resourceType lists in search states from new ArrayLists so they can be safely modified. Addresses bug where a blank advanced search would cause the File object type to be removed from default resource types list

Fix File resource type removal

---

model-api/src/main/java/edu/unc/lib/boxc/model/api/services/ContentPathFactory.java
model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/services/ContentPathFactoryImpl.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/util/CacheInvalidatingProcessor.java
services-camel-app/src/main/webapp/WEB-INF/service-context.xml
services-camel-app/src/main/webapp/WEB-INF/solr-indexing-context.xml
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/util/CacheInvalidatingProcessorTest.java
services-camel-app/src/test/resources/solr-update-processor-it-context.xml

https://jira.lib.unc.edu/browse/LIB-16359
* Add status updating filter to move operation indexing, since inherited statuses were not clearing when moving out of a folder with permissions restrictions
* Invalidate path cache when an object is modified, to prevent stale value from preventing the path from updating in solr from a move operation if the same object had recently been indexed

LIB-16359 - Resolve issues with refreshing solr after move operations

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/MultiSelectFacetListService.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/NeighborQueryService.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/SolrSearchService.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/utils/FacetFieldUtil.java
search-solr/src/test/java/edu/unc/lib/boxc/search/solr/services/MultiSelectFacetListServiceIT.java
search-solr/src/test/java/edu/unc/lib/boxc/search/solr/test/TestCorpus.java
search-solr/src/test/java/edu/unc/lib/boxc/search/solr/utils/FacetFieldUtilTest.java
static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json
static/js/vue-cdr-access/src/components/browseSearch.vue
static/js/vue-cdr-access/src/components/clearFacetsButton.vue
static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/src/components/facets.vue
static/js/vue-cdr-access/src/components/filterTags.vue
static/js/vue-cdr-access/src/components/pagination.vue
static/js/vue-cdr-access/src/components/searchWrapper.vue
static/js/vue-cdr-access/src/components/worksOnly.vue
static/js/vue-cdr-access/src/main.js
static/js/vue-cdr-access/src/mixins/routeUtils.js
static/js/vue-cdr-access/src/store.js
static/js/vue-cdr-access/tests/unit/browseSearch.spec.js
static/js/vue-cdr-access/tests/unit/browseSort.spec.js
static/js/vue-cdr-access/tests/unit/displayWrapper.spec.js
static/js/vue-cdr-access/tests/unit/facets.spec.js
static/js/vue-cdr-access/tests/unit/filterTags.spec.js
static/js/vue-cdr-access/tests/unit/pagination.spec.js
static/js/vue-cdr-access/tests/unit/routeUtils.spec.js
static/js/vue-cdr-access/tests/unit/viewType.spec.js
static/js/vue-cdr-access/tests/unit/worksOnly.spec.js

https://jira.lib.unc.edu/browse/BXC-3563
Also addresses https://jira.lib.unc.edu/browse/BXC-3610
* Facet results in listJson requests now include all children
* Required fixing an issue applyCutoffs parameter, which was not being honored for the ancestorPath facet when constructing solr queries (it is the only CutoffFacet), and was incorrectly being used to prevent other facet behaviors (most likely code had moved around at some point and the conditional not been updated)
* Applying facet restrictions now switches from listJson to searchJson, just like search terms
* "Show works only" button now shown on admin unit pages
* Suppress Admin Unit facet on all full record pages, suppress Collection facet on collection and folder pages
* Required switching possible_facet_fields over to vuex so …

BXC-3563 - Revisions to full record page faceting

---

indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentTypeFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentTypeFilterTest.java
integration/src/test/resources/spring-test/solr-indexing-context.xml
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/facets/CutoffFacetImpl.java
services-camel-app/src/main/webapp/WEB-INF/solr-indexing-context.xml
services-camel-app/src/test/resources/cdr-event-routing-it-context.xml
services-camel-app/src/test/resources/solr-update-context.xml
services-camel-app/src/test/resources/solr-update-processor-it-context.xml
services-camel-app/src/test/resources/spring-test/solr-indexing-context.xml
web-services-app/src/test/resources/spring-test/solr-indexing-context.xml

https://jira.lib.unc.edu/browse/BXC-3695
* Force commits of solr changes before starting batches of reindexes of Work objects triggered by indexing of File objects. 
* Use ContentPathService to get ancestor path information when looking up which Files are in a Work, so that it is using the same mechanism/caching as other indexing jobs

BXC-3695 - Fix NullPointerException when reindexing Work content type

---

model-api/src/main/java/edu/unc/lib/boxc/model/api/exceptions/TombstoneFoundException.java
model-api/src/main/java/edu/unc/lib/boxc/model/api/objects/WorkObject.java
model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/objects/WorkObjectImpl.java
model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/services/RepositoryObjectDriver.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/destroy/AbstractDestroyObjectsJob.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/destroy/DestroyObjectsJob.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/destroy/DestroyObjectsJobIT.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solr/AbstractSolrProcessorIT.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solr/SolrIngestProcessorIT.java

https://jira.lib.unc.edu/browse/BXC-3676
* Catch case when primary object is a tombstone, return null instead
* Throwing a specialized error when unexpectedly retrieving a tombstone to support this
* Clear primary object relation on work if the object it references gets destroyed (aka, turned into a tombstone)

BXC-3676 - Fix error when indexing work with tombstone primary object

---

web-access-app/src/main/webapp/WEB-INF/jsp/frontPage.jsp
web-common/src/main/java/edu/unc/lib/boxc/web/common/services/SolrQueryLayerService.java

It was noticed that the links for "What's in the Repository" weren't working, and also that the counts were off between the front page and the actual results. This capitalizes the facet options and makes the count only return the works, not the works and the files.
https://jira.lib.unc.edu/browse/BXC-3747

Bxc 3747 front page facet link bug

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/solrUpdate/AggregateUpdateProcessor.java
services-camel-app/src/main/webapp/WEB-INF/solr-indexing-context.xml
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateRouterTest.java
services-camel-app/src/test/resources/solr-update-context.xml
services-camel-app/src/test/resources/solr-update-processor-it-context.xml

https://jira.lib.unc.edu/browse/BXC-3748
* Call solr commit directly rather than sending commit message referencing the root of fedora, which was causing object tpye mismatch errors when loading the object

BXC-3748 - Fix ObjectTypeMismatchException thrown during work reindexing batches

---

integration/src/test/java/edu/unc/lib/boxc/integration/web/access/EndpointIT.java
integration/src/test/java/edu/unc/lib/boxc/integration/web/access/SearchEndpointIT.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/SearchStateFactory.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/SolrSearchService.java
static/js/public/advancedSearch.js
static/js/vue-cdr-access/src/components/filterTags.vue
static/js/vue-cdr-access/tests/unit/filterTags.spec.js
web-access-app/src/main/webapp/WEB-INF/jsp/advancedSearch.jsp

https://jira.lib.unc.edu/browse/BXC-3709
* Restricts advanced search Date Deposited and Date Created fields to YEAR only
* Date Created field now searches dateCreatedYear
* Fixed a bug when generating ranges for the solr query, which was incorrectly treating both the start and the end date in the range as end dates. This was causing Date Deposited to not return records that matched the start year.
* Update display name for "added" field on search results page to "Date Deposited" for consistency (was "Date Added")

BXC-3709 - Advanced search date range fixes

---

integration/src/test/java/edu/unc/lib/boxc/integration/factories/ModsFactory.java
integration/src/test/java/edu/unc/lib/boxc/integration/web/access/CollectionsEndpointIT.java
integration/src/test/java/edu/unc/lib/boxc/integration/web/access/EndpointIT.java
integration/src/test/java/edu/unc/lib/boxc/integration/web/access/SearchEndpointIT.java

[https://jira.lib.unc.edu/browse/BXC-3732](https://jira.lib.unc.edu/browse/BXC-3732)
- add language and subject facets to `ModsFactory.java`
- modify `getNodeFromResponse` (previously `getMetadataFromResponse`)
- move `createDatedObjects` and add `createLanguageSubjectObjects` to `EndpointIT.java`
- add integration tests for language and subject facet filter searches to `SearchEndpointIT.java`

Bxc 3732 facet filters search

---

search-api/src/main/java/edu/unc/lib/boxc/search/api/models/ContentObjectRecord.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/ContentObjectSolrRecord.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/GroupedContentObjectSolrRecord.java
search-solr/src/test/java/edu/unc/lib/boxc/search/solr/models/ContentObjectSolrRecordTest.java
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/fileRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/folderRecord.jsp

https://jira.lib.unc.edu/browse/BXC-3758
As Ben notes, the url is getting generated with a value like:
https://dcr-test.lib.unc.edu/record/This%20is%20a%20serial%20title%7Ca168cf29-a2a9-4da8-9b8d-025855b180d5
but it should be:
https://dcr-test.lib.unc.edu/record/a168cf29-a2a9-4da8-9b8d-025855b180d5
so this PR adds methods to get the second part of the string and return it accordingly

BXC-3758 adding test and methods to get parentCollectionId

---

operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/ClearOrderValidator.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/OrderValidatorFactory.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/SetOrderValidator.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/order/OrderValidatorFactoryTest.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/order/SetOrderValidatorTest.java

Adding a ClearOrderValidator that checks whether the target is a work object, with a test and adding a switch statement to the OrderValidator class.
https://jira.lib.unc.edu/browse/BXC-3785

BXC-3785 add ClearOrderValidator

---

etc/solr-config/access/conf/schema.xml
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/action/SeparateRootAndDescendantsUpdateAction.java
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetMemberOrderFilter.java
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/utils/MemberOrderService.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetMemberOrderFilterTest.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/utils/MemberOrderServiceTest.java
integration/src/test/resources/spring-test/solr-indexing-context.xml
model-api/src/main/java/edu/unc/lib/boxc/model/api/objects/WorkObject.java
model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/objects/WorkObjectImpl.java
model-fcrepo/src/test/java/edu/unc/lib/boxc/model/fcrepo/objects/WorkObjectTest.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/indexing/IndexingActionType.java
search-api/src/main/java/edu/unc/lib/boxc/search/api/SearchFieldKey.java
search-api/src/main/java/edu/unc/lib/boxc/search/api/models/ContentObjectRecord.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/GroupedContentObjectSolrRecord.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/IndexDocumentBean.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/util/CacheInvalidatingProcessor.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/util/IndexingActionUtil.java
services-camel-app/src/main/webapp/WEB-INF/service-context.xml
services-camel-app/src/main/webapp/WEB-INF/solr-indexing-context.xml
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/order/OrderRequestProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateProcessorIT.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/util/CacheInvalidatingProcessorTest.java
services-camel-app/src/test/resources/solr-indexing-it-context.xml
services-camel-app/src/test/resources/solr-update-processor-it-context.xml
services-camel-app/src/test/resources/spring-test/solr-indexing-context.xml
web-services-app/src/test/resources/spring-test/solr-indexing-context.xml

https://jira.lib.unc.edu/browse/BXC-3762
I manually tested that the field is being populated when reindexing on my local vm, but there is still no way to add ordering via the UI, so this still has no visible impact.
* Adds support for indexing of member order, both during full (re)index operations and for partial updates after the order has been modified.
* For a partial update, a UPDATE_MEMBER_ORDER message is sent. This triggers an action that causes a UPDATE_MEMBER_ORDER_PARENT action to be sent which will update 
* Adds a service which computes the ordering id. There is a cache involved, so invalidation was hooked into the CacheInvalidatingProcessor which triggers when an object is modified.
* Adds memberOrderId field to solr, and objects representing solr records
* Adds method for …

BXC-3762 - Index member ordering

---

indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/utils/MemberOrderServiceTest.java
operations/src/main/java/edu/unc/lib/boxc/operations/api/order/MemberOrderHelper.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/ClearOrderValidator.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/SetOrderValidator.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/MemberOrderCsvExporter.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/exceptions/RestResponseEntityExceptionHandler.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/MemberOrderController.java
web-services-app/src/main/webapp/WEB-INF/service-context.xml
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/MemberOrderCsvExporterTest.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/MemberOrderControllerTest.java
web-services-app/src/test/resources/member-order-test-servlet.xml

https://jira.lib.unc.edu/browse/BXC-3763
* Adds service and controller for generating a CSV document for viewing and reimporting member order
* Add handling of InvalidOperationForObjectType from controllers
Can be tested locally with direct requests:
```
https://localhost:8080/services/api/edit/memberOrder/export/csv?ids=1b9500f1-187e-4bfa-9b30-efe0ec50a8a3,6047d654-7102-4f94-8829-3fc3fc00b62d
```

BXC-3763 - Export Member Order CSV

---

operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/MessageSender.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/order/MemberOrderRequestSender.java
operations-jms/src/test/java/edu/unc/lib/boxc/operations/jms/order/MemberOrderRequestSenderTest.java
services-camel-app/src/main/webapp/WEB-INF/service-context.xml
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/MemberOrderCsvConstants.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/MemberOrderCsvExporter.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/MemberOrderCsvTransformer.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/MemberOrderController.java
web-services-app/src/main/webapp/WEB-INF/service-context.xml
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/MemberOrderCsvExporterTest.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/MemberOrderCsvTransformerTest.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/MvcTestHelpers.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/AbstractAPIIT.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/MemberOrderControllerTest.java
web-services-app/src/test/resources/member-order-test-servlet.xml

https://jira.lib.unc.edu/browse/BXC-3764
* Enables updating member order via importing a CSV document
* Adds service for turning CSV into MultiParentOrderRequest
* Adds service for queuing these requests
* Wires up all the services needed to perform this service
* Adds API endpoint for doing the import
* Refactor some common constants/methods into helper classes for better access, plus some refactoring suggested by intellij

BXC-3764 - Import member order via CSV

---

operations/src/main/java/edu/unc/lib/boxc/operations/api/order/MemberOrderHelper.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/OrderValidatorFactory.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/RemoveFromOrderValidator.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/SetOrderValidator.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/order/OrderValidatorFactoryTest.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/order/RemoveFromJobTest.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/order/RemoveFromOrderValidatorTest.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/order/SetOrderJobTest.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/order/SetOrderValidatorTest.java
operations/src/test/java/edu/unc/lib/boxc/operations/test/OrderTestHelper.java

This PR adds a validator for the RemoveFromOrderJob. In doing so, methods in common with SetOrderJob and its validators/tests were moved to helpers as well.
https://jira.lib.unc.edu/browse/BXC-3792

BXC-3792 remove job validator code and moving methods to helpers

---

indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentStatusFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentStatusFilterTest.java
search-api/src/main/java/edu/unc/lib/boxc/search/api/FacetConstants.java
static/js/admin/src/ResultObject.js
static/member_order_csv.html

This adds the ability to filter by member ordering in the content facets, and adds a "members-are-ordered" tag to the works whose members are ordered.
https://jira.lib.unc.edu/browse/BXC-3808

Bxc 3808 file ordering facet

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestContentObjectsJob.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestContentObjectsJobTest.java

This adds the memberOrder property to the AIP properties.
https://jira.lib.unc.edu/browse/BXC-3789

BXC-3789 add memberOrder property to archival resource for Fedora

---

services-camel-app/pom.xml
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/http/HealthChecksController.java
services-camel-app/src/main/webapp/WEB-INF/rest-servlet.xml
services-camel-app/src/main/webapp/WEB-INF/service-context.xml
services-camel-app/src/main/webapp/WEB-INF/web.xml
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/http/HealthChecksControllerTest.java
services-camel-app/src/test/resources/health-check-test-context.xml

https://jira.lib.unc.edu/browse/BXC-3887
* Add api endpoint to services-camel to allow for HTTP requests to find out if camel is up and running. This will allow us to detect if the dcr-services-camel app hasn't started, or if it has started but the camel context is not available.
* Needed to add spring-webmvc for the controller and its test

BXC-3887 - Camel healthcheck endpoint

---

etc/ide_setup/README.md

remove `## code templates` section from intellij instructions

remove code templates section

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/CleanupDepositJob.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/work/DepositSupervisor.java

https://jira.lib.unc.edu/browse/BXC-3922
* Switch cleanup delay to using long instead of int everywhere, to avoid overflow issues for long delays in milliseconds

BXC-3922 - Use longs for deposit cleanup delay

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/SearchStateFactory.java
search-solr/src/test/java/edu/unc/lib/boxc/search/solr/services/SearchStateFactoryTest.java
static/css/cdrui_styles.css
static/js/vue-cdr-access/src/components/filterTags.vue
web-access-app/src/main/resources/search.properties
web-access-app/src/main/webapp/WEB-INF/jsp/advancedSearch.jsp

This PR adds a search by collection ID field to the advanced search. It also provides a filter tag at the top of the search results when the field is used.
https://jira.lib.unc.edu/browse/BXC-3594

Bxc 3594 add collection id search

---

web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FedoraContentController.java
web-access-app/src/test/java/edu/unc/lib/boxc/web/access/controllers/FedoraContentControllerIT.java
web-access-app/src/test/resources/fedora-content-it-servlet.xml

https://jira.lib.unc.edu/browse/BXC-3585
* Requests to download the original_file for a work now return a 400 response, rather than sometimes returning the contents of the primary object. Downloading original_files must now be done using the file id (which is how it is used in the UI already). This is also consistent with the behavior of the `services/api/file/pid/original_file` endpoint.

BXC-3585 - Download requests for work IDs behavior

---

common-utils/src/main/java/edu/unc/lib/boxc/common/util/DateTimeUtil.java
common-utils/src/test/java/edu/unc/lib/boxc/common/util/DateTimeUtilTest.java
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilterTest.java
indexing-solr/src/test/resources/datastream/dateCreatedYearIssue.xml

https://jira.lib.unc.edu/browse/BXC-3941
* Treat incoming dates as being in UTC timezone when parsing unless otherwise specified. 
* When extracting year for dateCreatedYear, extract the year using an instant in UTC timezone to avoid getting the wrong year due to timezone conversions
* Change unit test to testing public method, and adjust expectations based on UTC being the default timezone.

BXC-3941 - UTC when indexing date fields

---

.codeclimate.yml
common-utils/src/main/resources/checkstyle/checkstyle-suppressions.xml
common-utils/src/main/resources/checkstyle/checkstyle.xml
pom.xml

[https://jira.lib.unc.edu/browse/BXC-3811](https://jira.lib.unc.edu/browse/BXC-3811)
This PR includes adjustments to codeclimate check thresholds and changes to checkstyles. The checkstyles plugin works when enabled but codeclimate has a fit because there are 16k+ errors.
- added checks to codeclimate
- adjusted check thresholds to reduce issues (fixed 811 of 1558 issues)
- added duplication plugin to modify similar-code and identical-code thresholds
- updated checkstyle and checkstyle-suppressions config
- checkstyle.xml: incorporated file suppression config, moved modules, added/removed properties and comments
- updated maven-checkstyle-plugin version

Bxc 3811 adjust codeclimate thresholds 2

---

operations/src/main/java/edu/unc/lib/boxc/operations/api/order/MemberOrderHelper.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/RemoveFromOrderJob.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/SetOrderJob.java

Part of https://jira.lib.unc.edu/browse/BXC-3752
* Perform serialization of member order via a helper method, so it can be reused in chompb

BXC-3752 - Move serialization of order into a helper method

---

static/js/public/fullRecord.js

https://jira.lib.unc.edu/browse/BXC-4004
This PR removes the initial title sort so that results come back as is from solr. This would reflect the member order if it was set. It also fixes the fact that solr was returning up to 2000 results at once. Now it returns 10 to match the pagination in datatables.

Bxc 4004 adjust sort in work

---

web-access-app/src/main/resources/modsExclusionXPaths.json

This adds a hidden field in order to retain legacy Usage Rights statements from CONTENTdm for cases when rights metadata has been supplemented with RightsStatements.org URIs.

BXC-4017 Add hidden cdm rights field

---

operations/src/main/java/edu/unc/lib/boxc/operations/impl/move/MoveObjectsJob.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/move/MoveObjectsService.java
web-services-app/src/main/webapp/WEB-INF/service-context.xml
web-services-app/src/test/resources/move-objects-it-servlet.xml

https://jira.lib.unc.edu/browse/BXC-4072
* Inject missing premisLoggerFactory into service and job, which was causing a NPE when moving works between admin units because that includes an extra premis event

BXC-4072 - Fix move operations between admin units

---

indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilterTest.java
indexing-solr/src/test/resources/datastream/inventoryMods.xml

https://jira.lib.unc.edu/browse/BXC-4066
* Prevent CDM Rights statements from getting indexed
* Also split out the rights related assertions into their own tests so they are easier to detect issues with.

BXC-4066 - Prevent CDM Rights statements from getting indexed

---

static/css/cdrui_styles.css

* Switch back to showing full thumbnail (but still resolve the issue where the thumbnail was overlapping the text below it in the related items list)

Switch back to showing full thumbnail

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/longleaf/LongleafRouter.java

https://jira.lib.unc.edu/browse/BXC-4163
* Add additional activemq routes which feed into the longleaf batch register/deregister tasks, since we cannot easily move failed batch messages from the dead letter queue into an sjms batching end point

BXC-4163 - Support requeuing failed longleaf jobs

---

web-common/src/main/java/edu/unc/lib/boxc/web/common/controllers/LorisContentController.java
web-common/src/main/java/edu/unc/lib/boxc/web/common/services/LorisContentService.java

https://jira.lib.unc.edu/browse/BXC-4207
* Perform loris retry in a loop rather than recursively so that the connections will close before the next try starts, which should prevent the retries from getting stuck waiting for a connection to come available. 
* Set a shorter max time to wait for a connection to become available
* Removed a parameter that wasn't actually used, it previously just thought it was used because it was passed into a recursive call to the same method.

BXC-4207 - Loris retry connections

---

static/js/vue-cdr-access/src/components/full_record/aggregateRecord.vue
static/js/vue-cdr-access/src/components/full_record/collectionFolder.vue
static/js/vue-cdr-access/src/translations.js

Should the `no_finding_aid` line be removed from translation.js?

BXC-4199 vuejs hide FA field if blank

---

static/js/vue-cdr-access/src/components/full_record/restrictedContent.vue
static/js/vue-cdr-access/tests/unit/restrictedContent.spec.js

https://jira.lib.unc.edu/browse/BXC-4177
* Don't show download button if the dataFileUri is empty (including an empty string, which is what we get in production).

BXC-4177 - Don't show download link for works without primary objects

---

static/js/vue-cdr-access/src/components/full_record/restrictedContent.vue
static/js/vue-cdr-access/tests/unit/restrictedContent.spec.js

https://jira.lib.unc.edu/browse/BXC-4229
* Remove download button from the top of the work full record page
* Separate embargo displaying logic from download button logic, since a work can be embargoed.

BXC-4229 - Remove download button from the top of the work full record page

---

static/js/vue-cdr-access/src/components/full_record/metadataDisplay.vue
static/js/vue-cdr-access/src/components/full_record/player.vue
static/js/vue-cdr-access/src/components/modalMetadata.vue

* Add a leading slash to record page requests to prevent browsers from occasionally getting confused and requesting /record/record/ paths

Fix UV failing to load due to /record/record urls

---

web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/RunEnhancementsService.java

Relates to https://jira.lib.unc.edu/browse/BXC-4231
* Fix run enhancements action only queuing the first 20 children by setting an explicit page size and then paging through the results

BXC-4231 - Fix run enhancements only queuing first 20 items

---

static/templates/admin/addFileForm.html

https://jira.lib.unc.edu/browse/BXC-4187
This PR removed the label form field from the Add File pop up:

BXC-4187 remove label form field

---

services-camel-app/pom.xml
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/images/AddDerivativeProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/images/AddDerivativeProcessorTest.java

Part of https://jira.lib.unc.edu/browse/BXC-4274
* AddDerivativeProcessor will now succeed without adding a derivative if no derivative file exists but the generation command indicated success. 
* Refactor `process` method to split into helper methods, remove unused FileAlreadyExists behaviors, more consistently throw errors when generation fails, use Path instead of File.
*  Expanded test coverage and switched it to junit 5

BXC-4274 - AddDerivativeProcessor handle when no derivative expected to be produced

---

model-api/src/main/java/edu/unc/lib/boxc/model/api/rdf/Cdr.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/thumbnail/ThumbnailRequest.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/thumbnail/ThumbnailRequestSerializationHelper.java
services-camel-app/pom.xml
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/thumbnails/ThumbnailRequestProcessor.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/thumbnails/ThumbnailRouter.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/ProcessorTestHelper.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/order/OrderRequestProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/thumbnails/ThumbnailProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/thumbnails/ThumbnailRouterTest.java
services-camel-app/src/test/resources/thumbnails-config.properties
services-camel-app/src/test/resources/thumbnails-context.xml

This PR creates a workflow to assign a thumbnail from a file to its parent work via a router and processor. It also has associated tests, context and properties files, and a test helper file with some helper methods. Some of these methods are used in other tests but i just updated an OrderMember test to use them to see if it would work.
https://jira.lib.unc.edu/browse/BXC-4063

Bxc 4064 assign thumbnail

---

operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/thumbnail/ThumbnailRequestSender.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/ImportThumbnailService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/ThumbnailController.java
web-services-app/src/main/webapp/WEB-INF/service-context.xml
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/ThumbnailIT.java
web-services-app/src/test/resources/thumb-it-servlet.xml

This PR introduces an API endpoint to assign a thumbnail from a child object to the parent object. To do this, I moved the existing thumbnail-related controller to the `modify` package and generalized the naming so I could add the new endpoint. There are also related tests and context files.
https://unclibrary.atlassian.net/browse/BXC-4062

Bxc 4062 assign thumbnail api

---

static/js/xmleditor/templates/archives.xml

adds the new mods:displayDate field to the archives description template in the admin ui

BXC-4298 - add displayDate to archives description template

---

operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/thumbnail/ThumbnailRequest.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/thumbnail/ThumbnailRequestSender.java
operations-jms/src/test/java/edu/unc/lib/boxc/operations/jms/thumbnail/ThumbnailRequestSenderTest.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/thumbnails/ThumbnailRequestProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/thumbnails/ThumbnailProcessorTest.java

This PR adds the "action" param to Thumbnail request so that either "assign" or "delete" requests may use the same structure. The processor now processes both types of requests. A test was also added.
https://unclibrary.atlassian.net/browse/BXC-4065

BXC-4065 add delete to thumbnail request and process accordingly

---

indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentStatusFilter.java
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetDatastreamFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentStatusFilterTest.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetDatastreamFilterTest.java
model-api/src/main/java/edu/unc/lib/boxc/model/api/objects/WorkObject.java
model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/objects/WorkObjectImpl.java
model-fcrepo/src/test/java/edu/unc/lib/boxc/model/fcrepo/objects/WorkObjectTest.java
search-api/src/main/java/edu/unc/lib/boxc/search/api/FacetConstants.java
services-camel-app/src/main/webapp/WEB-INF/solr-indexing-context.xml
services-camel-app/src/test/resources/solr-indexing-it-context.xml

This PR allows the assigned thumbnail to be indexed in solr for a work. If the content object is a work object, it looks to see if there is a thumbnail object relation. if there is, then it selectively adds the thumbnail streams of the assigned file object to the work object's datastreams.
https://unclibrary.atlassian.net/browse/BXC-4082

Bxc 4082 thumbnail solr index

---

pom.xml
services-camel-app/pom.xml

https://unclibrary.atlassian.net/browse/BXC-4348
Update to activemq 5.17.6, and activemq-camel to 5.16.7 (the newest available version) to match version on server and resolve CVE

BXC-4348 - Update AMQ for CVE

---

web-services-app/pom.xml
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/IiifV3ManifestService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/IiifV3ManifestController.java
web-services-app/src/main/webapp/WEB-INF/service-context.xml
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/IiifV3ManifestServiceTest.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/IiifV3ManifestControllerTest.java

https://unclibrary.atlassian.net/browse/BXC-4330
* Adds a new services/api/iiif/v3/ endpoint for getting manifests and canvases using the iiif v3 presentation api
* Adds the jiiify-presentation dependency for use in constructing manifests
An example manifest for a work with one image file:
```
{
"@context": "http://iiif.io/api/presentation/3/context.json",
"id": "https://localhost:8080/services/api/iiif/v3/54d91d8f-5059-4324-9f10-85cc159cc79c/manifest",
"type": "Manifest",
"label":
{
"none":
[
"Test Flying Dog Work"
]
},
"metadata":
[
{
"label":
{
"none":
[
"Creators"
]
},
"value":
{
"none":
[
"Boxy"
]
}
},
{
"label":
{
"none":
[
"Subjects"
]
},
"value":
{
"none":
[
"Testing"
]
}
},
{
"label":
{
"none":
[
""
]
},
"value":
{
"none":
[
"<a …
```

BXC-4330 - IIIFv3 manifests

---

static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json
static/js/vue-cdr-access/src/components/full_record/aggregateRecord.vue
static/js/vue-cdr-access/src/components/full_record/fileList.vue
static/js/vue-cdr-access/src/mixins/fileDownloadUtils.js
static/js/vue-cdr-access/tests/unit/fileList.spec.js

https://unclibrary.atlassian.net/browse/BXC-4318

Don't show download button to users without download access

---

auth-api/src/main/java/edu/unc/lib/boxc/auth/api/services/DatastreamPermissionUtil.java
static/js/vue-cdr-access/src/components/full_record/fileList.vue
static/js/vue-cdr-access/src/components/full_record/thumbnail.vue
static/js/vue-cdr-access/tests/unit/thumbnail.spec.js
web-common/src/main/java/edu/unc/lib/boxc/web/common/services/AccessCopiesService.java
web-common/src/main/java/edu/unc/lib/boxc/web/common/services/PermissionsHelper.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/services/AccessCopiesServiceTest.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/services/PermissionsHelperTest.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/DatastreamRestControllerIT.java
web-services-app/src/test/resources/datastream-content-it-servlet.xml

https://unclibrary.atlassian.net/browse/BXC-4315

Only show thumbnails if user has viewAccessCopies permissions

---

web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/DownloadImageService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/ImageServerProxyService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/DownloadImageController.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/ImageServerProxyController.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/utils/ImageServerUtil.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/ImageServerProxyControllerTest.java

This PR adds new tests and refactors the image server proxy code to more clearly separate the controller and service. This also affected some downloadImage code to use new Util code.
https://unclibrary.atlassian.net/browse/BXC-4375

Bxc 4375 refactor image server proxy

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/VirusScanJob.java
deposit-app/src/main/webapp/WEB-INF/deposit-jobs-context.xml
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/VirusScanJobTest.java

https://unclibrary.atlassian.net/browse/BXC-4376
Use streaming scanning for files which are larger than the max scanning size, so that the first N bytes will be scanned.

BXC-4376 - Virus scan for large files

---

web-access-app/src/main/resources/recordTransformations/modsToFullRecord.xsl

- added template for identifiers
- for catalog id identifiers, generate link

BXC-4353 - catalog id link

---

web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/SingleUseKeyService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/utils/CsvUtil.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/MemberOrderCsvExporterTest.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/SingleUseKeyServiceTest.java

https://unclibrary.atlassian.net/browse/BXC-4358

Bxc-4358 manage links service

---

static/js/vue-cdr-access/src/components/aboutRepository.vue
static/js/vue-cdr-access/src/translations.js

https://unclibrary.atlassian.net/browse/BXC-3483

Move about page text to translations file

---

web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/SingleUseKeyService.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/SingleUseKeyServiceTest.java

Adding cron job and code changes to invalidate expired single use keys on a schedule (currently the first minute of every hour)
https://unclibrary.atlassian.net/browse/BXC-4362

Bxc 4362 invalidate schedule

---

static/js/vue-cdr-access/src/mixins/fileDownloadUtils.js
static/js/vue-cdr-access/tests/unit/restrictedContent.spec.js

https://unclibrary.atlassian.net/browse/BXC-4437
* Hide the download button if the user doesn't have any download options, such as if it is a very small image and they only have reduced quality access
* A few extra tests to confirm that the download button and render partial option lists.

BXC-4437 - Hide download button when no options available

---

static/js/vue-cdr-access/src/components/full_record/aggregateRecord.vue
static/js/vue-cdr-access/src/components/full_record/collectionFolder.vue
static/js/vue-cdr-access/src/components/full_record/fileRecord.vue
static/js/vue-cdr-access/src/mixins/fullRecordUtils.js
static/js/vue-cdr-access/tests/unit/aggregateRecord.spec.js

https://unclibrary.atlassian.net/browse/BXC-4444

Fix display of exhibits in the UI

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/exportxml/ExportXMLProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/exportxml/ExportXMLRouteIT.java

This PR deletes the temp files created when exporting XML and adds related tests.
https://unclibrary.atlassian.net/browse/BXC-4416

Bxc 4416 cleanup temp files

---

operations/src/main/java/edu/unc/lib/boxc/operations/api/exceptions/StateUnmodifiedException.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/edit/UpdateDescriptionService.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/importxml/ImportXMLJob.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/versioning/VersionedDatastreamService.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/edit/UpdateDescriptionServiceIT.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/versioning/VersionedDatastreamServiceIT.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/versioning/VersionedDatastreamServiceTest.java
persistence/src/main/java/edu/unc/lib/boxc/persist/impl/InputStreamDigestUtil.java
persistence/src/test/java/edu/unc/lib/boxc/persist/impl/InputStreamDigestUtilTest.java
persistence/src/test/java/edu/unc/lib/boxc/persist/impl/MultiDigestInputStreamWrapperTest.java
services-camel-app/src/main/resources/update-complete-html.txt

https://unclibrary.atlassian.net/browse/BXC-3390
* VersionedDatastreamService now supports flag to tell it to skip updates if the SHA1 of the new version and existing version are the same
* UpdateDescriptionService uses this flag to prevent unnecessary updates when the incoming data is unchanged
* Adds utility for digest calculation on a stream
* Adds test coverage for MultiDigestInputStreamWrapper

BXC-3390 - Skip MODS updates when content is unmodified

---

static/js/admin/src/action/ExportMetadataXMLBatchAction.js

https://unclibrary.atlassian.net/browse/BXC-4461
Match form field to `onlyIncludeValidDatastreams` setter otherwise the value is always false

Match form field to onlyIncludeValidDatastreams setter

---

operations/src/main/java/edu/unc/lib/boxc/operations/impl/acl/PatronAccessAssignmentService.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/acl/PatronAccessAssignmentServiceIT.java

https://unclibrary.atlassian.net/browse/BXC-4361
* Add previous patron role state to premis event when assigning. 
* Ensure that assignments show up in a consistent order by sorting them (to prevent flapping tests)

BXC-4361 - Capture previous patron role state in premis event

---

deposit-app/src/test/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit-app/src/test/resources/simpleMods.xml
integration/src/test/java/edu/unc/lib/boxc/integration/factories/ContentObjectFactory.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/edit/EditTitleService.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/edit/UpdateDescriptionService.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/edit/EditTitleServiceTest.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/edit/UpdateDescriptionServiceTest.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/importxml/ImportXMLJobIT.java
operations/src/test/resources/samples/modsNormalized.xml
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/enhancements/EnhancementRouterIT.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/AddContainerService.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/EditTitleIT.java

https://unclibrary.atlassian.net/browse/BXC-4459
* Perform normalization of MODS documents when updating descriptions by pretty printing.
* Improve test coverage of UpdateDescriptionService.
* Allow MODS documents to be passed in directly without needing to be deserialized first, and update usages of the update service to do this to save unnecessary steps.

BXC-4459 - MODS ingest in consistent format

---

web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/AnalyticsTrackerUtil.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/utils/AnalyticsTrackerUtilTest.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/DownloadImageController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/DownloadImageControllerIT.java
web-services-app/src/test/resources/download-image-it-servlet.xml

This PR generates a random UUID and sets the user id to that for analytics usage, to fix these errors in the log:
`An exception occurred while recording download event on http://dcr-bes.libint.unc.edu:8181/fcrepo/rest/content/5b/b8/10/4c/5bb8104c-c218-4ee6-bd0b-6d7a705f4f83
java.lang.NullPointerException: inputHex is marked non-null but is null
at org.matomo.java.tracking.parameters.VisitorId.fromHex(VisitorId.java:87)
at edu.unc.lib.boxc.web.common.utils.AnalyticsTrackerUtil.buildMatomoRequest(AnalyticsTrackerUtil.java:70)`
https://unclibrary.atlassian.net/browse/BXC-4488

BXC-4488 fix null user id error and add test

---

pom.xml
web-common/pom.xml

Relates to https://unclibrary.atlassian.net/browse/BXC-4497
* Switch to using matomo java11 implementation, update version
* Update other dependencies with security alerts

BXC-4497 - Update matomo tracker and other dependencies

---

web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/AnalyticsTrackerUtil.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/utils/AnalyticsTrackerUtilTest.java

https://unclibrary.atlassian.net/browse/BXC-4497

BXC-4497 - Temporarily disabling setting of a random user id

---

web-access-app/src/main/webapp/WEB-INF/access-fedora-context.xml
web-common/pom.xml
web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/AnalyticsTrackerUtil.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/utils/AnalyticsTrackerUtilTest.java
web-services-app/src/main/webapp/WEB-INF/service-context.xml

https://unclibrary.atlassian.net/browse/BXC-4497
* Reuse a single instance of MatomoTracker
* Add init and close methods to AnalyticsTrackerUtil to create the MatomoTracker and shut it down
* Update to Matomo-java-tracker 3.3.0

BXC-4497 - Use single MatomoTracker instance

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/MultiSelectFacetListService.java
search-solr/src/test/java/edu/unc/lib/boxc/search/solr/services/MultiSelectFacetListServiceIT.java

https://unclibrary.atlassian.net/browse/BXC-4505
* Prevent error when no facet fields are returned while populating facet list

BXC-4505 - Prevent error when no facet fields are returned while populating facet list

---

web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/ExportCsvService.java
web-services-app/src/main/webapp/WEB-INF/service-context.xml
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/ExportCsvIT.java
web-services-app/src/test/resources/export-csv-it-servlet.xml

https://unclibrary.atlassian.net/browse/BXC-4514
* In CSV export, switch Embargoed column to Embargo Date, and store the value in date format. Update tests accordingly

BXC-4514 - CSV export embargo dates

---

model-api/src/main/java/edu/unc/lib/boxc/model/api/rdf/Cdr.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequest.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequestSerializationHelper.java
operations-jms/src/test/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequestSerializationHelperTest.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRequestProcessor.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRouter.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/TestHelper.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/order/OrderRequestProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRouterTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/thumbnails/ThumbnailProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/thumbnails/ThumbnailRouterTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/viewSettings/ViewSettingRequestProcessorTest.java
services-camel-app/src/test/resources/config.properties
services-camel-app/src/test/resources/streaming-context.xml

This PR includes the processor, router, request, request serialization helper, and their associated tests for adding streaming properties to files. It also renames the ProcessorTestHelper since I added a method for the router tests to it (and updated the view setting router test, but did not update any other router tests as that's out of scope)
https://unclibrary.atlassian.net/browse/BXC-4445

Bxc 4445 duracloud service

---

auth-fcrepo/src/main/java/edu/unc/lib/boxc/auth/fcrepo/services/GroupsThreadStore.java
web-common/src/main/java/edu/unc/lib/boxc/web/common/auth/PatronPrincipalProvider.java
web-common/src/main/java/edu/unc/lib/boxc/web/common/auth/filters/StoreUserAccessControlFilter.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/auth/PatronPrincipalProviderTest.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/auth/filters/StoreUserAccessControlFilterTest.java

https://unclibrary.atlassian.net/browse/BXC-4503
* Use the last IP in x-forwarded-for header if multiple are present, since it is the one set by our server rather than the client. 
* This should resolve the "No access groups" issue we have been having.
* Increase log level when an exception is thrown while setting user access info
* Remove unused code related to setting user access info, some of which was leftover from when the application used JSP for the front end.
* Always clear agentPrincipals when setting groups

BXC-4503 - Handle multiple IPs and cleanup

---

operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequest.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequestSender.java
operations-jms/src/test/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequestSenderTest.java
operations-jms/src/test/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequestSerializationHelperTest.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRequestProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRouterTest.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/StreamingPropertiesController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/StreamingPropertiesIT.java

This PR adds necessary files for adding and deleting streaming properties via API endpoint. It also refactors some validations and makes the TestHelper file more generic so it's not just for Processor tests.
https://unclibrary.atlassian.net/browse/BXC-4448

Bxc 4448 api endpoint

---

web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FedoraContentController.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/DatastreamController.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/SingleUseKeyController.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/exceptions/RestResponseEntityExceptionHandler.java

https://unclibrary.atlassian.net/browse/BXC-4521
* Handle uncaught EOFExceptions (which are thrown when the client disconnects early) by demoting it to a debug statement. 
* Allow download methods in the services app to throw IOExceptions rather than handling them locally, so that general error handling can deal with them, and specifically deal with EOFExceptions. 
* Exception handling methods now should now have a fall back for all exceptions, not just RuntimeExceptions

BXC-4521 - Handle client connections being closed early during single use link downloads

---

search-solr/pom.xml
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/SearchStateFactory.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/utils/FacetFieldUtil.java
search-solr/src/test/java/edu/unc/lib/boxc/search/solr/services/SearchStateFactoryTest.java

https://unclibrary.atlassian.net/browse/BXC-4524
* Add special handling of field name not existing when setting facetLimits, and reduce logging of other facet class errors.
* Increase test coverage of the SearchStateFactory createSearchState method
* Add mockito-inline jar so that we can mock static methods (this is built into mockito-core in version 5)

BXC-4524 - Cleanup warnings when invalid facet key provided

---

model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/objects/WorkObjectImpl.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/destroy/DestroyObjectsJob.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/destroy/DestroyObjectsProcessor.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateProcessor.java
services-camel-app/src/main/webapp/WEB-INF/service-context.xml
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateProcessorTest.java
services-camel-app/src/test/resources/destroy-objects-context.xml

https://unclibrary.atlassian.net/browse/BXC-4532
* Destroying files had not been fully updated to work with member order 
* Inject missing dependency, 
* prevent indexing error when a tombstone is supposed to be indexed, 
* improve test coverage in SolrUpdateProcessor, 
* address codeclimate warning
* Skip splitting member order string if the string is empty, otherwise split returns an array like `[""]`

BXC-4532 - Fix destroy file operation

---

operations/src/main/java/edu/unc/lib/boxc/operations/impl/destroy/DestroyObjectsJob.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/destroy/DestroyObjectsJobTest.java

https://unclibrary.atlassian.net/browse/BXC-4579
Skip destroying children that are already tombstones. Add unit test to verify this situation, since it's hard to reproduce in an IT

BXC-4579 - Fix destroy error when member already tombstone

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/solrUpdate/AggregateUpdateProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateRouterTest.java

https://unclibrary.atlassian.net/browse/BXC-4589
* Verify that an object exists in solr before attempting to update it via AggregateUpdateProcessor, which is currently only used for the workflow that triggers indexing of the parent work when a binary is updated.

BXC-4589 - Prevent attempt to update work before it is indexed

---

common-utils/src/main/java/edu/unc/lib/boxc/common/http/MimetypeHelpers.java
common-utils/src/test/java/edu/unc/lib/boxc/common/http/MimetypeHelpersTest.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJob.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJobTest.java

https://unclibrary.atlassian.net/browse/BXC-4604
* Update TechnicalMetadata FITS job to always use a symlink before processing, and use the provided label for the filename if present. 
* Files with unicode characters can be processed by the FITS web app now since the paths get sanitized there now too
* Ignore symlink mimetype when deciding which mimetype to use, since everything is going to return symlink now

BXC-4604 - Use label as filename for TechMD extract

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/images/ImageDerivativeProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/images/ImageEnhancementsRouterTest.java

https://unclibrary.atlassian.net/browse/BXC-4590
* Add icon files to the list of image types not to attempt to produce derivatives for. 
* Add missing mock statements to some tests that were passing for the wrong reason

BXC-4590 - Skip Derivatives for icon files

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/ValidateContentModelJob.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestContentObjectsJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/ValidateContentModelJobTest.java
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentTypeFilter.java
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetDatastreamFilter.java
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentTypeFilterTest.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetDatastreamFilterTest.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilterTest.java
model-api/src/main/java/edu/unc/lib/boxc/model/api/StreamingConstants.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequest.java
operations-jms/src/test/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequestSenderTest.java
operations-jms/src/test/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequestSerializationHelperTest.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRequestProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRouterTest.java
static/js/admin/src/EditStreamingPropertiesForm.js
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/StreamingPropertiesController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/StreamingPropertiesIT.java

Part of https://unclibrary.atlassian.net/browse/BXC-4612
* Update indexing filters to allow for streaming only file objects
* Move streaming constants to their own file in the model-api module so they can be used everywhere
* Refactored getAlternativeTitle to cut down on unnecessary data retrieval by using early returns, since I had to expand it anyways.

BXC-4612 - Update solr indexing to allow for streaming only files

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/normalize/AbstractFileServerToBagJob.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/normalize/NormalizeFileObjectsJob.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/normalize/BagIt2N3BagJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/normalize/DirectoryToBagJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/normalize/NormalizeFileObjectsJobTest.java

https://unclibrary.atlassian.net/browse/BXC-3584
Add tests and assertions to verify that primary object does not get set during bag and directory ingests, and in the normalization job. Modify the jobs not to set it. This mainly affects bag and directory deposits.

BXC-3584 - Do not default to setting primary object in deposits

---

static/js/admin/src/ResultObject.js

Part of investigation into why "no-streaming" and "no-access-surrogate" tags were displaying
https://unclibrary.atlassian.net/browse/BXC-4654

Add help text for streaming and access surrogates

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/SolrSearchService.java
search-solr/src/test/java/edu/unc/lib/boxc/search/solr/services/SolrSearchServiceIT.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/DownloadImageController.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/exceptions/RestResponseEntityExceptionHandler.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/DownloadImageControllerIT.java

https://unclibrary.atlassian.net/browse/BXC-4664
* Throw a SolrRuntimeException when a SolrServerException happens, rather than returning null (which results in a NullPointerException later on in some cases, such as the bug encountered here)
* Check whether the result is null in downloadImages controller and throw appropriate error if it is. 
* Removed unused method in SolrSearchService, and some cleanup
* Added direct test coverage of SolrSearchService

BXC-4664 - Handling of SolrServerExceptions

---

fcrepo-utils/src/main/java/edu/unc/lib/boxc/fcrepo/exceptions/RangeNotSatisfiableException.java
fcrepo-utils/src/main/java/edu/unc/lib/boxc/fcrepo/utils/ClientFaultResolver.java
fcrepo-utils/src/test/java/edu/unc/lib/boxc/fcrepo/exceptions/RangeNotSatisfiableExceptionTest.java
model-api/src/main/java/edu/unc/lib/boxc/model/api/exceptions/FedoraException.java
web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FedoraContentController.java
web-access-app/src/test/java/edu/unc/lib/boxc/web/access/controllers/FedoraContentControllerIT.java
web-access-app/src/test/java/edu/unc/lib/boxc/web/access/controllers/FedoraContentControllerTest.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/exceptions/RestResponseEntityExceptionHandler.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/DatastreamRestControllerIT.java

https://unclibrary.atlassian.net/browse/BXC-4694
* Handle responses from fedora where the range is not satisfiable by returning a 416 rather than a 500
* Increase the logging for uncaught exceptions during fedora content downloads to include header info, so it's not clear what the conditions that cause some similar looking errors were.

BXC-4694 - Handle RangeNotSatisfiable

---

static/js/admin/src/action/RefreshResultAction.js

https://unclibrary.atlassian.net/browse/BXC-3156

Set max refresh attempts

---

.github/workflows/build.yml
docker-compose.yml
etc/solr-config/access/conf/solrconfig.xml
etc/solr-config/access/conf/solrcore.properties
etc/solr-config/access/core.properties
etc/solr-config/log4j2.xml
indexing-solr/pom.xml
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/action/BaseEmbeddedSolrTest.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentTypeFilterTest.java
integration/pom.xml
integration/src/test/resources/spring-test/solr-embedded-context.xml
model-fcrepo/pom.xml
persistence/pom.xml
pom.xml
search-solr/src/test/java/edu/unc/lib/boxc/search/solr/test/BaseEmbeddedSolrTest.java
services-camel-app/pom.xml
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRequestProcessor.java
services-camel-app/src/test/resources/spring-test/solr-indexing-context.xml
web-common/pom.xml
web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/AnalyticsTrackerUtil.java
web-services-app/pom.xml
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/IiifV3ManifestService.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/ExportCsvIT.java
web-services-app/src/test/resources/spring-test/solr-indexing-context.xml

https://unclibrary.atlassian.net/browse/BXC-4701 
* Uses solrj clients version 9.6
* Uses solr version 9.6 for tests
* Uses containerized version of solr for integration tests that used standalone solr, while the tests that were using embedded solr are still using that (we will probably want to move those over later)
* Wiremock moved over to the "standalone" version of its dependency, due to dependency conflicts with solr jetty versions (maybe resolved after moving to external solr for all tests)
* Associated updates to configuration and dependencies, including some that were previously being pulled in transitively.

BXC-4701 - Update clients/tests to solr 9

---

.github/workflows/build.yml
docker-compose.yml
etc/solr-config/access/conf/solrconfig.xml
etc/solr-config/access/core.properties
etc/solr-config/log4j2.xml
indexing-solr/pom.xml
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/action/BaseEmbeddedSolrTest.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentTypeFilterTest.java
integration/pom.xml
integration/src/test/resources/spring-test/solr-embedded-context.xml
model-fcrepo/pom.xml
persistence/pom.xml
pom.xml
search-solr/src/test/java/edu/unc/lib/boxc/search/solr/test/BaseEmbeddedSolrTest.java
services-camel-app/pom.xml
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRequestProcessor.java
services-camel-app/src/test/resources/spring-test/solr-indexing-context.xml
web-common/pom.xml
web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/AnalyticsTrackerUtil.java
web-services-app/pom.xml
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/IiifV3ManifestService.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/ExportCsvIT.java
web-services-app/src/test/resources/spring-test/solr-indexing-context.xml

* Update to solr 9, and wiremock 3 due to jetty versions. Update some commons usages which were referencing libraries pulled in by old solr versons
* Update solr config, make paths absolute since it is now required, and don't double load config
* Switch over to wiremock-jre8-standalone to avoid jetty version conflicts with solr
* Running solr 9 in docker for the integration tests that ran it in jetty, since it was failing to start. Add solr logging config
* Adjusting ghactions
* Try solr as docker run
* Reenable build
* Explicitly add solr-api as compile scope, otherwise solr-core pulls it in as test. Add commons-codec directly in a lower module, since it was previously being imported via transitive dependencies, but no longer is

BXC-4701 - Update clients/tests to solr 9 (#1791) (repeat to merge solr-9-development into main)

---

web-access-app/src/test/java/edu/unc/lib/boxc/web/access/controllers/FedoraContentControllerIT.java
web-common/src/main/java/edu/unc/lib/boxc/web/common/services/FedoraContentService.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/services/FedoraContentServiceTest.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/DatastreamRestControllerIT.java

https://unclibrary.atlassian.net/browse/BXC-4709
* If end of range is equal to or greater than the size of the file, remove it so we get the remainder of the file. 
* Add more testing for FedoraContentService

BXC-4709 - Handle range end >= file size

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/audio/AudioDerivativeProcessor.java

[https://unclibrary.atlassian.net/browse/BXC-4715](https://unclibrary.atlassian.net/browse/BXC-4715)
- `AudioDerivativeProcessor`: add all audio formats currently in dcr prod and supported by ffmpeg to `MIMETYPE_PATTERN`

BXC-4715 all audio to m4a

---

static/js/admin/src/action/RunEnhancementsBatchAction.js
static/templates/admin/runEnhancementsForm.html
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/RunEnhancementsRequest.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/RunEnhancementsService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/RunEnhancementsController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/RunEnhancementsServiceTest.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/RunEnhancementsIT.java

https://unclibrary.atlassian.net/browse/BXC-4729
* Extends Run Enhancements form to allow the list of ids submitted to be hand edited, and adds a checkbox for whether to run enhancements recursively
* Updates Run Enhancements server side code to make recursive execution controlled by a flag.
* RunEnhancementsRequest split into standalone class and used for passing params to service.
* Adds a unit test for run enhancements service

BXC-4729 - Run enhancements for list of objects

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/images/ImageEnhancementsRouter.java
services-camel-app/src/main/webapp/WEB-INF/service-context.xml

Part of https://unclibrary.atlassian.net/browse/BXC-4541
* Set explicit sizes for thread pool used in services camel, granting a somewhat larger pool thank default. 
* Perform calls for cantaloupe cache invalidation in a separate thread so that it won't block jp2 generation from continuing
* Use rate limiting to avoid overwhelming cantaloupe with requests

BXC-4541 - Tuning of cantaloupe cache invalidation

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/filters/MultipleDirectlyOwnedDatastreamsFilter.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/filters/QueryFilterFactory.java
search-solr/src/test/java/edu/unc/lib/boxc/search/solr/filters/QueryFilterFactoryTest.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/exportxml/ExportXMLProcessor.java

https://unclibrary.atlassian.net/browse/BXC-4779
Filter was failing for jp2's with extent info since that comes after the owner section

BXC-4779 - Fix viewable files filter

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/images/ImageDerivativeProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/images/ImageDerivativeProcessorTest.java

Part of https://unclibrary.atlassian.net/browse/BXC-4775
* Block jp2 processing for x-raw-panasonic. 
* Add unit test

BXC-4775 - Block jp2 processing for x-raw-panasonic

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/thumbnails/ImportThumbnailRequestProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/thumbnails/ImportThumbnailProcessorTest.java

https://unclibrary.atlassian.net/browse/BXC-4761
Forcing derivative regeneration when a thumbnail is uploaded.

Bxc 4761 replace existing bug

---

operations/src/main/java/edu/unc/lib/boxc/operations/impl/download/DownloadBulkService.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/download/DownloadBulkServiceTest.java
web-services-app/src/main/webapp/WEB-INF/service-context.xml
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/DownloadBulkControllerIT.java

https://unclibrary.atlassian.net/browse/BXC-4771

Bxc 4771 upper file limit

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/images/ImageDerivativeProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/images/ImageDerivativeProcessorTest.java

[https://unclibrary.atlassian.net/browse/BXC-4792](https://unclibrary.atlassian.net/browse/BXC-4792)
- block jp2 processing for image/vnd.microsoft.icon
- add test

BXC-4792 block jp2 processing for image/vnd.microsoft.icon

---

static/js/vue-cdr-access/src/components/full_record/aggregateRecord.vue
static/js/vue-cdr-access/src/components/full_record/bulkDownload.vue
static/js/vue-cdr-access/tests/unit/bulkDownload.spec.js

https://unclibrary.atlassian.net/browse/BXC-4794
Add alert which prompts user to confirm they want to go through with export when there are too many files

BXC-4794 - Too many files for bulk download

---

web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/ChompbController.java
web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/processing/ChompbPreIngestService.java
web-admin-app/src/main/webapp/WEB-INF/service-context.xml
web-admin-app/src/test/java/edu/unc/lib/boxc/web/admin/controllers/ChompbControllerIT.java
web-admin-app/src/test/java/edu/unc/lib/boxc/web/admin/controllers/processing/ChompbPreIngestServiceTest.java
web-admin-app/src/test/resources/server.properties

https://unclibrary.atlassian.net/browse/BXC-4691

Bxc 4691 chompb cropping

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/normalize/PreconstructedDepositJob.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/work/AbstractDepositJob.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestContentObjectsJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestDepositRecordJobIT.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/fcrepo4/StaffOnlyPermissionJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/normalize/BagIt2N3BagJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/normalize/CDRMETS2N3BagJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/normalize/DirectoryToBagJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/normalize/NormalizeFileObjectsJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/normalize/PreconstructedDepositJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/normalize/Simple2N3BagJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/normalize/VocabularyEnforcementJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/ValidateContentModelJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/ValidateDescriptionJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/ValidateFileAvailabilityJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/VirusScanJobTest.java
deposit-utils/src/main/java/edu/unc/lib/boxc/deposit/impl/model/DepositDirectoryManager.java
deposit-utils/src/test/java/edu/unc/lib/boxc/deposit/impl/model/DepositDirectoryManagerTest.java

Relates to https://unclibrary.atlassian.net/browse/BXC-4787
* Consolidated deposit directory logic into DepositDirectoryManager.
* Added alt text getter methods. 
* Directory getter methods no longer default to creating parent directories, but there are no overridden methods which can be used for that

BXC-4787 - Consolidate deposit directory logic and add alt text path getter

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/images/ImageEnhancementsRouter.java

[https://unclibrary.atlassian.net/browse/BXC-4777](https://unclibrary.atlassian.net/browse/BXC-4777)
- skip retries for `DerivativeGenerationException` errors

BXC-4777 improve handing and retries of jp2 generation errors

---

model-api/src/main/java/edu/unc/lib/boxc/model/api/sparql/SparqlUpdateHelper.java
model-fcrepo/src/test/java/edu/unc/lib/boxc/model/fcrepo/services/RepositoryObjectFactoryTest.java

https://unclibrary.atlassian.net/browse/BXC-4863
* Escape quotes in string literals when replacing relationships

BXC-4863 - Fix error when changing filename to contain quote

---

static/css/admin/search_results.css
static/js/admin/src/ResultView.js
static/js/vue-cdr-access/src/components/full_record/collectionRecord.vue
static/js/vue-cdr-access/src/components/listDisplay.vue
static/templates/admin/resultEntry.html
static/templates/admin/resultTableView.html
web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/AbstractSearchController.java
web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/ResultEntryController.java
web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/SerializationUtil.java

[https://unclibrary.atlassian.net/browse/BXC-4869](https://unclibrary.atlassian.net/browse/BXC-4869)
- add `collectionId` sortable field to admin UI
- if the `collectionId` is present, display `collectionId` in collection browse and under the collection name when collection results are returned

BXC-4869 display archival collection id in additional locations

---

etc/solr-config/access/conf/schema.xml
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetAspaceRefIdFilter.java
search-api/src/main/java/edu/unc/lib/boxc/search/api/SearchFieldKey.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/SolrSearchService.java
static/js/admin/src/SearchTags.js
static/templates/admin/searchMenu.html
web-admin-app/src/main/resources/search.properties
web-admin-app/src/main/webapp/WEB-INF/jsp/search/searchMenu.jsp

[https://unclibrary.atlassian.net/browse/BXC-4929](https://unclibrary.atlassian.net/browse/BXC-4929)
- add `identifierIndex` field to solr schema and copy `aspaceRefId` field into `identifierIndex`
- add `identifierIndex` to `SearchFieldKeys`
- update the admin UI to make this field searchable from the left hand search box, with drop down labeled "Identifier"

BXC-4929 add identifier search index for admin UI

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestContentObjectsJob.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/ValidateContentModelJob.java
deposit-app/src/main/resources/cdr-schema.ttl
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestContentObjectsJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/ValidateContentModelJobTest.java

[https://unclibrary.atlassian.net/browse/BXC-4959](https://unclibrary.atlassian.net/browse/BXC-4959)
- update `populateAIPProperties` to add the `CdrAspace.RefId` property if it is present
- update `cdr-schema.ttl` to only allow the `CdrAspace.RefId` property to works

BXC-4959 update deposit pipeline to receive refIds

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/images/PdfImageProcessor.java

https://unclibrary.atlassian.net/browse/BXC-4968
* Explicitly close randomAccessReadBuffer to prevent memory leaks. The inputstream that it wraps is being closed, but closing the buffer as well

BXC-4968 - Explicitly close randomAccessReadBuffer to prevent memory leaks

---

.github/workflows/build.yml
pom.xml
services-camel-app/pom.xml
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/images/PdfImageProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/images/PdfImageProcessorTest.java

https://unclibrary.atlassian.net/browse/BXC-4962
* App jp2 library so that pdfs containing them will render. 
* Handle ioexceptions during PDF rendering to reduce verbosity and prevent retries. This is to deal with the other exceptions that occurred during PDF image generation
* Update setup-java gh action and specify a distribution, since GH actions was randomly failing to get a JDK

BXC-4962 - PDF error handling and embedded jp2s

---

operations/src/test/java/edu/unc/lib/boxc/operations/impl/metadata/ExportDominoMetadataServiceTest.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/filters/HasPopulatedFieldFilter.java
search-solr/src/test/java/edu/unc/lib/boxc/search/solr/filters/QueryFilterFactoryTest.java

Part of https://unclibrary.atlassian.net/browse/BXC-4975
* HasPopulatedFieldFilter will now only match non-blank values. Not doing this was causing blank ref ids to get submitted to domino

BXC-4975 - Don't submit blank ref ids to domino

---

static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json

* Lock clover-iiif to 2.14 because there is an issue in 2.15 that prevents the build from passing https://github.com/samvera-labs/clover-iiif/issues/291 . 
* Update dependencies so it will build in arm64

Update vue dependencies in java-21 for arm64
