UNC-Libraries/box-c

services/src/main/java/edu/unc/lib/dl/cdr/services/rest/ContainerDataFileChecksumsController.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/ContainerManifestController.java

* Include missing AND in file list query
* Set the "rows" parameter for queries to an arbitrary largish number (1000)

Quick fixes for CSV export controllers

---

access/src/main/external/static/css/admin/search_results.css
access/src/main/external/static/css/cdr_access.css
access/src/main/external/static/css/cdr_admin.css
access/src/main/external/static/css/cdr_common.css
access/src/main/external/static/js/admin/src/MoveDropLocation.js
access/src/main/external/static/js/admin/src/ResultTableView.js
access/src/main/external/static/js/cdr-admin.js
access/src/main/external/static/templates/admin/resultEntry.html
access/src/main/external/static/templates/admin/resultTableHeader.html
access/src/main/external/static/templates/structureEntry.html

* Use resource_icon class
* Add a case for one other item (so we don't see "1 other items")
* Make resource_icon classnames lower case and fix other references

Fix display of move helper

---

access/src/main/external/static/css/admin/jquery.xmleditor.css
access/src/main/external/static/js/admin/editDescription.js
access/src/main/external/static/js/admin/resultList.js
access/src/main/external/static/js/admin/reviewList.js
access/src/main/external/static/js/admin/src/AbstractFileUploadForm.js
access/src/main/external/static/js/admin/src/ResultObject.js
access/src/main/external/static/js/admin/src/ResultObjectActionMenu.js
access/src/main/external/static/js/admin/src/ResultView.js
access/src/main/external/static/js/admin/src/StringUtilities.js
access/src/main/external/static/js/admin/trashList.js
access/src/main/external/static/js/cdr-admin.js
access/src/main/external/static/js/xmleditor/jquery.xmleditor.js
access/src/main/external/static/templates/admin/resultEntry.html
access/src/main/webapp/WEB-INF/jsp/common/header.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/metadataBody.jsp
admin/src/main/webapp/WEB-INF/jsp/common/header.jsp
admin/src/main/webapp/WEB-INF/jsp/edit/description.jsp

Improved linkage back and forth between the public and admin UI's.

Admin public linkage

---

access-common/src/main/java/edu/unc/lib/dl/ui/util/SerializationUtil.java
admin/src/main/java/edu/unc/lib/dl/admin/controller/ExportController.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/BriefObjectMetadata.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/BriefObjectMetadataBean.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/GroupedMetadataBean.java
solr-search/src/test/java/edu/unc/lib/dl/search/solr/model/BriefObjectMetadataBeanTest.java

- Delegates to getRelation("label") currently
- Update ExportController to use getLabel

Introduce BriefObjectMetadata#getLabel, which returns an object's label

---

sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/deposit/AbstractDepositHandler.java

This means that we respect the On-Behalf-Of header if present.

Set the depositorName of a deposit to be the "owner"

---

deposit/src/test/resources/service-context.xml
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetRelationsFilterTest.java
solr-search/src/test/java/edu/unc/lib/dl/search/solr/model/BriefObjectMetadataBeanTest.java

- in deposit, service-context.xml was missing DepositEmailHandler, and included the old SendDepositorEmailJob
- solr-ingest and solr-search tests were checking for the label relation, which has been removed

Fix unit tests in deposit, solr-ingest, and solr-search

---

access/src/main/external/static/css/admin/admin_forms.css
access/src/main/external/static/css/cdr_admin.css
access/src/main/external/static/js/admin/src/AbstractFileUploadForm.js
access/src/main/external/static/js/admin/src/EditLabelForm.js
access/src/main/external/static/js/admin/src/ResultObjectActionMenu.js
access/src/main/external/static/js/admin/src/ResultTableView.js
access/src/main/external/static/js/cdr-admin.js
access/src/main/external/static/templates/admin/editLabelForm.html
admin/src/main/java/edu/unc/lib/dl/admin/controller/EditLabelController.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/ManagementClient.java
services/src/main/java/edu/unc/lib/dl/cdr/services/model/FedoraEventMessage.java
services/src/main/java/edu/unc/lib/dl/cdr/services/processing/SolrUpdateConductor.java

Edit Label feature added.
Created a controller,
Update Fedora Signals to Solr
Created an edit label form js
Modified Resultactionmenu to accommodate new changes

--Adding "Edit Label" feature

---

access/src/main/external/static/recordTransformations/modsToFullRecord.xsl

values for elements with @type not showing up.  Tried to add that back.  Maybe I succeeded, maybe not.  We'll see.  Next time on,
OPEN SUPPOSITORIES.

added back value for elements with type attribute

---

admin/src/main/java/edu/unc/lib/dl/admin/controller/EditLabelController.java
admin/src/main/webapp/WEB-INF/access-fedora-context.xml

Add a Premis event to track when a file/container has been renamed

Add Premis event to the file/container renaming process.

---

access-common/src/main/java/edu/unc/lib/dl/ui/util/SerializationUtil.java
access/src/main/external/static/css/admin/search_results.css
access/src/main/external/static/css/cdr_admin.css
access/src/main/external/static/js/admin/resultList.js
access/src/main/external/static/js/admin/src/ActionEventHandler.js
access/src/main/external/static/js/admin/src/MoveActionMonitor.js
access/src/main/external/static/js/admin/src/ResultObject.js
access/src/main/external/static/js/admin/src/ResultObjectList.js
access/src/main/external/static/js/admin/src/ResultTableView.js
access/src/main/external/static/js/admin/src/ResultView.js
access/src/main/external/static/js/admin/src/SearchMenu.js
access/src/main/external/static/js/admin/src/action/MoveObjectsAction.js
access/src/main/external/static/js/cdr-admin.js
admin/src/main/java/edu/unc/lib/dl/admin/controller/AbstractSearchController.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/MoveObjectsController.java

Tracks ongoing move operations on the server.  Clients poll server for changes to set of ongoing move operations, displaying which items are actively being moved to all users.  Informs originating user when their move operations complete.

Move reporting

---

access/src/main/external/static/js/admin/editDescription.js
access/src/main/external/static/js/xmleditor/jquery.xmleditor.js
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/managers/ContainerManagerImpl.java

Output useful, verbose error messages when user generates a 500 error, instead of just generating a 500 error with no further info.

Output useful, verbose error messages when user generates a 500 error.

---

deposit/src/main/resources/service-context.xml
deposit/src/test/resources/service-context.xml
pom.xml
services/src/main/webapp/WEB-INF/rest-servlet.xml
services/src/main/webapp/WEB-INF/service-context.xml
services/src/main/webapp/WEB-INF/sword-servlet.xml

* Updated jedis version
* Removed extra jedis pool and config beans

Updated jedis from 2.2.1 to 2.7.2

---

access/src/main/external/static/css/admin/admin_forms.css
access/src/main/external/static/css/admin/cdradmin.css
access/src/main/external/static/css/admin/jquery.xmleditor.css
access/src/main/external/static/css/cdr_admin.css
access/src/main/external/static/js/admin/editDescription.js
access/src/main/external/static/js/xmleditor/jquery.xmleditor.js
access/src/main/external/static/js/xmleditor/templates/generic.xml
access/src/main/external/static/js/xmleditor/templates/mods.xml
admin/src/main/java/edu/unc/lib/dl/admin/controller/MODSController.java
admin/src/main/webapp/WEB-INF/jsp/edit/description.jsp

Created new branch without the cruft of the other templating branch

Add templates to main CDR xml editor

---

access/src/main/external/static/js/admin/src/statusMonitor/DepositMonitor.js

I thought this could use a comment since it's the opposite of what one might expect.

Add comment to clarify sorting.

---

deposit/src/main/java/edu/unc/lib/deposit/validate/ValidateFileAvailabilityJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/main/resources/service-context.xml

This ensures that referenced files exist before continuing with virus scanning, ingest, etc.

Introduce ValidateFileAvailabilityJob.

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo3/IngestDeposit.java

Attempt to determine if an existing file is okay during ingest, including when the object is either from the same deposit or is the same size

Prevent failure on duplicate pid

---

metadata/src/main/java/edu/unc/lib/dl/util/ContentModelHelper.java
services-worker/src/main/java/edu/unc/lib/dl/cdr/services/imaging/ImageEnhancement.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetPathFilterTest.java

Removed references to jp2 content model and its assignment during the ImageEnhancement

jp2 content model

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo3/IngestDeposit.java
deposit/src/main/resources/service-context.xml
deposit/src/test/java/edu/unc/lib/deposit/fcrepo3/IngestDepositTest.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/ManagementClient.java
persistence/src/main/java/edu/unc/lib/dl/services/DigitalObjectManager.java
persistence/src/main/java/edu/unc/lib/dl/services/DigitalObjectManagerImpl.java
persistence/src/main/java/edu/unc/lib/dl/update/FedoraObjectUIPProcessor.java
persistence/src/main/java/edu/unc/lib/dl/util/ContainerContentsHelper.java
persistence/src/test/java/edu/unc/lib/dl/update/FedoraObjectUIPProcessorTest.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/ChangeObjectStateController.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/PublishRestController.java
services/src/main/webapp/WEB-INF/sword-servlet.xml

Performing access control checks in the application layer for user operations that involve updating relations in order to allow for processor and ingester roles to perform operations.

Processor permission fixes

---

access/src/main/webapp/WEB-INF/jsp/frontPage.jsp
static/front/front.css
static/front/peek.css

- Move the headline up over the "a peek into..." element, move the "peek" link to the bottom right.
- Add OA-specific instructions for deposit, and include a button that links directly to the OA form.

Add OA info to front page.

---

deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/main/resources/service-context.xml
metadata/src/main/java/edu/unc/lib/dl/util/RedisWorkerConstants.java
services/src/main/webapp/WEB-INF/sword-servlet.xml
static/templates/admin/statusMonitor/depositMonitorJobDetails.html
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/deposit/AbstractDepositHandler.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/deposit/AtomPubEntryDepositHandler.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/deposit/CDRMETSDepositHandler.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/deposit/DSPACEMETSDepositHandler.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/deposit/DepositHandler.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/deposit/SimpleObjectDepositHandler.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/managers/CollectionDepositManagerImpl.java
sword-server/src/test/java/edu/unc/lib/dl/cdr/sword/server/deposit/AtomPubEntryDepositHandlerTest.java
sword-server/src/test/java/edu/unc/lib/dl/cdr/sword/server/deposit/CDRMETSDepositHandlerTest.java
sword-server/src/test/java/edu/unc/lib/dl/cdr/sword/server/deposit/DSPACEMETSDepositHandlerTest.java

Added a separate "high" priority queue with its own worker pool, which is fed by deposit forms and simple object deposits presently.

Jumping line for form deposits

---

deposit/src/main/java/edu/unc/lib/deposit/CleanupDepositJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/CDRMETS2N3BagJob.java
deposit/src/test/java/edu/unc/lib/deposit/CleanupDepositJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJobTest.java
deposit/src/test/resources/cleanupDeposit/everything.n3
deposit/src/test/resources/cleanup_stages.json
metadata/src/main/java/edu/unc/lib/dl/util/ContentModelHelper.java
metadata/src/main/java/edu/unc/lib/dl/util/RedisWorkerConstants.java

Cleaning up bag and directory ingest folders
Removed METS staging folder cleanup

Trash bags

---

deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
metadata/src/main/java/edu/unc/lib/dl/reporting/ActivityMetricsClient.java

This looks like it fixes the issue. Incrementing seems to work fine. The set Jedis type doesn't work with the 3 parameter setup that hincrBy does.

Metrics fix

---

access-common/src/main/java/edu/unc/lib/dl/ui/controller/LorisContentController.java
access-common/src/main/java/edu/unc/lib/dl/ui/service/LorisContentService.java
static/js/public/src/JP2Viewer.js
static/plugins/Leaflet-IIIF/leaflet-iiif.js

Loris head requests should no longer spam the logs, partially per changes on David's end.
Proxies tile requests.

Loris head requests spam & proxying loris requests.

---

static/js/admin/src/IsSorted.js
static/js/admin/src/ResultTableView.js
static/js/admin/src/URLUtilities.js

Save sorting preferences in admin interface if a user sorts the results and then edits a record.
Fix issue with two drop down menus appearing if gear clicked in a result row.

Save sorting preferences

---

deposit/src/main/java/edu/unc/lib/deposit/PrepareResubmitJob.java
deposit/src/main/java/edu/unc/lib/deposit/fcrepo3/IngestDeposit.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/AbstractMETS2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/BioMedToN3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/CDRMETS2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/Proquest2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/Simple2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ValidateMODS.java
deposit/src/main/java/edu/unc/lib/deposit/validate/VirusScanJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
metadata/src/main/java/edu/unc/lib/dl/event/PremisLogger.java
metadata/src/main/java/edu/unc/lib/dl/rdf/Premis.java
metadata/src/main/java/edu/unc/lib/dl/util/PremisEventBuilder.java
metadata/src/test/java/edu/unc/lib/dl/event/PremisLoggerTest.java

Update deposit pipeline to use RDF Premis events.

Fcrepo4 mapping

---

access-common/src/main/resources/META-INF/resources/jsp/util/facetList.jsp
admin/src/main/java/edu/unc/lib/dl/admin/controller/GetFacetsController.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/SearchActionService.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/util/AbstractSettings.java
static/js/admin/src/SearchMenu.js

Get admin ui facet filters behaving correctly, when selected or expanded/collapsed.

Admin Filters

---

deposit/src/main/java/edu/unc/lib/deposit/validate/ValidateMODS.java

Fix issue with with normalization event being considered a validation

---

admin/src/main/java/edu/unc/lib/dl/admin/controller/ExportController.java

Removed an extra parenthesis that sneaked into my code yesterday.

remove extra parenthesis

---

admin/src/main/java/edu/unc/lib/dl/admin/controller/AbstractSwordController.java
admin/src/main/java/edu/unc/lib/dl/admin/controller/ExportController.java
admin/src/main/java/edu/unc/lib/dl/admin/controller/MODSController.java

Nearly all chars will now display in the CDR. I checked with Moira for signoff on the char that was causing her difficulty, namely, an e with a macron, which ironically this editor won't let me insert.

Fix character encoding

---

.gitignore
fcrepo-clients/src/main/java/edu/unc/lib/dl/event/FilePremisLogger.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/ContentObject.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/LdpContainerFactory.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/Repository.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObject.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectDataLoader.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactory.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryPathConstants.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/WorkObject.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/InvalidRelationshipException.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/LdpContainerFactoryIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactoryIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/WorkObjectIT.java
metadata/src/main/java/edu/unc/lib/dl/rdf/Cdr.java
metadata/src/main/java/edu/unc/lib/dl/util/ResourceType.java

Adds client and factory methods for creating Work objects.  Implemented general ContentObject ability to retrieve members for use by work objects.

Implement work object client

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestDepositRecordJob.java
deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/MakePCDMAIPsJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestDepositRecordJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/MakePCDMAIPsJobTest.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/event/FilePremisLogger.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/PIDs.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/UpdateDocTransformer.java

This is ready to review. I changed the IngestDepositRecordJob to handle multiple manifests, and I updated the class's unit test to ensure it handles cases where a Deposit Record is created, Manifests are added to it, and Premis Events are added to it.

Update ingest deposit record job

---

access-common/src/main/java/edu/unc/lib/dl/ui/util/AnalyticsTrackerUtil.java
access/src/main/webapp/WEB-INF/jsp/fullRecord.jsp
access/src/main/webapp/WEB-INF/jsp/googleAnalytics.jsp
access/src/main/webapp/WEB-INF/jsp/searchResults/resultsList.jsp
deposit/src/main/java/edu/unc/lib/deposit/normalize/Proquest2N3BagJob.java

Using new tracker and updates to parameters used in download event.  The download event may or may not work.  On QA it worked against the old tracker id but not the new one, but in the absence of other options I would like to try this in prod to see if it has the same issue.

Google analytics update

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/event/FilePremisLogger.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/event/PremisEventBuilder.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/event/RepositoryPremisLogger.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/Repository.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactory.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/event/FilePremisLoggerTest.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/event/RepositoryPremisLoggerIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/DepositRecordIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/RepositoryTest.java

Adds a unit test for the Repository class
Cleans up the API for the class a bit for consistency.

Repository client unit test

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/BinaryObject.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/BinaryObjectTest.java

This PR supersedes the one for add-unit-test-for-binary-object

Bin obj unit test

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/CollectionObject.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/Repository.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactory.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/CollectionObjectTest.java

Adds a new class and unit test for the fcrepo CollectionObject client. Updates Repository and RepositoryObjectFactory to handle the new type.

Collection object client

---

deposit/src/main/java/edu/unc/lib/deposit/normalize/VocabularyEnforcementJob.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/AbstractNormalizationJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/VocabularyEnforcementJobTest.java
metadata/src/main/java/edu/unc/lib/dl/rdf/CdrDeposit.java

Updates properties with those in the new namespace.

updates properties in VocabularyEnforcementJob and related unit tests

---

deposit/pom.xml
deposit/src/main/java/edu/unc/lib/deposit/normalize/BioMedToN3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/CDRMETSGraphExtractor.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/DirectoryToBagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/METSHelper.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/Proquest2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/Simple2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/VocabularyEnforcementJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositGraphUtils.java
deposit/src/main/resources/proquest-to-mods.xsl
deposit/src/test/java/edu/unc/lib/deposit/AbstractDepositJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/AbstractNormalizationJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/BioMedToN3BagJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/DirectoryToBagJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/Proquest2N3BagJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/Simple2N3BagJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/VocabularyEnforcementJobTest.java
deposit/src/test/resources/dspacemets-context.xml
fcrepo-clients/pom.xml
fcrepo-clients/src/main/java/edu/unc/lib/dl/fedora/ClientUtils.java
metadata/pom.xml
pom.xml
sword-server/pom.xml

Update properties in normalization jobs

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestDepositRecordJob.java
deposit/src/main/resources/fcrepo-clients-context.xml
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestDepositRecordJobTest.java
deposit/src/test/resources/spring-test/cdr-client-container.xml
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/ContentObject.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectDataLoader.java

Adds stubbed fcrepo4 access control utilities, updates the ingest content job, and updates ingest tests

fcrepo4 ingest content ACL stubbing

---

access-common/src/main/java/edu/unc/lib/dl/ui/access/StoreAccessLevelFilter.java
access-common/src/test/java/edu/unc/lib/dl/ui/util/AccessUtilTest.java
admin/src/main/java/edu/unc/lib/dl/admin/controller/BinCollectorController.java
fcrepo-cdr-fesl/src/main/java/edu/unc/lib/dl/security/AccessControlUtils.java
fcrepo-cdr-fesl/src/main/java/edu/unc/lib/dl/security/controller/AccessLookupController.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fedora/FedoraAccessControlServiceTest.java
security/src/main/java/edu/unc/lib/dl/acl/fcrepo3/ObjectAccessControlsBeanImpl.java
security/src/main/java/edu/unc/lib/dl/acl/util/UserRole.java
security/src/test/java/edu/unc/lib/dl/acl/util/ObjectAccessControlsBeanTest.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessControlFilter.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/indexing/DocumentIndexingPackageDataLoader.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessControlFilterTest.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/indexing/DocumentIndexingPackageDataLoaderTest.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/BriefObjectMetadataBean.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/tags/AccessRestrictionsTagProvider.java
solr-search/src/test/java/edu/unc/lib/dl/search/solr/tags/AccessRestrictionsTagProviderTest.java
sword-server/src/test/java/edu/unc/lib/dl/cdr/sword/managers/CollectionListManagerTest.java

Get things compiling again with changes to acl bean implementation

Fix ACL Bean references

---

access/src/main/webapp/WEB-INF/jsp/common/footer.jsp
access/src/main/webapp/WEB-INF/jsp/common/header.jsp
access/src/main/webapp/WEB-INF/jsp/frontPage.jsp
access/src/main/webapp/WEB-INF/jsp/studentPapers.jsp
access/src/main/webapp/WEB-INF/jsp/template/defaultTemplate.jsp
static/css/cdrui_styles.css
static/front/front.css
static/front/peek.js

Addressed accessibility issues on front page and student papers landing page

CDR 1703-1704 accessibility issues

---

deposit/src/main/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJob.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/BinaryObject.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetFullTextFilter.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetFullTextFilterTest.java

@bbpennel @lfarrell this should be ready to look at :)

Cdr 1786 update setfulltextfilter

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/acl/fcrepo4/InheritedAclFactory.java
metadata/src/main/java/edu/unc/lib/dl/rdf/Cdr.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessStatusFilter.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetContentStatusFilter.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetStatusTagsFilter.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessStatusFilterTest.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetContentStatusFilterTest.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetStatusTagsFilterTest.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/IndexDocumentBean.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/tags/DefaultObjectTagProvider.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/util/FacetConstants.java

@ben, this is ready for review!

Status tags

---

solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetFullTextFilter.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetFullTextFilterTest.java

@ben, here’s that PR for the error-logging bug

removes error logging in SetFullTextFilter

---

services/src/main/webapp/WEB-INF/sword-context.xml
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/managers/MediaResourceManagerImpl.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/managers/ServiceDocumentManagerImpl.java
sword-server/src/main/resources/edu/unc/lib/dl/cdr/sword/server/managers/immediateChildrenPaged.sparql
sword-server/src/main/resources/edu/unc/lib/dl/cdr/sword/server/managers/immediateContainerChildren.sparql

Fixes issues related to retrieving the CDR's service document

Sword service doc fix

---

pom.xml

Removed leftover staging areas submodule folder (it had already been removed from the list of submodules, but not cleaned up)

F4 remove staging areas

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestDepositRecordJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/CDRMETSGraphExtractor.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ValidateFileAvailabilityJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ValidateMODS.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJobTest.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/ContentRootObject.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/PIDs.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectCacheLoader.java
metadata/src/main/java/edu/unc/lib/dl/util/DepositConstants.java
metadata/src/main/resources/edu/unc/lib/dl/schematron/simple_mets_profile.sch
security/src/main/java/edu/unc/lib/dl/acl/util/Permission.java
security/src/main/java/edu/unc/lib/dl/acl/util/UserRole.java

Changes to deposit and related modules to get sample packages to deposit on BES.

Cdr 1896 Getting sample packages depositing

---

deposit/src/main/java/edu/unc/lib/deposit/normalize/BioMedToN3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/CDRMETSGraphExtractor.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/DirectoryToBagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/Simple2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/staging/StagingPolicyManager.java
deposit/src/main/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJob.java
deposit/src/main/java/edu/unc/lib/deposit/validate/PackageIntegrityCheckJob.java
deposit/src/main/webapp/WEB-INF/service-context.xml
deposit/src/test/java/edu/unc/lib/deposit/normalize/DirectoryToBagJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/staging/StagingPolicyManagerTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJobTest.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactory.java
pom.xml

Addresses issues related to getting file cleanup working, including leftover file handles, clunky error handling, relative staging paths, and consolidates checksum calculation and handling.

Cdr 1898 deposit cleanup

---

access/src/main/java/edu/unc/lib/dl/ui/controller/AdvancedSearchFormController.java

Order display correctly

---

fcrepo-clients/src/test/resources/spring-test/cdr-client-container.xml
services-camel/src/test/resources/spring-test/cdr-client-container.xml

Pid minter Take Two Fixes

---

access/pom.xml
access/src/main/java/edu/unc/lib/dl/ui/controller/SearchActionController.java
access/src/main/webapp/WEB-INF/access-fedora-context.xml
access/src/main/webapp/WEB-INF/service-context.xml
access/src/main/webapp/WEB-INF/solr-search-context.xml
access/src/main/webapp/WEB-INF/web.xml

The main page now loads. It ignores solr at this point.

Deploy access

---

access-common/pom.xml
access/src/main/webapp/WEB-INF/solr-search-context.xml
admin/pom.xml
admin/src/main/java/edu/unc/lib/dl/admin/controller/IngestSourceController.java
admin/src/main/java/edu/unc/lib/dl/admin/controller/RunEnhancementsController.java
admin/src/main/webapp/WEB-INF/access-fedora-context.xml
admin/src/test/resources/server.properties
etc/server.properties
pom.xml
services/src/main/webapp/WEB-INF/access-fedora-context.xml
solr-search/pom.xml

Removes dependencies which caused version conflicts when starting admin app.
Reduces size of admin.war from 120mb to 40mb.
Fixes a few configuration settings.

F4 cleanup admin dependencies

---

access/src/main/resources/recordTransformations/modsToFullRecord.xsl

Don't know if this is too specific, but it works for the provided use case.

Link out to RLA site codes

---

.travis.yml
access-common/src/main/java/edu/unc/lib/dl/ui/util/SerializationUtil.java
access-common/src/main/java/edu/unc/lib/dl/ui/util/StringFormatUtil.java
access-common/src/test/java/edu/unc/lib/dl/ui/service/AbstractSolrQueryLayerTest.java
access-common/src/test/java/edu/unc/lib/dl/ui/service/ChildrenCountTest.java
access-common/src/test/java/edu/unc/lib/dl/ui/service/StructureQueryTest.java
access-common/src/test/java/edu/unc/lib/dl/ui/util/SerializationUtilTest.java
access-common/src/test/java/edu/unc/lib/dl/ui/util/StringFormatUtilTest.java
access-common/src/test/resources/config/access/conf/schema.xml
access-common/src/test/resources/config/access/conf/solrconfig.xml
access-common/src/test/resources/config/access/core.properties
access-common/src/test/resources/config/solr.xml
persistence/src/test/java/edu/unc/lib/dl/update/AccessControlUIPFilterTest.java
persistence/src/test/java/edu/unc/lib/dl/update/FedoraObjectUIPProcessorTest.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/solr/CdrEventToSolrUpdateProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/solrUpdate/SolrUpdateProcessor.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/solr/CdrEventToSolrUpdateProcessorTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/solrUpdate/SolrUpdateProcessorTest.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/SearchStateFactory.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/util/SearchSettings.java
sword-server/src/test/java/edu/unc/lib/dl/cdr/sword/managers/CollectionListManagerTest.java
sword-server/src/test/resources/service-context.xml

Fixes some unit tests that were not passing, removes others which are no longer applicable, and adds some additional tests which were missing

Cdr 2092 - Get CI passing

---

solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetRecordDatesFilter.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/indexing/SolrUpdateDriver.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetRecordDatesFilterTest.java

Falls back to getting required date fields from foxml if mulgara is missing them

Handle missing lastModifiedDate during indexing

---

access-common/src/main/java/edu/unc/lib/dl/ui/service/SolrQueryLayerService.java
access-common/src/test/java/edu/unc/lib/dl/ui/service/NeighborQueryTest.java

Adds test for neighbor query
Refactors neighbor query to be faster for large numbers of siblings.

Bxc-2164 slow neighbors

---

access/src/main/webapp/WEB-INF/access-fedora-context.xml
deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml
deposit/src/main/webapp/WEB-INF/fcrepo-clients-context.xml
deposit/src/test/resources/spring-test/cdr-client-container.xml
etc/deposit.properties
etc/server.properties
etc/services-camel.properties
fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectCacheLoader.java
services-camel/src/main/resources/config.properties
services-camel/src/main/webapp/WEB-INF/service-context.xml
services-camel/src/test/resources/cdr-event-routing-it-config.properties
services-camel/src/test/resources/config.properties
services-camel/src/test/resources/spring-test/cdr-client-container.xml
services-camel/src/test/resources/triples-reindexing-it-config.properties
services/src/main/webapp/WEB-INF/access-fedora-context.xml

Adds missing properties, cleans up some unused bean creation, resolves missing dependency and expands error message.

VM properties and cleanup

---

admin/src/main/webapp/WEB-INF/service-context.xml
deposit/src/main/webapp/WEB-INF/service-context.xml
persistence/pom.xml
pom.xml
services/src/main/webapp/WEB-INF/service-context.xml
services/src/main/webapp/WEB-INF/sword-context.xml
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/deposit/AbstractDepositHandler.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/deposit/CDRMETSDepositHandler.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/managers/AbstractFedoraManager.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/managers/CollectionDepositManagerImpl.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/managers/CollectionListManagerImpl.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/managers/ContainerManagerImpl.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/managers/ServiceDocumentManagerImpl.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/managers/StatementManagerImpl.java
sword-server/src/main/java/edu/unc/lib/dl/cdr/sword/server/util/DepositReportingUtil.java

Update SWORD to work with current ACL model.
Remove dead code and components of sword implementation that we are not using currently that have not been updated (such as updates to objects)

Bxc 2230 - sword deposits

---

persistence/src/main/java/edu/unc/lib/dl/persist/services/delete/MarkForDeletionJob.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/delete/MarkForDeletionService.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/delete/MarkForDeletionJobTest.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/MarkForDeletionController.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/MarkForDeletionIT.java
static/css/admin/admin_forms.css
static/js/admin/src/AbstractForm.js
static/js/admin/src/DeleteForm.js
static/js/admin/src/ResultObjectActionMenu.js
static/js/admin/src/ResultTableActionMenu.js
static/js/admin/src/ResultView.js
static/js/admin/src/action/AbstractBatchAction.js
static/js/admin/src/action/AjaxCallbackAction.js
static/js/admin/src/action/DeleteBatchAction.js
static/js/admin/src/action/DeleteResultAction.js
static/js/admin/src/action/OpenDeleteBatchAction.js
static/templates/admin/deleteForm.html

* Requires that a message describing the reason for one or more objects being marked for deletion, which will be added to the PREMIS event.
* Adds a simple form and actions to accommodate providing this message.

Bxc 2208 - Provide reason for deletion

---

access-common/pom.xml
access/pom.xml
admin/pom.xml
deposit/pom.xml
fcrepo-cdr-fesl/pom.xml
fcrepo-clients/pom.xml
fcrepo-irods-storage/pom.xml
fcrepo-irods-storage/src/main/java/fedorax/server/module/storage/lowlevel/irods/IrodsDBPathRegistry.java
metadata/pom.xml
persistence/pom.xml
pom.xml
security/pom.xml
security/src/main/java/edu/unc/lib/dl/acl/filter/GroupsToHttpHeaderInterceptor.java
services-worker/pom.xml
services/pom.xml
solr-ingest/pom.xml
solr-search/pom.xml
sword-server/pom.xml

Consolidates maven dependencies to be more centrally managed and updates versions.

Bxc-2278 - Update maven dependencies (Master branch)

---

admin/src/main/java/edu/unc/lib/dl/admin/collect/IngestSourceManager.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJob.java
pom.xml

Updates to bagit 5.2.0
IngestSourceManager is only sort of updated, since it has not been migrated for bxc5 yet. BagIt2N3BagJob is tested and updated with the new client.

BXC2284 - Update Bagit

---

access-common/src/main/java/edu/unc/lib/dl/ui/util/SerializationUtil.java
static/js/public/fullRecord.js

https://jira.lib.unc.edu/browse/BXC-2356

Add default thumbnails

---

access/src/main/java/edu/unc/lib/dl/ui/controller/FullRecordController.java
access/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/ChildrenCountService.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/StructureQueryService.java
solr-search/src/test/java/edu/unc/lib/dl/search/solr/service/ChildrenCountServiceIT.java

https://jira.lib.unc.edu/browse/BXC-2360

Populate children counts for works in full record

---

access/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
admin/src/main/webapp/WEB-INF/access-fedora-context.xml
static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss
static/js/public/fullRecord.js
static/plugins/DataTables/datatables.min.js

https://jira.lib.unc.edu/browse/BXC-2361

Style updates for table view of works

---

access/src/main/webapp/WEB-INF/html/headElements.html
static/maintenance.html
static/service-unavailable.html

https://jira.lib.unc.edu/browse/BXC-2362

Add meta tag for Bing site auth

---

access/src/main/resources/recordTransformations/modsToFullRecord.xsl

https://jira.lib.unc.edu/browse/BXC-2303

Fix spelling mistake

---

access/src/main/webapp/WEB-INF/jsp/frontPage.jsp
access/src/main/webapp/WEB-INF/web.xml
admin/src/main/java/edu/unc/lib/dl/admin/controller/ExportXMLController.java
deposit/src/main/resources/completed_html.txt
deposit/src/main/resources/completed_text.txt
deposit/src/main/resources/failed_html.txt
deposit/src/main/resources/failed_text.txt

https://jira.lib.unc.edu/browse/BXC-2378
https://jira.lib.unc.edu/browse/LIB-11417

Change CDR references to DCR

---

access/src/main/java/edu/unc/lib/dl/ui/controller/FullRecordController.java
access/src/main/webapp/WEB-INF/jsp/fullRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/collectionRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/folderRecord.jsp
static/js/vue-cdr-access/src/components/browseDisplay.vue
static/js/vue-cdr-access/src/components/browseImages.vue
static/js/vue-cdr-access/src/components/modalMetadata.vue

https://jira.lib.unc.edu/browse/BXC-2389

Folder browse page

---

solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/RoleGroupFacet.java

https://jira.lib.unc.edu/browse/BXC-2397
Gets the facet panel to display, but it is not currently functional due to the redesign of the search page in the access app. We'll need to work out facet expectations and possibly split the rendering up for each application if they are diverging.

BXC-2397 - Get admin filters panel to display facets

---

admin/src/main/webapp/WEB-INF/jsp/common/header.jsp

https://jira.lib.unc.edu/browse/BXC-2412

Update links for box-c 5

---

admin/src/main/java/edu/unc/lib/dl/admin/controller/ExportController.java

* https://jira.lib.unc.edu/browse/BXC-2399

Export object and children in csv format

---

static/js/vue-cdr-access/src/components/modalMetadata.vue
static/js/vue-cdr-access/tests/unit/modalMetadata.spec.js

https://jira.lib.unc.edu/browse/BXC-2433

Retrieve metadata on click instead of page load

---

static/js/vue-cdr-access/src/components/browseSearch.vue
static/js/vue-cdr-access/tests/unit/browseSearch.spec.js

https://jira.lib.unc.edu/browse/BXC-2434
* Trigger search if enter key pressed
* Don't clear search after enter/search btn triggered

Make browse search more usable

---

persistence/src/main/java/edu/unc/lib/persist/services/EmailHandler.java
services/src/main/java/edu/unc/lib/dl/cdr/services/processing/XMLExportJob.java
services/src/main/java/edu/unc/lib/dl/cdr/services/processing/XMLImportService.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/ExportXMLController.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/ImportXMLController.java
services/src/main/webapp/WEB-INF/service-context.xml
static/js/admin/src/action/ExportMetadataXMLBatchAction.js

https://jira.lib.unc.edu/browse/BXC-2405
* Set correct path to controller from XML export javascript
* Refactor exception handling for xml import and export, plus resolve warnings
* Add missing dependencies required for sending emails
* Remove unused params

BXC-2405 - MODS Export

---

static/js/admin/src/action/ReindexResultAction.js

https://jira.lib.unc.edu/browse/BXC-2406

Fix error causing admin ui not to be able to send reindexing requests

---

static/css/admin/cdradmin.css
static/css/admin/jquery.xmleditor.css

https://jira.lib.unc.edu/browse/BXC-2400
https://jira.lib.unc.edu/browse/BXC-2394

Fix display of edit description modal

---

access-common/src/main/java/edu/unc/lib/dl/ui/util/SerializationUtil.java
access-common/src/test/java/edu/unc/lib/dl/ui/util/SerializationUtilTest.java
static/js/vue-cdr-access/src/components/browseDisplay.vue

https://jira.lib.unc.edu/browse/BXC-2393

Use url base with record id to generate url

---

static/js/admin/src/action/AjaxCallbackAction.js
static/js/admin/src/action/DeleteResultAction.js
static/js/admin/src/action/DestroyResultAction.js
static/js/admin/src/action/PublishAction.js

https://jira.lib.unc.edu/browse/BXC-2407

Update work method so actions can submit data

---

services-camel/src/main/java/edu/unc/lib/dl/services/camel/enhancements/EnhancementRouter.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/enhancements/EnhancementRouterIT.java

https://jira.lib.unc.edu/browse/BXC-2435

BXC-2435 - Skip enhancements of fcr:metadata

---

access-common/src/main/resources/META-INF/resources/jsp/util/pathTrail.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/navigationBar.jsp
access/src/main/webapp/WEB-INF/jsp/searchResults.jsp
static/css/cdr-ui.css
static/css/cdrui_styles.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss

https://jira.lib.unc.edu/browse/BXC-2338

Update the way breadcrumbs are laid out

---

static/js/vue-cdr-access/tests/unit/browseDisplay.spec.js
static/js/vue-cdr-access/tests/unit/modalMetadata.spec.js

Using moxios without passing in 'done' results in this issue.

Update tests so they don't always pass regardless of data.

---

static/js/admin/src/ResultView.js

https://jira.lib.unc.edu/browse/BXC-2465

Update public link of admin site record pages

---

static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss
static/js/vue-cdr-access/src/components/browseDisplay.vue
static/js/vue-cdr-access/src/components/browseSort.vue
static/js/vue-cdr-access/src/components/viewType.vue
static/js/vue-cdr-access/src/components/worksOnly.vue
static/js/vue-cdr-access/src/mixins/routeUtils.js
static/js/vue-cdr-access/tests/unit/browseDisplay.spec.js
static/js/vue-cdr-access/tests/unit/routeUtils.spec.js
static/js/vue-cdr-access/tests/unit/viewType.spec.js
static/js/vue-cdr-access/tests/unit/worksOnly.spec.js

https://jira.lib.unc.edu/browse/BXC-2480
List view currently works the same as the previous structure view

Works only option and list v browse view

---

persistence/src/main/java/edu/unc/lib/dl/persist/services/acl/PatronAccessDetails.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/RetrievePatronRolesIT.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/UpdatePatronAccessIT.java
static/js/admin/src/ResultObjectActionMenu.js
static/js/admin/vue-permissions-editor/package-lock.json
static/js/admin/vue-permissions-editor/package.json
static/js/admin/vue-permissions-editor/src/assets/common-styles.css
static/js/admin/vue-permissions-editor/src/components/embargo.vue
static/js/admin/vue-permissions-editor/src/components/modalEditor.vue
static/js/admin/vue-permissions-editor/src/components/patronDisplayRow.vue
static/js/admin/vue-permissions-editor/src/components/patronRoles.vue
static/js/admin/vue-permissions-editor/src/components/staffRoles.vue
static/js/admin/vue-permissions-editor/src/mixins/displayModal.js
static/js/admin/vue-permissions-editor/src/mixins/patronHelpers.js
static/js/admin/vue-permissions-editor/tests/unit/embargo.spec.js
static/js/admin/vue-permissions-editor/tests/unit/patronDisplayRow.spec.js
static/js/admin/vue-permissions-editor/tests/unit/patronRoles.spec.js

https://jira.lib.unc.edu/browse/BXC-2475

Implement patron access control interface

---

access/src/main/webapp/WEB-INF/jsp/collectionBrowse.jsp
access/src/main/webapp/WEB-INF/jsp/searchResults.jsp

https://jira.lib.unc.edu/browse/BXC-2486

Update search results text

---

static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss

https://jira.lib.unc.edu/browse/BXC-2491

Adjust thumbnail placement

---

static/js/admin/src/ResultObjectActionMenu.js

https://jira.lib.unc.edu/browse/BXC-2495

Set conditions for displaying permission editors

---

static/maintenance.html
static/service-unavailable.html

https://jira.lib.unc.edu/browse/BXC-2497

Update link locations

---

persistence/src/main/java/edu/unc/lib/dl/persist/services/edit/EditTitleService.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/edit/EditTitleServiceTest.java
persistence/src/test/resources/mods/valid-mods.xml

* https://jira.lib.unc.edu/browse/BXC-2440

title edit

---

access/src/main/java/edu/unc/lib/dl/ui/controller/FullRecordController.java
access/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp

https://jira.lib.unc.edu/browse/BXC-2501

Fix display of jp2 for aggregate works.

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
metadata/src/main/java/edu/unc/lib/dl/util/DepositStatusFactory.java
static/js/admin/src/statusMonitor/DepositMonitor.js

https://jira.lib.unc.edu/browse/BXC-2396

Fix issue with ingest progress showing "undefined"

---

services/src/main/java/edu/unc/lib/dl/cdr/services/processing/AddContainerService.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/AddContainerController.java
services/src/main/webapp/WEB-INF/service-context.xml
services/src/test/java/edu/unc/lib/dl/cdr/services/processing/AddContainerServiceTest.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/AddContainerIT.java
services/src/test/resources/add-container-it-servlet.xml
static/js/admin/src/CreateContainerForm.js
static/templates/admin/createContainerForm.html

https://jira.lib.unc.edu/browse/BXC-2502

Allow staff only access when creating new collections or folders

---

services-camel/src/main/webapp/WEB-INF/solr-indexing-context.xml
services-camel/src/test/resources/solr-indexing-it-context.xml

https://jira.lib.unc.edu/browse/BXC-2504

Add set access filter

---

static/js/admin/vue-permissions-editor/package-lock.json
static/js/vue-cdr-access/package-lock.json

https://jira.lib.unc.edu/browse/BXC-2517

Fix non-breaking security issues

---

services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/EditTitleController.java
services/src/main/webapp/WEB-INF/service-context.xml
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/EditTitleIT.java
services/src/test/resources/edit-title-it-servlet.xml
static/js/admin/src/EditTitleForm.js
static/js/admin/src/ResultObjectActionMenu.js
static/templates/admin/editTitleForm.html

https://jira.lib.unc.edu/browse/BXC-2430

Implement user interface to edit work titles

---

migration-util/README.md
migration-util/pom.xml
migration-util/src/main/java/edu/unc/lib/dcr/migration/BannerUtility.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/MigrationCLI.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/MigrationConstants.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/PathIndexCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/paths/PathIndex.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/paths/PathIndexingService.java
migration-util/src/main/resources/create_path_index.sql
migration-util/src/test/java/edu/unc/lib/dcr/migration/paths/PathIndexingServiceTest.java

https://jira.lib.unc.edu/browse/BXC-2525
* Adds a service which can take pids and file types, and gives back the path on disk where it is stored.
* the implementation is an embedded h2 database
* Adds a CLI for populating and querying the index of files.

BXC-2525 - Path service

---

access-common/src/main/resources/META-INF/resources/jsp/util/facetList.jsp
static/css/cdr_common.css

https://jira.lib.unc.edu/browse/BXC-2508

Fix facets on admin site

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/MigrationCLI.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/TransformContentCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerManager.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/DepositDirectoryManager.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/fcrepo3/FoxmlDocumentHelpers.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/fcrepo3/FoxmlDocumentBuilder.java

https://jira.lib.unc.edu/browse/BXC-2528
* Extracts and makes most recent MODS version available as part of generated content deposit.
* Adds a utility for adding files to deposits

BXC-2528 - Extract and populate MODS for deposit

---

static/js/admin/src/ResultObjectActionMenu.js
static/js/admin/vue-permissions-editor/package-lock.json
static/js/admin/vue-permissions-editor/package.json
static/js/admin/vue-permissions-editor/src/components/embargo.vue
static/js/admin/vue-permissions-editor/src/components/patronDisplayRow.vue
static/js/admin/vue-permissions-editor/src/components/patronRoles.vue
static/js/admin/vue-permissions-editor/tests/unit/patronDisplayRow.spec.js
static/js/admin/vue-permissions-editor/tests/unit/patronRoles.spec.js

https://jira.lib.unc.edu/browse/BXC-2522

Patron permissions "winning" permission bug

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/util/VocabularyHelperManager.java

https://jira.lib.unc.edu/browse/BXC-2578
* pulls a fresh copy of the RELS-EXT before retrying the update in the case of an optimistic lock failure, since it was constantly submitting the same outdated modification timestamp when retrying.
* added a max number of retries

BXC-2578 - Fix concurrency issue with updateInvalidTermsRelations

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/TransformContentCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerManager.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/DepositDirectoryManager.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java

https://jira.lib.unc.edu/browse/BXC-2531
* Existing PREMIS event logs migrated during content object migration

BXC-2531 - Migration of PREMIS with Content Objects

---

persistence/src/main/java/edu/unc/lib/dl/persist/services/edit/EditTitleService.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/edit/EditTitleServiceTest.java
services/src/main/webapp/WEB-INF/service-context.xml
services/src/test/resources/edit-title-it-servlet.xml

https://jira.lib.unc.edu/browse/BXC-2575
* Triggers indexing of objects after their title is edited

BXC-2575 - Edit title reindex

---

admin/src/main/webapp/WEB-INF/web.xml

Relates to https://jira.lib.unc.edu/browse/IMS-1997

IMS-1997 - Spring ordering

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestDepositRecordJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestDepositRecordJobIT.java

https://jira.lib.unc.edu/browse/BXC-2520
* Add package format to ingestion event for deposit records 
NOTE: Needs to be rebased after other premis PRs are merged

BXC-2520 - Include packaging info in Deposit record ingestion event

---

static/js/admin/src/AddMenu.js

https://jira.lib.unc.edu/browse/BXC-2597

Remove ingestPackage option

---

access/src/main/webapp/WEB-INF/jsp/common/headerSmall.jsp
static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_homepage.scss

https://jira.lib.unc.edu/browse/BXC-2586

Increase contrast for sub-menu items

---

static/js/admin/src/ResultObjectActionMenu.js

https://jira.lib.unc.edu/browse/BXC-2613

Enable destroy action for admins when objects are marked for deletion

---

static/js/admin/src/ResultView.js

https://jira.lib.unc.edu/browse/BXC-2599

Remove edit type option

---

access/src/main/webapp/WEB-INF/jsp/advancedSearch.jsp
static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss

https://jira.lib.unc.edu/browse/BXC-2598

Reduce font sizing on adv search page

---

static/js/admin/src/ResultObject.js

https://jira.lib.unc.edu/browse/BXC-2605

Fix display of file size and other metadata

---

static/js/admin/editDescription.js

https://jira.lib.unc.edu/browse/BXC-2568

Return the parentId.id so mods editor will close on cancel

---

services/src/main/webapp/WEB-INF/service-context.xml

https://jira.lib.unc.edu/browse/BXC-2610

BXC-2610 - Up max file size for uploads

---

static/js/vue-cdr-access/src/components/facets.vue

https://jira.lib.unc.edu/browse/BXC-2595

Clean up facet display

---

static/js/admin/editDescription.js

https://jira.lib.unc.edu/browse/BXC-2603

Only show view file option for files and works

---

metadata/src/main/java/edu/unc/lib/dl/validation/MODSValidator.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/UpdateDescriptionController.java

https://jira.lib.unc.edu/browse/BXC-2603

Improve error message for mods editor

---

static/js/admin/src/ResultObjectActionMenu.js

https://jira.lib.unc.edu/browse/BXC-2617

Fix form pop up issue when restoring an object marked for deletion

---

static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss
static/js/vue-cdr-access/src/components/browseDisplay.vue

https://jira.lib.unc.edu/browse/BXC-2567

Wrap long titles

---

access/src/main/java/edu/unc/lib/dl/ui/controller/FullRecordController.java
access/src/main/webapp/WEB-INF/jsp/common/thumbnail.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/adminUnit.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/collectionRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/fileRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/folderRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/neighborList.jsp
static/css/cdr-ui.css
static/css/cdrui_styles.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss
static/js/public/fullRecord.js
static/js/vue-cdr-access/src/components/browseDisplay.vue
static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/src/components/listDisplay.vue
static/js/vue-cdr-access/src/components/worksOnly.vue
static/js/vue-cdr-access/src/mixins/displayUtils.js

https://jira.lib.unc.edu/browse/BXC-2563

Update display of items marked for deletion in public UI

---

metadata/src/main/java/edu/unc/lib/dl/rdf/Premis.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/delete/MarkForDeletionJob.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/delete/RestoreDeletedJob.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/delete/MarkForDeletionJobTest.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/delete/RestoreDeletedJobTest.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/MarkForDeletionIT.java

https://jira.lib.unc.edu/browse/BXC-2619

Change marked for deletion premis event

---

deposit/src/main/java/edu/unc/lib/deposit/normalize/AbstractMETS2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/CDRMETS2N3BagJob.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/CDRMETS2N3BagJobTest.java
metadata/src/main/java/edu/unc/lib/dl/rdf/Premis.java

https://jira.lib.unc.edu/browse/BXC-2621

Change event from Normalization to Accession for PID creation

---

static/css/admin/jquery.xmleditor.css

https://jira.lib.unc.edu/browse/BXC-2602
https://jira.lib.unc.edu/browse/BXC-2604

Xmleditor display fixes

---

static/css/admin/jquery.xmleditor.css

https://jira.lib.unc.edu/browse/BXC-2602
https://jira.lib.unc.edu/browse/BXC-2604

Xmleditor  display fixes - master

---

access/src/main/java/edu/unc/lib/dl/ui/controller/FedoraContentController.java

https://jira.lib.unc.edu/browse/BXC-2519

Check if download is a work. If so, use its primary object's PID

---

access/src/main/java/edu/unc/lib/dl/ui/controller/FullRecordController.java

https://jira.lib.unc.edu/browse/BXC-2627
* Removes second, inaccurate setting of child count

BXC-2627 - Fix child count next to collection title

---

static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss
static/js/vue-cdr-access/src/components/listDisplay.vue

https://jira.lib.unc.edu/browse/BXC-2566

Fix button focus color

---

solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetDescriptiveMetadataFilter.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetDescriptiveMetadataFilterTest.java
static/js/xmleditor/jquery.xmleditor.js

https://jira.lib.unc.edu/browse/BXC-2625

Add message to confirm that user wants to update MODS record without adding a title

---

static/js/vue-cdr-access/src/components/browseSearch.vue
static/js/vue-cdr-access/tests/unit/browseSearch.spec.js

* Add clear search link and test
* Reorganize tests a bit
https://jira.lib.unc.edu/browse/BXC-2571

Add clear search link

---

static/js/admin/src/ResultObjectActionMenu.js

https://jira.lib.unc.edu/browse/BXC-2646

Add option for admin units to have display thumbnails

---

access/src/main/webapp/WEB-INF/jsp/fullRecord/collectionRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/folderRecord.jsp
static/css/admin/search_results.css
static/css/cdr-homepage.css
static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss
static/js/vue-cdr-access/src/components/listDisplay.vue
static/templates/admin/collector/binList.html
static/templates/admin/resultEntry.html
static/templates/admin/trashResultEntry.html

https://jira.lib.unc.edu/browse/BXC-2643

Style counts as badge

---

services/src/main/java/edu/unc/lib/dl/cdr/services/processing/ImportThumbnailService.java

Depends on https://gitlab.lib.unc.edu/cdr/boxc-ansible/-/merge_requests/49

Remove creation of sourceImages directory. Set in ansible.

---

metadata/src/main/java/edu/unc/lib/dl/util/SoftwareAgentConstants.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/PathIndexCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/TransformContentCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/DepositRecordTransformer.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/paths/PathIndex.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/deposit/AbstractDepositRecordTransformationIT.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/deposit/DepositRecordTransformerIT.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/premis/TestPremisEventHelpers.java

https://jira.lib.unc.edu/browse/BXC-2640
* Adds migration events to content and deposit records during transformation

BXC-2640 - Migration event

---

access/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss
static/js/public/fullRecord.js

https://jira.lib.unc.edu/browse/BXC-2589

Remove "listen" button and style player a bit.

---

static/js/vue-cdr-access/src/components/facets.vue
static/js/vue-cdr-access/tests/unit/facets.spec.js

https://jira.lib.unc.edu/browse/BXC-2644

Remove facet checkboxes

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/RegisterToLongleafJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml

https://jira.lib.unc.edu/browse/BXC-2425
* Enables deposit job
* Fail job is registration fails

BXC-2425 - Enable longleaf deposit job

---

spoof/src/main/webapp/WEB-INF/jsp/spoof.jsp

https://jira.lib.unc.edu/browse/BXC-2648

Remove unused groups

---

static/js/admin/editDescription.js

https://jira.lib.unc.edu/browse/BXC-2630

Add link to MODS history

---

static/js/admin/src/RemoteStateChangeMonitor.js

https://jira.lib.unc.edu/browse/BXC-2614

Consider any admin ui work done if an error is returned

---

persistence/src/main/java/edu/unc/lib/dl/persist/services/edit/EditFilenameService.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/edit/EditFilenameServiceTest.java

https://jira.lib.unc.edu/browse/BXC-2632

Update dc:title on fileObject

---

access/src/main/webapp/WEB-INF/jsp/fullRecord/fileRecord.jsp

https://jira.lib.unc.edu/browse/BXC-2573

Have view button display on all file pages

---

static/css/cdrui_styles.css

https://jira.lib.unc.edu/browse/BXC-2562

Retain original ratio for images

---

static/js/vue-cdr-access/src/components/browseSort.vue
static/js/vue-cdr-access/tests/unit/browseSort.spec.js

https://jira.lib.unc.edu/browse/BXC-2659

Keep sort type displayed

---

access-common/src/main/java/edu/unc/lib/dl/ui/controller/LorisContentController.java
static/js/public/src/JP2Viewer.js

https://jira.lib.unc.edu/browse/BXC-2657

Allow images to get through access filter

---

services/src/main/java/edu/unc/lib/dl/cdr/services/rest/DepositController.java
static/templates/admin/statusMonitor/depositMonitorJobDetails.html

https://jira.lib.unc.edu/browse/BXC-2653

Allow admins to pause/resume deposits

---

static/js/admin/src/ResultObjectActionMenu.js

https://jira.lib.unc.edu/browse/BXC-2658

Add link to view FITS output

---

static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss
static/maintenance.html
static/service-unavailable.html

https://jira.lib.unc.edu/browse/BXC-2615

Fix link contrast and broken header image

---

persistence/src/main/java/edu/unc/lib/dl/persist/services/destroy/DestroyObjectsJob.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/destroy/DestroyObjectsJobIT.java

https://jira.lib.unc.edu/browse/BXC-2664

Add premis event to parent when child objects destroyed

---

persistence/src/main/java/edu/unc/lib/dl/persist/services/move/MoveObjectsJob.java

https://jira.lib.unc.edu/browse/BXC-2667

Add premis event if an object is moved between admin units

---

static/css/admin/admin_forms.css
static/js/admin/src/AbstractFileUploadForm.js
static/templates/admin/addFileForm.html

https://jira.lib.unc.edu/browse/BXC-2620

Add note about max file size and throw an error if file is larger than the max allowed

---

static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss

https://jira.lib.unc.edu/browse/BXC-2685

Fix color of deleted text and controls

---

static/js/admin/vue-permissions-editor/src/components/patronDisplayRow.vue
static/js/admin/vue-permissions-editor/src/components/patronRoles.vue
static/js/admin/vue-permissions-editor/tests/unit/patronDisplayRow.spec.js
static/js/admin/vue-permissions-editor/tests/unit/patronRoles.spec.js

https://jira.lib.unc.edu/browse/BXC-2675

Fix issues with display showing the wrong user prinicipal in some situations

---

solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessControlFilter.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessStatusFilter.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetContentStatusFilter.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetStatusTagsFilter.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessStatusFilterTest.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetContentStatusFilterTest.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetStatusTagsFilterTest.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/util/FacetConstants.java
static/js/admin/src/ResultObject.js
static/js/vue-cdr-access/src/mixins/displayUtils.js
static/templates/admin/resultEntry.html

* Filter and display tags
* Remove unpublished tag
Supersedes #991
https://jira.lib.unc.edu/browse/BXC-2226

Filter and display tags

---

static/js/admin/src/MoveDropLocation.js

https://jira.lib.unc.edu/browse/BXC-2666

Warn user if moving objects between admin units

---

static/js/admin/src/ResultObject.js

https://jira.lib.unc.edu/browse/BXC-2693

Fix issue with tags having incorrect dashed output

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ACLTransformationHelpers.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ACLTransformationHelpersTest.java

https://jira.lib.unc.edu/browse/BXC-2691

Objects with embargoes failing migration

---

static/css/admin/search_results.css
static/js/admin/src/MoveDropLocation.js
static/js/admin/src/ResultTableView.js
static/templates/admin/resultEntry.html
static/templates/structureEntry.html

https://jira.lib.unc.edu/browse/BXC-2670

Improve UI for illegal move operations

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactory.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactoryIT.java

https://jira.lib.unc.edu/browse/BXC-2696

Remove charset, ingest fails otherwise

---

services-camel/src/main/java/edu/unc/lib/dl/services/camel/longleaf/RegisterToLongleafProcessor.java

https://jira.lib.unc.edu/browse/BXC-2695
* Adds metrics for longleaf registration

BXC-2695 - Add timer and batch size metrics trackers

---

static/js/public/fullRecord.js
static/js/vue-cdr-access/src/mixins/displayUtils.js

https://jira.lib.unc.edu/browse/BXC-2662

Check for "Public Access" and assume staff only if no status is returned

---

access/src/main/webapp/WEB-INF/jsp/common/footer.jsp

https://jira.lib.unc.edu/browse/BXC-2697

Update accessibility link

---

static/js/admin/vue-permissions-editor/package-lock.json
static/js/admin/vue-permissions-editor/package.json
static/js/admin/vue-permissions-editor/tests/unit/embargo.spec.js
static/js/admin/vue-permissions-editor/tests/unit/modalEditor.spec.js
static/js/admin/vue-permissions-editor/tests/unit/patronRoles.spec.js
static/js/admin/vue-permissions-editor/tests/unit/staffRoles.spec.js
static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json
static/js/vue-cdr-access/src/components/browseSearch.vue
static/js/vue-cdr-access/src/components/browseSort.vue
static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/src/components/facets.vue
static/js/vue-cdr-access/src/mixins/routeUtils.js
static/js/vue-cdr-access/tests/unit/modalMetadata.spec.js
static/js/vue-cdr-access/tests/unit/pagination.spec.js
static/js/vue-cdr-access/tests/unit/routeUtils.spec.js

https://jira.lib.unc.edu/browse/BXC-2694

Update Vue dependencies and fix deprecations/warnings

---

static/js/admin/src/action/AjaxCallbackAction.js

https://jira.lib.unc.edu/browse/BXC-2688

trigger unchecking all selected items after running a batch action

---

deposit/src/main/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
metadata/src/main/java/edu/unc/lib/dl/util/JobStatusFactory.java
metadata/src/main/java/edu/unc/lib/dl/util/RedisWorkerConstants.java

https://jira.lib.unc.edu/browse/BXC-2699

Check if file has already been ingested

---

migration-util/README.md
migration-util/src/main/java/edu/unc/lib/dcr/migration/MigrationCLI.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/UpdateModelCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/DepositModelManager.java

https://jira.lib.unc.edu/browse/BXC-2715
* Adds a command for running SPARQL queries against deposit models
* Adds a command for running SPARQL updates against deposit models

BXC-2715 - Query and update deposit models

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/DepositRecordTransformer.java
migration-util/src/main/resources/spring/service-context.xml

https://jira.lib.unc.edu/browse/BXC-2686
* Missing dependencies
* Better handling of re-running the migration after failures.

BXC-2686 - Address deposit record migration issues

---

static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_homepage.scss

Make hover styling consistent between navbar and footer

---

static/js/admin/src/ResultObjectList.js

https://jira.lib.unc.edu/browse/BXC-2661

Update overlays for "moving/working" rows if a row is removed

---

deposit/src/main/java/edu/unc/lib/deposit/validate/VirusScanJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/AbstractDepositJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/validate/VirusScanJobTest.java

https://jira.lib.unc.edu/browse/BXC-2710

Add check to see if virus check has already been run.

---

persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/FSToFSTransferClient.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/StreamToFSTransferClient.java
persistence/src/main/java/edu/unc/lib/dl/util/FileTransferHelpers.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/transfer/FSToFSTransferClientTest.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/transfer/StreamToFSTransferClientTest.java

https://jira.lib.unc.edu/browse/BXC-2709

Allow for file rollback if transfer is interrupted or fails

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java

https://jira.lib.unc.edu/browse/BXC-2698

Add retry if work object ingest gives a checksum mismatch

---

services/src/main/java/edu/unc/lib/dl/cdr/services/processing/XMLExportService.java
services/src/test/java/edu/unc/lib/dl/cdr/services/processing/XMLExportServiceTest.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/ExportXMLIT.java
services/src/test/resources/export-xml-it-servlet.xml
static/js/admin/src/action/ExportMetadataXMLBatchAction.js

https://jira.lib.unc.edu/browse/BXC-2651

Allow child object MODS to be exported

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/DepositRecordTransformer.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/deposit/DepositRecordTransformerIT.java

https://jira.lib.unc.edu/browse/BXC-2726

Skip transformation of deposit records for items in the CDR

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobTest.java

https://jira.lib.unc.edu/browse/BXC-2728

Update deposited count after adding children

---

static/js/admin/vue-permissions-editor/src/components/patronRoles.vue
static/js/admin/vue-permissions-editor/tests/unit/patronRoles.spec.js

https://jira.lib.unc.edu/browse/BXC-2737

Check all permissions before assigning "staff" role

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java

https://jira.lib.unc.edu/browse/BXC-2730

Add premis events after children complete ingest

---

access/src/main/webapp/WEB-INF/jsp/advancedSearch.jsp
access/src/main/webapp/WEB-INF/jsp/common/thumbnail.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
access/src/main/webapp/WEB-INF/jsp/template/defaultTemplate.jsp
admin/src/main/webapp/WEB-INF/jsp/template/default.jsp
deposit/src/main/resources/completed_html.txt
deposit/src/main/resources/failed_html.txt
services-camel/src/main/resources/update-complete-html.txt
services-camel/src/main/resources/update-failed-html.txt
services/src/main/webapp/index.jsp
spoof/src/main/webapp/WEB-INF/jsp/spoof.jsp
static/css/cdr-homepage.css
static/css/cdr-ui.css
static/css/cdrui_styles.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_homepage.scss
static/css/sass/cdr_ui_styles.scss
static/js/public/fullRecord.js
static/js/vue-cdr-access/src/components/browseSearch.vue
static/js/vue-cdr-access/src/components/browseSort.vue
static/js/vue-cdr-access/src/components/listDisplay.vue
static/js/vue-cdr-access/src/components/pagination.vue
static/js/vue-cdr-access/src/mixins/displayUtils.js
static/maintenance.html
static/service-unavailable.html

https://jira.lib.unc.edu/browse/BXC-2496
Does not address contrast issues. Probably needs a larger discussion on color choices.

Accessibility updates

---

access-common/src/main/java/edu/unc/lib/dl/ui/service/SolrQueryLayerService.java
services/src/main/java/edu/unc/lib/dl/cdr/services/processing/XMLExportJob.java
services/src/main/java/edu/unc/lib/dl/cdr/services/processing/XMLExportService.java
services/src/test/java/edu/unc/lib/dl/cdr/services/processing/XMLExportServiceTest.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/ExportXMLIT.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/SearchState.java

https://jira.lib.unc.edu/browse/BXC-2736

Return all export results with qualified ids

---

admin/src/main/java/edu/unc/lib/dl/admin/controller/ExportController.java

https://jira.lib.unc.edu/browse/BXC-2747

Add mimetype, filesize and checksum to csv output

---

static/js/vue-cdr-access/src/components/browseSort.vue
static/js/vue-cdr-access/tests/unit/browseSort.spec.js

https://jira.lib.unc.edu/browse/BXC-2740

Fix issue with default sort causing select box to be blank

---

static/js/vue-cdr-access/src/components/displayWrapper.vue

https://jira.lib.unc.edu/browse/BXC-2735

Don't update route if no parameters are passed in the url on page load

---

deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/AbstractFedoraDepositJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestDepositRecordJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/validate/ValidateDestinationJobIT.java
deposit/src/test/resources/spring-test/cdr-client-container.xml
fcrepo-clients/src/test/java/edu/unc/lib/dl/acl/fcrepo4/AccessControlServiceImplIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/AbstractFedoraIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/AdminUnitIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/DepositRecordIT.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fedora/ContentPathFactoryIT.java
fcrepo-clients/src/test/resources/spring-test/cdr-client-container.xml
persistence/src/test/java/edu/unc/lib/dl/persist/services/acl/ExpireEmbargoServiceIT.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/acl/PatronAccessAssignmentServiceIT.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/acl/StaffRoleAssignmentServiceIT.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/destroy/DestroyObjectsJobIT.java
persistence/src/test/resources/spring-test/cdr-client-container.xml
services-camel/src/test/java/edu/unc/lib/dl/services/camel/solr/AbstractSolrProcessorIT.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/triplesReindexing/TriplesReindexingRouterIT.java
services-camel/src/test/resources/spring-test/cdr-client-container.xml
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/AbstractAPIIT.java
services/src/test/resources/spring-test/cdr-client-container.xml

https://jira.lib.unc.edu/browse/BXC-2746

BXC-2746 - Cleanup PersistingRdfStreamConsumer spam

---

static/js/admin/vue-permissions-editor/package-lock.json

Same fix as https://github.com/UNC-Libraries/Carolina-Digital-Repository/pull/1059, but for permissions editor

Pull in fix for high severity vulnerability

---

deposit/src/main/java/edu/unc/lib/deposit/work/DepositEmailHandler.java

https://jira.lib.unc.edu/browse/BXC-2754

Check for slash at end of url and remove if needed.

---

static/css/cdrui_styles.css

https://jira.lib.unc.edu/browse/BXC-2760

Break long alt text on images

---

static/js/admin/src/MoveDropLocation.js
static/js/admin/src/ResultTableView.js
static/js/admin/src/ResultView.js

https://jira.lib.unc.edu/browse/BXC-2752

Set destinations that produce errors  to invalid drop targets instead of cancelling the entire drop

---

static/js/admin/vue-permissions-editor/package-lock.json
static/js/admin/vue-permissions-editor/package.json
static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json

Should fix https://github.com/UNC-Libraries/Carolina-Digital-Repository/network/alerts

Update to grab security fixes

---

.gitmodules
pom.xml

https://jira.lib.unc.edu/browse/BXC-2762
See https://gitlab.lib.unc.edu/cdr/boxc-ansible/-/merge_requests/71 for updated OAI-PMH deploy

Remove oai submodule

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java

https://jira.lib.unc.edu/browse/BXC-2786

Favor filename over dc.title when migrating objects

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobTest.java

https://jira.lib.unc.edu/browse/BXC-2785
* Move checksum failure retry to only apply to original file add, rather than retrying whole work to avoid repeating operations. 
* Remove check for description storage uri property before adding description, as it can cause mods to be lost if the job is interrupted gracefully after adding the description but before the work completes

BXC-2785 - Prevent loss of mods when ingest checksum failure occurs

---

deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
metadata/src/main/java/edu/unc/lib/dl/util/DepositStatusFactory.java

https://jira.lib.unc.edu/browse/BXC-2739

Clear empty deposit workers before stopping deposit service

---

deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java

https://jira.lib.unc.edu/browse/BXC-2782

Don't throw JobInterrupted exception if state is "finished" and waiting on cleanup job to run

---

services/src/main/java/edu/unc/lib/dl/cdr/services/processing/RunEnhancementsService.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/RunEnhancementsIT.java

https://jira.lib.unc.edu/browse/BXC-2776

Fix issue with enhancements trying to run on non-file objects

---

deposit/src/main/java/edu/unc/lib/deposit/normalize/AbstractFileServerToBagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJob.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/DirectoryToBagJob.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/DirectoryToBagJobTest.java

https://jira.lib.unc.edu/browse/BXC-2731

Have DirectoryToBagJob produce works instead of folders

---

static/js/admin/vue-permissions-editor/package-lock.json
static/js/admin/vue-permissions-editor/package.json
static/js/admin/vue-permissions-editor/tests/unit/staffRoles.spec.js
static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json
static/js/vue-cdr-access/tests/unit/pagination.spec.js

Fixes security notices.
As a side effect, it should fix https://jira.lib.unc.edu/browse/BXC-2791

minor dependency updates

---

services-camel/src/main/java/edu/unc/lib/dl/services/camel/solrUpdate/SolrUpdatePreprocessor.java

https://jira.lib.unc.edu/browse/BXC-2792

Add RECURSIVE_ADD to the list of large actions. Allows primary object changes to index

---

Makefile
static/js/admin/vue-permissions-editor/package-lock.json
static/js/admin/vue-permissions-editor/package.json
static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json

https://jira.lib.unc.edu/browse/BXC-2791

Pkg updates

---

deposit/src/test/java/edu/unc/lib/deposit/transfer/TransferBinariesToStorageJobTest.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/FSToFSTransferClient.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/transfer/StreamToFSTransferClient.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/transfer/BinaryTransferServiceImplIT.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/transfer/BinaryTransferSessionImplTest.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/transfer/FSToFSTransferClientTest.java

https://jira.lib.unc.edu/browse/BXC-2803

BXC-2803: Switch ingest file transfers from move to copy

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactory.java

https://jira.lib.unc.edu/browse/BXC-2813

Remove all sub fields from mimetype

---

etc/solr-config/access/conf/schema.xml
etc/solr-config/access/conf/solrconfig.xml
services-camel/src/test/resources/config/access/conf/schema.xml
services-camel/src/test/resources/config/access/conf/solrconfig.xml
solr-ingest/src/test/resources/config/access/conf/schema.xml
solr-ingest/src/test/resources/config/access/conf/solrconfig.xml

* Bump lucene match version
* Fix deprecation notices
https://jira.lib.unc.edu/browse/BXC-2807
See https://gitlab.lib.unc.edu/cdr/boxc-ansible/-/merge_requests/86 for related updates

Fix solr warnings

---

static/js/admin/src/AddMenu.js

https://jira.lib.unc.edu/browse/BXC-2805

Only allow file server ingests at the collection level

---

static/js/admin/vue-permissions-editor/package-lock.json
static/js/admin/vue-permissions-editor/package.json
static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json

Security fix: https://github.com/UNC-Libraries/Carolina-Digital-Repository/network/alerts

Vue security fix

---

static/js/xmleditor/templates/generic.xml

https://jira.lib.unc.edu/browse/BXC-2806

Set default language for generic mods template

---

spoof/src/main/webapp/WEB-INF/jsp/spoof.jsp

https://jira.lib.unc.edu/browse/BXC-2766

BXC-2766 - Change spoof options

---

deposit/src/main/java/edu/unc/lib/deposit/validate/VirusScanJob.java
deposit/src/test/java/edu/unc/lib/deposit/validate/VirusScanJobTest.java

https://jira.lib.unc.edu/browse/BXC-2812

Only mark a file completed if it passes virus checking

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJob.java
deposit/src/main/java/edu/unc/lib/deposit/fcrepo4/IngestDepositRecordJob.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/IngestDepositRecordJobIT.java

https://jira.lib.unc.edu/browse/BXC-2816

BXC-2816 - Set storageLocation property in fedora during ingest

---

solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessStatusFilter.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessStatusFilterTest.java

https://jira.lib.unc.edu/browse/BXC-2815

Check patron roles instead of princ roles when adding patron-settings tag

---

services/src/main/java/edu/unc/lib/dl/cdr/services/processing/AddContainerService.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/AddContainerIT.java

https://jira.lib.unc.edu/browse/BXC-2819

new collections should default to canViewOriginals permissions

---

access-common/src/main/java/edu/unc/lib/dl/ui/service/LorisContentService.java
access-common/src/main/java/edu/unc/lib/dl/ui/util/AnalyticsTrackerUtil.java
access/src/main/webapp/WEB-INF/access-fedora-context.xml
access/src/main/webapp/WEB-INF/service-context.xml
admin/src/main/webapp/WEB-INF/access-fedora-context.xml
admin/src/main/webapp/WEB-INF/service-context.xml
deposit/src/main/webapp/WEB-INF/service-context.xml
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/AbstractDepositJobTest.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/sparql/FusekiSparqlQueryServiceImpl.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/SubmitDepositCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/TransformContentCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/TransformDepositRecordsCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/UpdateModelCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/ViewDepositModelCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/PreconstructedDepositSubmissionService.java
migration-util/src/main/resources/spring/service-context.xml
migration-util/src/test/java/edu/unc/lib/dcr/migration/TransformContentCommandIT.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/deposit/PreconstructedDepositSubmissionServiceTest.java
migration-util/src/test/resources/spring-test/cdr-client-container.xml
persistence/src/main/java/edu/unc/lib/dl/persist/services/deposit/DepositModelManager.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/ingest/DepositSubmissionServiceTest.java
services-camel/src/main/webapp/WEB-INF/service-context.xml
services-camel/src/test/resources/triples-reindexing-it-context.xml
services/src/main/webapp/WEB-INF/access-fedora-context.xml
services/src/main/webapp/WEB-INF/service-context.xml

Make sure to close various connection pools on shutdown, particularly for the migration utility

Cleanup connection pools on shutdown

---

access-common/src/main/resources/META-INF/cdrUI.tld
access/src/main/webapp/WEB-INF/jsp/common/header.jsp
access/src/main/webapp/WEB-INF/jsp/common/headerSmall.jsp
admin/src/main/webapp/WEB-INF/jsp/common/header.jsp

https://jira.lib.unc.edu/browse/BXC-2831

Correctly display user as logged in

---

deposit/src/main/java/edu/unc/lib/deposit/fcrepo3/IngestDeposit.java
deposit/src/main/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJob.java

https://jira.lib.unc.edu/browse/BXC-2834
Store path to bagit manifests as file path. Allow files to be ingested from outside of the deposit directory if they are part of a manifest datastream

BXC-2834 - Fix bug with adding manifests for bagit deposits

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/TransformContentCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerManager.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentTransformationService.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerTest.java

https://jira.lib.unc.edu/browse/BXC-2824
https://jira.lib.unc.edu/browse/BXC-2845

Transform collections in collections into folders and set parentType destination

---

static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_homepage.scss
static/js/admin/src/ResultObjectActionMenu.js

* Fix options for content root
* Fix hover css for "advanced search" link on home page
https://jira.lib.unc.edu/browse/BXC-2851

Fix options for content root

---

access/src/main/webapp/WEB-INF/jsp/fullRecord/adminUnit.jsp

Fix layout of subject display
https://jira.lib.unc.edu/browse/BXC-2838

Fix layout of collection pages

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/TransformContentCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ACLTransformationHelpers.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ACLTransformationReport.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformer.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentObjectTransformerManager.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentTransformationReport.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/utils/DisplayProgressUtil.java

https://jira.lib.unc.edu/browse/BXC-2867
* Add reporting of content transformation stats for transform command
* Adjust how completion count is calculated and displayed to make it more up to date
* Fix rounding problem with progress bar

BXC-2867 - Add reporting of content transformation stats for transform command

---

static/js/admin/vue-permissions-editor/src/assets/common-styles.css
static/js/admin/vue-permissions-editor/src/components/staffRoles.vue

https://jira.lib.unc.edu/browse/BXC-2869

Truncate long permission text. Show full permission on hover

---

services-camel/src/main/java/edu/unc/lib/dl/services/camel/fulltext/FulltextProcessor.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/fulltext/FulltextProcessorTest.java

https://jira.lib.unc.edu/browse/BXC-2868

Prevent text extraction for empty files

---

pom.xml

https://jira.lib.unc.edu/browse/BXC-2879

Update junit version

---

persistence/src/main/java/edu/unc/lib/dl/persist/services/acl/PatronAccessAssignmentService.java
persistence/src/test/java/edu/unc/lib/dl/persist/services/acl/PatronAccessAssignmentServiceIT.java
services/src/main/java/edu/unc/lib/dl/cdr/services/processing/AddContainerService.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/AddContainerIT.java

https://jira.lib.unc.edu/browse/BXC-2871

Allow ingestors to create "staff only" folders

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/content/ContentTransformationService.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/TransformContentCommandIT.java

https://jira.lib.unc.edu/browse/BXC-2883
Allow multiple starting pids to be provided in a single content transformation command

BXC-2883 - Multiple starting pids in content transformation command

---

deposit/src/main/java/edu/unc/lib/deposit/validate/VirusScanJob.java
deposit/src/test/java/edu/unc/lib/deposit/validate/VirusScanJobTest.java

https://jira.lib.unc.edu/browse/BXC-2886

Update clicks for already run files

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactory.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/fcrepo4/RepositoryObjectFactoryIT.java

https://jira.lib.unc.edu/browse/BXC-2914

Only return first part of mimetype, if it has multiple parts

---

static/js/admin/vue-permissions-editor/src/assets/common-styles.css
static/js/admin/vue-permissions-editor/src/components/staffRoles.vue

* Truncate from the end of the permissions
* Allow permission copying.
https://jira.lib.unc.edu/browse/BXC-2920

Permission display updates

---

solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessControlFilter.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetAccessControlFilterTest.java

Followup to https://github.com/UNC-Libraries/Carolina-Digital-Repository/pull/1128

Grant patron read access to collections object

---

static/js/admin/src/ParentResultObject.js

https://jira.lib.unc.edu/browse/BXC-2899

Check if parent container is marked for deletion

---

deposit/src/main/java/edu/unc/lib/deposit/validate/ExtractTechnicalMetadataJob.java

https://jira.lib.unc.edu/browse/BXC-2909

Skip objects that have already run

---

static/js/admin/src/ResultObjectActionMenu.js

https://jira.lib.unc.edu/browse/BXC-2933

Use copy api insead of a prompt

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/TransformContentCommand.java

https://jira.lib.unc.edu/browse/BXC-2942

BXC-2942 - Make failure message more visible

---

deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml

https://jira.lib.unc.edu/browse/BXC-2915
* Use a separate HttpClient with a different configurable timeout for requests to the FITS service

BXC-2915 - Configure separate timeout for FITS extract requests

---

deposit/src/main/java/edu/unc/lib/deposit/validate/VirusScanJob.java
deposit/src/main/java/edu/unc/lib/deposit/work/AbstractDepositJob.java
deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml
deposit/src/test/java/edu/unc/lib/deposit/validate/VirusScanJobTest.java
fcrepo-clients/src/main/java/edu/unc/lib/dl/event/FilePremisLogger.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/MigrationCLI.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/VerifyPremisLogsCommand.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/deposit/DepositDirectoryManager.java

https://jira.lib.unc.edu/browse/BXC-2936
* Perform virus scans within a executor service with a configured number of workers

BXC-2936 - Parallel virus scans

---

services-camel/src/main/java/edu/unc/lib/dl/services/camel/fulltext/FulltextProcessor.java

https://jira.lib.unc.edu/browse/BXC-2930

Allow unlimited characters for text extraction

---

services-camel/src/main/java/edu/unc/lib/dl/services/camel/fulltext/FulltextProcessor.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/fulltext/FulltextProcessorTest.java

Follow up for https://jira.lib.unc.edu/browse/BXC-2930

BXC-2930 - Set tika limit to 1million characters

---

services-camel/src/main/java/edu/unc/lib/dl/services/camel/images/ImageDerivativeProcessor.java

Remove logic for adding [0] as it is always present in the script now

BXC-2945 - Remove duplicate frame index

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/MigrationCLI.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/SendMessageCommand.java
migration-util/src/main/resources/fedora_message.json.template
migration-util/src/main/resources/spring/send-message-context.xml

https://jira.lib.unc.edu/browse/BXC-2944
* Utility for sending fedora messages for one or more objects, optionally recursively. This should trigger indexing and services.
```
> sudo dcr_migr.sh send_message fedora -f /tmp/send_msg.txt --recursive
Sending messages for 3 objects
===================================================================
══        ══            ___                                   
___      ___           | _ ) _____ ____                       
| ▄ |    | ▄ |          | _ \/ _ \ \ / _|                      
┌---┴---┴----┴---┴----┐     |___/\___/_\_\__|       _   _          
|                     |     |  \/  (_)__ _ _ _ __ _| |_(_)___ _ _  
└-┬┬--┬┬--┬-┬--┬┬--┬┬-┘     | |\/| | / _` | '_/ _` |  _| / _ \ ' \ 
| \/  \/   \/  \/ |       |_|  |_|_\__, |_| …
```

BXC-2944 - Utility for triggering all services

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/fcrepo4/FcrepoJmsConstants.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/SendMessageCommand.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/BinaryEnhancementProcessor.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/routing/FedoraIdFilters.java
services-camel/src/main/java/edu/unc/lib/dl/services/camel/solr/SolrIngestProcessor.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/BinaryEnhancementProcessorTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/enhancements/EnhancementRouterIT.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/fulltext/FulltextRouterTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/routing/MetaServicesRouterTest.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/solr/SolrIngestProcessorIT.java
services-camel/src/test/java/edu/unc/lib/dl/services/camel/solr/SolrRouterTest.java

* Allow "send_messages" command to follow primaryObject links
* Setting fedora headers on messages
* Moves Fcrepo constants file

Send message command follow primaryObject links

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/util/DerivativeService.java
services-camel/src/main/webapp/WEB-INF/solr-indexing-context.xml
services-camel/src/test/java/edu/unc/lib/dl/services/camel/solr/SolrIngestProcessorIT.java
services-camel/src/test/resources/solr-indexing-it-context.xml
services/src/test/resources/spring-test/solr-indexing-context.xml
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetFullTextFilter.java
solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/indexing/SolrUpdateDriver.java
solr-ingest/src/test/java/edu/unc/lib/dl/data/ingest/solr/filter/SetFullTextFilterTest.java

https://jira.lib.unc.edu/browse/BXC-2971
* Set full text field from the text extract derivative

BXC-2971 - Set full text field from the text extract derivative

---

deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
deposit/src/test/java/edu/unc/lib/deposit/fcrepo4/AbstractFedoraDepositJobIT.java
deposit/src/test/java/edu/unc/lib/deposit/work/DepositSupervisorTest.java
deposit/src/test/resources/spring-test/cdr-client-container.xml
deposit/src/test/resources/spring-test/deposit-supervisor-test-context.xml
metadata/src/main/java/edu/unc/lib/dl/util/DepositStatusFactory.java

https://jira.lib.unc.edu/browse/BXC-2875
* Switch test to polling for deposit state and action with a timeout

BXC-2875 - Fix flapping DepositSupervisor test

---

solr-ingest/src/main/java/edu/unc/lib/dl/data/ingest/solr/filter/SetDescriptiveMetadataFilter.java

https://jira.lib.unc.edu/browse/BXC-2991
* Make sure that display label exists before checking its value for finding aid links

BXC-2991 - Fix NPE for relatedItem with location but not finding aid

---

migration-util/src/main/java/edu/unc/lib/dcr/migration/MigrationCLI.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/SubmitDepositCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/TransformContentCommand.java
migration-util/src/main/java/edu/unc/lib/dcr/migration/deposit/PreconstructedDepositSubmissionService.java
migration-util/src/test/java/edu/unc/lib/dcr/migration/deposit/PreconstructedDepositSubmissionServiceTest.java

https://jira.lib.unc.edu/browse/BXC-2955

Allow user to pass in a display label.

---

access/src/main/webapp/WEB-INF/jsp/index.jsp
admin/src/main/webapp/WEB-INF/jsp/index.jsp

https://jira.lib.unc.edu/browse/BXC-2975

Set Shibboleth redirect to always use https

---

static/css/admin/cdradmin.css
static/js/admin/src/ResultObjectActionMenu.js

https://jira.lib.unc.edu/browse/BXC-2994

Add more metadata view options

---

static/maintenance.html

https://jira.lib.unc.edu/browse/BXC-3001

Update offline page message

---

static/js/admin/vue-permissions-editor/src/assets/common-styles.css
static/js/admin/vue-permissions-editor/src/components/embargo.vue
static/js/admin/vue-permissions-editor/src/components/patronDisplayRow.vue
static/js/admin/vue-permissions-editor/src/components/patronRoles.vue
static/js/admin/vue-permissions-editor/src/mixins/patronHelpers.js
static/js/admin/vue-permissions-editor/tests/unit/patronDisplayRow.spec.js
static/js/admin/vue-permissions-editor/tests/unit/patronRoles.spec.js

https://jira.lib.unc.edu/browse/BXC-2887
Component basically entirely rewritten.

Improve readability of patron status screen

---

admin/src/main/java/edu/unc/lib/dl/admin/controller/SearchController.java
static/js/admin/src/ResultObjectActionMenu.js
static/js/admin/src/ResultView.js

* Restrict CSV export to 50,000 objects
* Make sure parent gets a child count
https://jira.lib.unc.edu/browse/BXC-2999

Restrict CSV export to 50,000 objects

---

static/js/public/fullRecord.js

https://jira.lib.unc.edu/browse/BXC-3005

Treat Nan as 0 bytes

---

services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/ExportCsvController.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/ExportCsvIT.java

https://jira.lib.unc.edu/browse/BXC-2993

Add permissions and embargo info to CSV output

---

access/src/main/webapp/WEB-INF/jsp/fullRecord/adminUnit.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/collectionRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/folderRecord.jsp

https://jira.lib.unc.edu/browse/BXC-3012

Don't show note if no abstract found

---

access/src/main/webapp/WEB-INF/jsp/frontPage.jsp

https://jira.lib.unc.edu/browse/BXC-3027
* Use correct rbc thumbnail.
* Remove uuid: prefixes

BXC-3027 - RBC thumbnail on front page

---

access/src/main/webapp/WEB-INF/jsp/fullRecord/adminUnit.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/collectionRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/folderRecord.jsp
static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss
static/js/public/abstractDisplay.js
static/js/vue-cdr-access/src/components/browseDisplay.vue

* Make display abstract larger and align it.
* Fix issue with titles bleeding of page in browse view
* Fix issue with thumbnails bleeding into  breadcrumbs on small screens
https://jira.lib.unc.edu/browse/BXC-3029

Layout fixes

---

metadata/src/main/java/edu/unc/lib/dl/util/URIUtil.java
metadata/src/test/java/edu/unc/lib/dl/util/URIUtilTest.java

https://jira.lib.unc.edu/browse/BXC-3025

Skip empty segments when creating uris

---

access/src/main/java/edu/unc/lib/dl/ui/controller/FullRecordController.java
access/src/main/java/edu/unc/lib/dl/ui/controller/SearchActionController.java

https://jira.lib.unc.edu/browse/BXC-3037

redirect list/{pid} links to record/{pid}

---

fcrepo-clients/src/main/java/edu/unc/lib/dl/acl/fcrepo4/GlobalPermissionEvaluator.java
fcrepo-clients/src/test/java/edu/unc/lib/dl/acl/fcrepo4/GlobalPermissionEvaluatorTest.java

https://jira.lib.unc.edu/browse/BXC-3031

BXC-3031 - Allow for multiple global principals to be assigned to the same role

---

static/js/vue-cdr-access/src/components/browseSort.vue
static/js/vue-cdr-access/src/mixins/routeUtils.js
static/js/vue-cdr-access/tests/unit/browseSort.spec.js
static/js/vue-cdr-access/tests/unit/routeUtils.spec.js

https://jira.lib.unc.edu/browse/BXC-3042

Set all searches to default,normal

---

static/js/vue-cdr-access/tests/unit/displayWrapper.spec.js

Additional fix as part of https://jira.lib.unc.edu/browse/BXC-3042

Change search option to default

---

services-camel/src/test/java/edu/unc/lib/dl/services/camel/enhancements/EnhancementRouterIT.java

https://jira.lib.unc.edu/browse/BXC-2932
- Send messages after setting up notification monitors

BXC-2932 - EnhancementRouterIT

---

access-common/src/main/java/edu/unc/lib/dl/ui/service/SolrQueryLayerService.java
access-common/src/main/java/edu/unc/lib/dl/ui/util/SearchConstants.java

https://jira.lib.unc.edu/browse/BXC-3049

Bump up number of returned collections

---

access/src/main/java/edu/unc/lib/dl/ui/controller/FullRecordController.java

https://jira.lib.unc.edu/browse/BXC-3047

Catch restricted access exceptions

---

services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/EditTitleIT.java
static/js/admin/src/EditTitleForm.js

https://jira.lib.unc.edu/browse/BXC-3055

Escape special characters in title

---

static/css/sass/cdr_vue_modal_styles.scss

https://jira.lib.unc.edu/browse/BXC-3060

Add vertical scrolling for modal dialog boxes

---

Makefile
admin/src/main/java/edu/unc/lib/dl/admin/controller/ResultEntryController.java
static/css/sass/cdr_vue_modal_styles.scss
static/js/admin/src/ParentResultObject.js
static/js/admin/src/ResultObjectActionMenu.js
static/js/admin/vue-permissions-editor/src/components/modalEditor.vue
static/js/admin/vue-permissions-editor/src/components/patronRoles.vue
static/js/admin/vue-permissions-editor/tests/unit/patronRoles.spec.js
static/templates/admin/resultTableHeader.html

https://jira.lib.unc.edu/browse/BXC-3054

Update admin result entries after changes

---

services/src/main/webapp/WEB-INF/access-fedora-context.xml

https://jira.lib.unc.edu/browse/BXC-3073
Configure DatastreamUtil so that it can be used to create thumbnail uris in services app

BXC-3073 - Configure DatastreamUtil

---

deposit/src/main/java/edu/unc/lib/deposit/normalize/AbstractFileServerToBagJob.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJobTest.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/DirectoryToBagJobTest.java
metadata/src/main/java/edu/unc/lib/dl/util/RedisWorkerConstants.java
persistence/src/main/java/edu/unc/lib/dl/persist/services/ingest/AbstractDepositHandler.java
services/src/main/java/edu/unc/lib/dl/cdr/services/rest/modify/IngestSourceController.java
services/src/test/java/edu/unc/lib/dl/cdr/services/rest/modify/IngestFromSourcesIT.java
static/js/admin/src/IngestFromSourceForm.js
static/js/xmleditor/templates/archives.xml
static/templates/admin/ingestSourceMetadata.html

https://jira.lib.unc.edu/browse/BXC-3057

Remove unused accession number and media id

---

.gitmodules
deposit/pom.xml
deposit/src/main/java/edu/unc/lib/deposit/validate/VirusScanJob.java
deposit/src/main/webapp/WEB-INF/deposit-jobs-context.xml
deposit/src/test/java/edu/unc/lib/deposit/validate/VirusScanJobTest.java
persistence/pom.xml
pom.xml

https://jira.lib.unc.edu/browse/BXC-2379
* Swaps clamavj for a fork of clamav-java https://github.com/UNC-Libraries/clamav-java/pull/2
* Adds retries when virus scans indicate that an issue is FOUND, but no information about the issue is returned. This seems to indicate it is a transient false positive.

BXC-2379 - Replace clam dependency, add retries

---

services/src/main/java/edu/unc/lib/dl/cdr/services/processing/XMLExportJob.java
services/src/test/java/edu/unc/lib/dl/cdr/services/processing/XMLExportServiceTest.java

https://jira.lib.unc.edu/browse/BXC-3067

Use the mods last modified date

---

access/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
access/src/main/webapp/WEB-INF/jsp/fullRecord/fileRecord.jsp
static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss

https://jira.lib.unc.edu/browse/BXC-3064

Add abstract text to work pages

---

services/src/main/java/edu/unc/lib/dl/cdr/services/processing/XMLExportJob.java
services/src/test/java/edu/unc/lib/dl/cdr/services/processing/XMLExportServiceTest.java

https://jira.lib.unc.edu/browse/BXC-3061

Add object type to mods export

---

access-common/src/main/java/edu/unc/lib/dl/ui/service/SolrQueryLayerService.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/model/SearchState.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/ChildrenCountService.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/NeighborQueryService.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/service/SolrSearchService.java
solr-search/src/main/java/edu/unc/lib/dl/search/solr/util/AccessRestrictionUtil.java
solr-search/src/test/java/edu/unc/lib/dl/search/solr/util/AccessRestrictionUtilTest.java

https://jira.lib.unc.edu/browse/BXC-2977
* Uses edismax query for regular keyword search queries
* Facets, ranges, access control components of query switched to filter queries

BXC-2977 - Title Search relevancy

---

static/js/admin/editDescription.js
static/js/xmleditor/jquery.xmleditor.js

https://jira.lib.unc.edu/browse/BXC-3056

Override current MODS using a template

---

access-common/src/main/java/edu/unc/lib/dl/ui/controller/LorisContentController.java
access-common/src/main/java/edu/unc/lib/dl/ui/service/LorisContentService.java

https://jira.lib.unc.edu/browse/BXC-3051

Allow remote img viewers access to public dcr images

---

static/js/admin/vue-permissions-editor/package-lock.json
static/js/admin/vue-permissions-editor/package.json
static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json
static/js/vue-cdr-access/src/components/browseSearch.vue
static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/src/components/worksOnly.vue
static/js/vue-cdr-access/src/mixins/routeUtils.js
static/js/vue-cdr-access/src/router.js
static/js/vue-cdr-access/tests/unit/browseSearch.spec.js
static/js/vue-cdr-access/tests/unit/browseSort.spec.js
static/js/vue-cdr-access/tests/unit/displayWrapper.spec.js
static/js/vue-cdr-access/tests/unit/routeUtils.spec.js
static/js/vue-cdr-access/tests/unit/worksOnly.spec.js

https://jira.lib.unc.edu/browse/BXC-3083

Search within an object

---

static/js/admin/vue-permissions-editor/src/components/embargo.vue
static/js/admin/vue-permissions-editor/src/components/modalEditor.vue
static/js/admin/vue-permissions-editor/src/components/patronRoles.vue
static/js/admin/vue-permissions-editor/tests/unit/patronRoles.spec.js

* Fix submit/cancel buttons to always display
* Fix issue with "warning" not popping up when there are unsaved changes
https://jira.lib.unc.edu/browse/BXC-3092

Patron access editor Save/Cancel button updates

---

metadata/src/main/resources/edu/unc/lib/dl/schematron/vocabularies-mods.sch
metadata/src/test/java/edu/unc/lib/dl/validation/MODSValidatorTest.java

https://jira.lib.unc.edu/browse/BXC-3121

Allow edtf for keyDates

---

access/src/main/webapp/WEB-INF/jsp/fullRecord/pdfViewer.jsp
static/plugins/pdfjs/web/viewer.css

https://jira.lib.unc.edu/browse/BXC-3126
https://jira.lib.unc.edu/browse/BXC-3127

Pdfjs accessibility

---

access/src/main/java/edu/unc/lib/dl/ui/controller/AdvancedSearchFormController.java

https://jira.lib.unc.edu/browse/BXC-3197

Update advanced search for new search url structure

---

Makefile

Depends on https://gitlab.lib.unc.edu/cdr/boxc-ansible/-/merge_requests/134
https://jira.lib.unc.edu/browse/BXC-3154

Split static build into multiple targets

---

static/js/admin/editDescription.js
static/js/xmleditor/templates/oral_histories_interviews.xml
static/js/xmleditor/templates/oral_histories_series.xml

Add oral_histories_interviews.xml and oral_histories_series.xml to xmleditor templates

Create mods templates from oral histories map

---

deposit/src/main/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJob.java
deposit/src/test/java/edu/unc/lib/deposit/normalize/BagIt2N3BagJobTest.java

https://jira.lib.unc.edu/browse/BXC-3217
* Avoid closing BagVerifier to prevent it from shutting down the executor

BXC-3217 - Bagit job shutting down executor

---

.gitmodules
pom.xml

https://jira.lib.unc.edu/browse/BXC-3219

BXC-3219 - Switch to using fcrepo-5.1.2-rc-1 for integration tests

---

static/css/cdr-ui.css
static/css/sass/cdr-ui.scss
static/css/sass/cdr_ui_styles.scss
static/js/public/fullRecord.js

https://jira.lib.unc.edu/browse/BXC-3239

Lazy load dataTables images

---

README.md

https://jira.lib.unc.edu/browse/BXC-3152

BXC-3152 - Update name of repo in readme

---

pom.xml

https://jira.lib.unc.edu/browse/BXC-3299

BXC-3299 - Update activemq to 5.16.3

---

auth-fcrepo/src/main/java/edu/unc/lib/boxc/auth/fcrepo/services/AccessControlServiceImpl.java
deposit-app/src/main/resources/completed_text.txt
services-camel-app/src/main/resources/update-complete-html.txt
services-camel-app/src/main/resources/update-failed-html.txt

https://jira.lib.unc.edu/browse/BXC-3124

BXC-3124 - Replace CDR with DCR in email templates and a comment

---

README.md
etc/ide_setup/README.md
etc/ide_setup/boxc_code_profile.xml

https://jira.lib.unc.edu/browse/BXC-3298

BXC-3298 - Add intellij setup

---

web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FullRecordController.java
web-access-app/src/main/resources/modsExclusionXPaths.json
web-access-app/src/main/webapp/WEB-INF/service-context.xml
web-common/src/main/java/edu/unc/lib/boxc/web/common/services/XmlDocumentFilteringService.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/services/XmlDocumentFilteringServiceTest.java
web-common/src/test/resources/mods/test_record.xml

https://jira.lib.unc.edu/browse/BXC-3287
* Filters MODS fields from the public display based on a list of configured xpath expressions

BXC-3287 - Filter MODS fields from public display

---

web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FullRecordController.java
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/pdfViewer.jsp
web-common/src/main/java/edu/unc/lib/boxc/web/common/services/AccessCopiesService.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/services/AccessCopiesServiceTest.java

* Update when download button displays
* Move audio file checks to service
https://jira.lib.unc.edu/browse/BXC-3384

Update when download button displays and move audio file check to service

---

pom.xml
services-camel-app/pom.xml

https://jira.lib.unc.edu/browse/BXC-3404
* Updates spring to 5.3.15
* Updates camel and resolves dependency conflicts with spring update
* Updates spring.ws version
* Removes unused dependency and variables

BXC-3404 - Update spring to 5.3.15

---

static/js/vue-cdr-access/jest.config.js
static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json
static/js/vue-cdr-access/src/components/browseSearch.vue
static/js/vue-cdr-access/src/components/browseSort.vue
static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/src/components/facets.vue
static/js/vue-cdr-access/src/components/searchWrapper.vue
static/js/vue-cdr-access/src/components/viewType.vue
static/js/vue-cdr-access/src/components/worksOnly.vue
static/js/vue-cdr-access/src/main.js
static/js/vue-cdr-access/src/router.js
static/js/vue-cdr-access/tests/unit/browseDisplay.spec.js
static/js/vue-cdr-access/tests/unit/browseSearch.spec.js
static/js/vue-cdr-access/tests/unit/browseSort.spec.js
static/js/vue-cdr-access/tests/unit/collectionBrowse.spec.js
static/js/vue-cdr-access/tests/unit/displayWrapper.spec.js
static/js/vue-cdr-access/tests/unit/facets.spec.js
static/js/vue-cdr-access/tests/unit/filterTags.spec.js
static/js/vue-cdr-access/tests/unit/listDisplay.spec.js
static/js/vue-cdr-access/tests/unit/modalMetadata.spec.js
static/js/vue-cdr-access/tests/unit/pagination.spec.js
static/js/vue-cdr-access/tests/unit/routeUtils.spec.js
static/js/vue-cdr-access/tests/unit/searchWrapper.spec.js
static/js/vue-cdr-access/tests/unit/viewType.spec.js
static/js/vue-cdr-access/tests/unit/worksOnly.spec.js

https://jira.lib.unc.edu/browse/BXC-3420

Update vue 2 based access app to vue 3

---

static/plugins/pdfjs/web/viewer.css

* Remove content rules with "var" element. They don't work on safari and are duplicating rules anyway.
* Fix hover color
https://jira.lib.unc.edu/browse/BXC-3425

Remove content rules with "var" element.

---

operations/src/main/resources/edu/unc/lib/boxc/operations/impl/validation/vocabularies-mods.sch

This seemed to work when I tested it on some sample MODS with the problem fields, but please suggest changes or improvements!

BXC-3430 - Add test for correct coll number pattern

---

static/plugins/uv/package-lock.json

https://jira.lib.unc.edu/browse/BXC-3450

Address universal viewer security issues

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/SolrSearchService.java

* Fix bug that caused contributor/subject/title searches to search all fields. 
* Refactor addSearchFields to perform term searches other than keyword/anywhere searches using fq parameters.

BXC-3434 - Fix advanced search contributor/subject/title searches

---

web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/SearchActionController.java

https://jira.lib.unc.edu/browse/BXC-3433
* Disable record rollup/grouping in search when no search terms are specified, since there is no need to match against data from file objects

BXC-3433 - Improve performance of blank search

---

web-access-app/src/main/resources/modsExclusionXPaths.json

- Revise dateCaptured specifically to fields used in Gilmer
- add two fields used in book metadata profile

BXC-3457 - Edit mods exclusion xpaths

---

web-access-app/src/main/webapp/WEB-INF/jsp/advancedSearch.jsp

https://jira.lib.unc.edu/browse/BXC-3454

Change keyword label to anywhere

---

static/templates/admin/importMetadataXMLForm.html

https://jira.lib.unc.edu/browse/BXC-3448

Update MODS upload text

---

static/js/admin/src/action/UpdatePatronAccessBatchAction.js

https://jira.lib.unc.edu/browse/BXC-3471

Switch bulk update data loading to use Vuex data store

---

static/js/xmleditor/templates/continuing_resource.xml
static/js/xmleditor/templates/generic.xml

- Personal name subjects
- Corporate name subjects
- Geographic subjects

BXC-3462 - Add subject fields to generic work and continuing resource templates

---

static/js/vue-cdr-access/src/components/facets.vue
static/js/vue-cdr-access/tests/unit/facets.spec.js

https://jira.lib.unc.edu/browse/BXC-3474

Don't display empty facets

---

static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json
static/js/vue-cdr-access/src/components/browseSearch.vue
static/js/vue-cdr-access/src/components/browseSort.vue
static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/src/components/facets.vue
static/js/vue-cdr-access/src/components/listDisplay.vue
static/js/vue-cdr-access/src/components/modalMetadata.vue
static/js/vue-cdr-access/src/components/pagination.vue
static/js/vue-cdr-access/src/components/searchWrapper.vue
static/js/vue-cdr-access/src/components/viewType.vue
static/js/vue-cdr-access/src/components/worksOnly.vue
static/js/vue-cdr-access/src/main.js
static/js/vue-cdr-access/src/translations.js
static/js/vue-cdr-access/tests/unit/browseSearch.spec.js
static/js/vue-cdr-access/tests/unit/browseSort.spec.js
static/js/vue-cdr-access/tests/unit/displayWrapper.spec.js
static/js/vue-cdr-access/tests/unit/facets.spec.js
static/js/vue-cdr-access/tests/unit/listDisplay.spec.js
static/js/vue-cdr-access/tests/unit/modalMetadata.spec.js
static/js/vue-cdr-access/tests/unit/pagination.spec.js
static/js/vue-cdr-access/tests/unit/searchWrapper.spec.js
static/js/vue-cdr-access/tests/unit/viewType.spec.js
static/js/vue-cdr-access/tests/unit/worksOnly.spec.js

https://jira.lib.unc.edu/browse/BXC-3482

Set up internationalization of vue components

---

static/js/vue-cdr-access/src/mixins/routeUtils.js
static/js/vue-cdr-access/tests/unit/routeUtils.spec.js

https://jira.lib.unc.edu/browse/BXC-3538

Have subject facet appear on all search types

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/config/SearchSettings.java
web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/structure/StructureResultsController.java
web-admin-app/src/main/webapp/WEB-INF/uiapp-servlet.xml

https://jira.lib.unc.edu/browse/LIB-16324
* Add roleGroup to structure results
* move structure controller to admin application

LIB-16324 - Fix move operations using the structure browse

---

static/js/vue-cdr-access/src/components/facets.vue

Small fix to reset slider end year correctly after clearing a date range search.

Small fix to reset slider end year correctly

---

etc/solr-config/access/conf/schema.xml

https://jira.lib.unc.edu/browse/BXC-3502
Related PR: https://gitlab.lib.unc.edu/cdr/boxc-ansible/-/merge_requests/185

Add docValues to fields used for sorting and faceting

---

indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetFullTextFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetFullTextFilterTest.java

https://jira.lib.unc.edu/browse/BXC-3583

Don't index full text for work objects

---

common-utils/src/main/java/edu/unc/lib/boxc/common/util/DateTimeUtil.java

https://jira.lib.unc.edu/browse/BXC-3452

Format dates before 1583 correctly

---

indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilterTest.java
indexing-solr/src/test/resources/datastream/inventoryMods.xml

https://jira.lib.unc.edu/browse/BXC-3589

Fix issue with empty publisher values being indexed

---

static/js/vue-cdr-access/src/components/browseSort.vue
static/js/vue-cdr-access/src/translations.js

https://jira.lib.unc.edu/browse/BXC-3529

Add sorting by date added

---

pom.xml
web-sword/pom.xml

https://jira.lib.unc.edu/browse/BXC-3618

BXC-3618 - Replace log4j 1.x from sword2-server with reload4j

---

static/js/vue-cdr-access/src/components/browseSearch.vue
static/js/vue-cdr-access/src/components/browseSort.vue
static/js/vue-cdr-access/src/components/clearFacetsButton.vue
static/js/vue-cdr-access/src/components/facets.vue
static/js/vue-cdr-access/src/components/searchWrapper.vue
static/js/vue-cdr-access/src/components/worksOnly.vue
static/js/vue-cdr-access/src/mixins/routeUtils.js
static/js/vue-cdr-access/tests/unit/routeUtils.spec.js

https://jira.lib.unc.edu/browse/BXC-3592

Reset start row to 0, if search changes

---

static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/tests/unit/displayWrapper.spec.js

https://jira.lib.unc.edu/browse/BXC-3642

Fix variable name

---

indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilterTest.java
indexing-solr/src/test/resources/datastream/inventoryMods.xml

https://jira.lib.unc.edu/browse/BXC-3651

Don't index empty genre elements or those without authorities

---

web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FullRecordController.java
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/fileRecord.jsp

https://jira.lib.unc.edu/browse/BXC-3605

Add link to parent work.

---

static/js/vue-cdr-access/src/components/listDisplay.vue
static/js/vue-cdr-access/tests/unit/listDisplay.spec.js
web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/DatastreamUtil.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/utils/DatastreamUtilTest.java

https://jira.lib.unc.edu/browse/BXC-3456

Update filetype text based on how many and what filetypes are returned

---

etc/solr-config/access/conf/schema.xml
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilterTest.java
indexing-solr/src/test/resources/datastream/inventoryMods.xml
search-api/src/main/java/edu/unc/lib/boxc/search/api/SearchFieldKey.java
search-api/src/main/java/edu/unc/lib/boxc/search/api/models/ContentObjectRecord.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/ContentObjectSolrRecord.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/GroupedContentObjectSolrRecord.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/IndexDocumentBean.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/AbstractQueryService.java
web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FullRecordController.java
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/collectionRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/fileRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/folderRecord.jsp

https://jira.lib.unc.edu/browse/BXC-3378
Depends on: https://gitlab.lib.unc.edu/cdr/boxc-ansible/-/merge_requests/196

Display links to related digital exhibits

---

static/js/vue-cdr-access/src/components/facets.vue
web-access-app/src/main/webapp/WEB-INF/jsp/collectionBrowse.jsp

https://jira.lib.unc.edu/browse/BXC-3667

Update language for admin unit display

---

static/js/vue-cdr-access/src/components/clearFilters.vue
static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/src/components/facets.vue
static/js/vue-cdr-access/src/components/searchWrapper.vue
static/js/vue-cdr-access/tests/unit/facets.spec.js

https://jira.lib.unc.edu/browse/BXC-3668

Add "Start Over" option to main search page

---

web-access-app/src/main/resources/modsExclusionXPaths.json

- hide object type and object id
- hide contentdm number

BXC-3681 add fields

---

indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilterTest.java

https://jira.lib.unc.edu/browse/BXC-3686

Don't use date added for date created value

---

integration/src/test/java/edu/unc/lib/boxc/integration/factories/CollectionFactory.java
integration/src/test/java/edu/unc/lib/boxc/integration/factories/WorkFactory.java
integration/src/test/java/edu/unc/lib/boxc/integration/web/access/CollectionsEndpointIT.java
integration/src/test/resources/spring-test/object-factory-context.xml

This PR adds the CollectionFactory which now allows Works to have Collections as parents. Collections have AdminUnits as parents. With that done, we can test factory creating in the CollectionsEndpointIT file.
https://jira.lib.unc.edu/browse/BXC-3661

Bxc 3661 collection factory

---

static/js/vue-cdr-access/src/mixins/displayUtils.js
web-access-app/src/main/webapp/WEB-INF/jsp/common/thumbnail.jsp

https://jira.lib.unc.edu/browse/BXC-3699

Admin units should always be marked as open

---

static/js/vue-cdr-access/src/components/facetModal.vue
static/js/vue-cdr-access/src/components/filterTags.vue
static/js/vue-cdr-access/tests/unit/facetModal.spec.js

https://jira.lib.unc.edu/browse/BXC-3719

Adjust layout of modal and make sure all filter tags are capitalized

---

integration/src/test/java/edu/unc/lib/boxc/integration/web/access/SearchEndpointIT.java

This adds two tests specifying search results by type.
https://jira.lib.unc.edu/browse/BXC-3736

BXC-3736 add integration tests searching for type

---

integration/src/test/java/edu/unc/lib/boxc/integration/web/access/EndpointIT.java
integration/src/test/java/edu/unc/lib/boxc/integration/web/access/SearchEndpointIT.java

This adds two tests, one that specifies a title search in normal order and another that tries a title search in reversed order.
https://jira.lib.unc.edu/browse/BXC-3734

BXC-3734 adding sort searchJson tests

---

static/js/vue-cdr-access/src/mixins/routeUtils.js
static/js/vue-cdr-access/tests/unit/displayWrapper.spec.js
static/js/vue-cdr-access/tests/unit/facetModal.spec.js
static/js/vue-cdr-access/tests/unit/routeUtils.spec.js
static/js/vue-cdr-access/tests/unit/worksOnly.spec.js

https://jira.lib.unc.edu/browse/BXC-3723
* Include files in record page searches so that full text searches work

BXC-3723 - Include files in record page searches so that full text searches work

---

integration/src/test/java/edu/unc/lib/boxc/integration/factories/ModsFactory.java
integration/src/test/java/edu/unc/lib/boxc/integration/web/access/EndpointIT.java
integration/src/test/java/edu/unc/lib/boxc/integration/web/access/SearchEndpointIT.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/SearchStateFactory.java

This PR tests the dateCreated search, and also fixes a bug found for the unknown search (thanks @bbpennel )
https://jira.lib.unc.edu/browse/BXC-3731

Bxc 3731 date filter search

---

common-utils/src/main/java/edu/unc/lib/boxc/common/xml/SecureXMLFactory.java
deposit-app/src/main/webapp/WEB-INF/deposit-jobs-context.xml
operations/src/test/resources/spring-test/cdr-client-container.xml
services-camel-app/src/main/webapp/WEB-INF/service-context.xml
services-camel-app/src/test/resources/import-xml-it-context.xml
web-services-app/src/main/webapp/WEB-INF/service-context.xml
web-services-app/src/test/resources/spring-test/cdr-client-container.xml

https://jira.lib.unc.edu/browse/BXC-3703
* Move instantiation of schema objects into factory class, as direct calls from spring context triggers a java 9 security warnings

BXC-3703 - Reflective access warning

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJob.java

https://jira.lib.unc.edu/browse/BXC-3773
https://stackoverflow.com/questions/17569608/format-a-message-using-messageformat-format-in-java

BXC-3773 - Escape single quotes in error message

---

integration/src/test/java/edu/unc/lib/boxc/integration/web/access/EndpointIT.java
integration/src/test/java/edu/unc/lib/boxc/integration/web/access/SearchEndpointIT.java

This integration test PR tests the `getFacets` and `facetSelect` parameters on the searchJson endpoint.
https://jira.lib.unc.edu/browse/BXC-3772

Bxc 3772 returning facets tests

---

static/plugins/uv/package-lock.json
static/plugins/uv/package.json

See comments on https://jira.lib.unc.edu/browse/BXC-3728

Update to latest UV 3.x

---

web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FullRecordController.java

https://jira.lib.unc.edu/browse/BXC-3700

Catch Mods parsing error where all fields are hidden

---

integration/src/test/java/edu/unc/lib/boxc/integration/factories/ModsFactory.java
integration/src/test/java/edu/unc/lib/boxc/integration/web/access/CollectionsEndpointIT.java
integration/src/test/java/edu/unc/lib/boxc/integration/web/access/EndpointIT.java
integration/src/test/java/edu/unc/lib/boxc/integration/web/access/SearchEndpointIT.java

[https://jira.lib.unc.edu/browse/BXC-3771](https://jira.lib.unc.edu/browse/BXC-3771)
- add fields to `ModsFactory.java`
- add `AssertStringValuePresent` and `AssertArrayValuePresent`
- create integration tests to verify all record fields returned

Bxc 3771 return fields tests

---

static/css/sass/cdr_ui_styles.scss
static/js/public/fullRecord.js
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp

https://jira.lib.unc.edu/browse/BXC-3694

Don't show user download button if they don't have access

---

.codeclimate.yml

* Use our checkstyle config
* Ignore some external libraries
* Enable some plugins

Initial Code Climate config

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJob.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJobTest.java

https://jira.lib.unc.edu/browse/BXC-3780
* Sanitize filenames submitted to FITS cli by symlinking to the file, using a filename with the reserved and non-ascii characters removed

BXC-3780 - Sanitize filenames for FITS CLI

---

model-api/src/main/java/edu/unc/lib/boxc/model/api/services/MembershipService.java
model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/services/PcdmMembershipService.java
model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/services/RepositoryObjectDriver.java
model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/sparql/SparqlListingHelper.java
model-fcrepo/src/test/java/edu/unc/lib/boxc/model/fcrepo/services/PcdmMembershipServiceTest.java
operations/src/main/java/edu/unc/lib/boxc/operations/api/order/OrderValidator.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/OrderValidator.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/OrderValidatorFactory.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/SetOrderValidator.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/order/OrderValidatorFactoryTest.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/order/SetOrderValidatorTest.java

https://jira.lib.unc.edu/browse/BXC-3784
* Adds a validator and factory for SetOrderRequests
* Adds PcdmMembershipService, to be used for getting lists of member pids

BXC-3784 - Validator for SetOrder requests

---

services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateProcessorIT.java

I reproduced this bug locally by invoking the test method 10 times in a row, and it very consistently failed 30-50% of the time. There were no failures after repeated runs with this change.
https://jira.lib.unc.edu/browse/BXC-3796
* Fix flapping test by invalidating cached objects prior to indexing (this also happens in the regular indexing camel routes)

BXC-3796 - Flapping test: SolrUpdateProcessorIT.testUpdateDescription

---

static/css/sass/cdr_ui_styles.scss
web-access-app/src/main/webapp/WEB-INF/jsp/error/invalidRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/accessInfo.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/adminUnit.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/collectionRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/fileRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/folderRecord.jsp
web-common/src/main/java/edu/unc/lib/boxc/web/common/services/PermissionsHelper.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/services/PermissionsHelperTest.java

https://jira.lib.unc.edu/browse/BXC-3782

Add buttons for restricted content access

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/order/OrderNotificationBuilder.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/order/OrderNotificationService.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/order/OrderNotificationBuilderTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/order/OrderNotificationServiceTest.java

This PR builds out the feature that sends a notification after a bulk ordering update.
https://jira.lib.unc.edu/browse/BXC-3787

Bxc 3787 send email set order update

---

.github/workflows/build.yml

So that coverage gets uploaded for main

Perform build on push to main

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/config/SearchSettings.java

https://jira.lib.unc.edu/browse/BXC-3809

Add member_order_id to default search sorting

---

operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/OrderJobFactory.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/RemoveFromOrderJob.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/order/RemoveFromJobTest.java
operations/src/test/java/edu/unc/lib/boxc/operations/test/OrderJobTestHelper.java

Creates functionality for REMOVE_FROM order type action and adds tests
https://jira.lib.unc.edu/browse/BXC-3791

Bxc 3791 remove child job

---

operations/src/main/java/edu/unc/lib/boxc/operations/impl/destroy/DestroyObjectsJob.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/destroy/DestroyObjectsJobIT.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/destroyDerivatives/DestroyDerivativesRouterIT.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solr/SolrIngestProcessorIT.java

This PR adds a trigger for the remove order job during the delete object job.
https://jira.lib.unc.edu/browse/BXC-3790

Bxc 3790 trigger remove job

---

web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FullRecordController.java
web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/MODSController.java
web-common/src/main/java/edu/unc/lib/boxc/web/common/controllers/AbstractErrorHandlingSearchController.java

https://jira.lib.unc.edu/browse/BXC-3878
* Return 404 for not found on full record page. Adjustments to error handling

BXC-3878 - 404 for not found record page

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/DepositSetMemberOrderValidator.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/ValidateContentModelJob.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/DepositSetMemberOrderValidatorTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/ValidateContentModelJobTest.java

This PR includes code for a validator for Member Order in a deposit job, and relevant tests.
https://jira.lib.unc.edu/browse/BXC-3788
Intellij did have a suggestion about the `iterator.hasNext()` because it may invoke a NullPointerException. not sure how we feel about that, so I left it out

Bxc 3788 deposit order validator

---

static/css/sass/cdr_homepage.scss

https://jira.lib.unc.edu/browse/BXC-3882

Fix issue with color contrast

---

indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/utils/JDOMQueryUtil.java
indexing-solr/src/test/resources/datastream/inventoryMods.xml

https://jira.lib.unc.edu/browse/BXC-3936

Check all date nodes, returning the first valid ISO6392b date

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/MultiSelectFacetListService.java

https://jira.lib.unc.edu/browse/BXC-3919

Turn off cutoffs for date faceting query

---

web-access-app/src/main/webapp/robots.txt

for https://jira.lib.unc.edu/browse/BXC-3937

BXC-3937 adding paths to robots.txt

---

web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FedoraContentController.java
web-access-app/src/test/java/edu/unc/lib/boxc/web/access/controllers/FedoraContentControllerIT.java

for https://jira.lib.unc.edu/browse/BXC-3938
This PR adds a test, and adds the InvalidPidException to the NotFound error handler.

BXC-3938 add test and exception handling code

---

etc/solr-config/access/conf/schema.xml

https://jira.lib.unc.edu/browse/BXC-3953

BXC-3953 add copy fields in schema to update indexing

---

static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/src/components/full_record/adminUnit.vue
static/js/vue-cdr-access/src/components/full_record/collectionFolder.vue

Co-authored-by: Dean Farrell <lfarrell@email.unc.edu>

Fix bug causing modal to display by default.

---

operations/src/main/java/edu/unc/lib/boxc/operations/impl/destroy/DestroyObjectsJob.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/destroy/DestroyObjectsRouterTest.java

https://jira.lib.unc.edu/browse/BXC-4001
* Add transaction refresher to destroy operation, otherwise destroying containers with lots of children will tend to time out. Rethrow error as a ServiceException instead of a tx exception for clarity.
* Some refactoring to shorten the `run` method

BXC-4001 - Avoid failure when destroying lots of stuff

---

web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/aggregateRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/collectionRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/fileRecord.jsp
web-access-app/src/main/webapp/WEB-INF/jsp/fullRecord/folderRecord.jsp

Do not display FA field if blank
https://jira.lib.unc.edu/browse/BXC-4014

BXC-4014 - hide FA field if blank

---

web-access-app/src/main/webapp/WEB-INF/access-fedora-context.xml
web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/AnalyticsTrackerUtil.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/utils/AnalyticsTrackerUtilTest.java
web-services-app/src/main/webapp/WEB-INF/service-context.xml

https://jira.lib.unc.edu/browse/BXC-3981
* Add dh property to supply missing host info.
* Removed unused value property.
*  Pass provided action down to the event being sent.
*  Make some constants static. 
* Add test coverage

BXC-3981 - host in download event, and AnalyticsUtil cleanup

---

static/css/cdrui_styles.css
static/css/sass/cdr_ui_styles.scss
static/js/vue-cdr-access/src/components/browseSort.vue
static/js/vue-cdr-access/src/components/full_record/adminUnit.vue
static/js/vue-cdr-access/src/components/full_record/aggregateRecord.vue
static/js/vue-cdr-access/src/components/full_record/collectionFolder.vue
static/js/vue-cdr-access/src/components/full_record/fileRecord.vue
static/js/vue-cdr-access/src/components/full_record/player.vue
static/js/vue-cdr-access/src/components/full_record/restrictedContent.vue
static/js/vue-cdr-access/src/components/full_record/thumbnail.vue
static/js/vue-cdr-access/src/components/galleryDisplay.vue
static/js/vue-cdr-access/src/components/listDisplay.vue
static/js/vue-cdr-access/src/components/searchWrapper.vue
static/js/vue-cdr-access/src/mixins/fullRecordUtils.js
static/js/vue-cdr-access/src/mixins/permissionUtils.js
static/js/vue-cdr-access/tests/unit/permissionUtils.spec.js
static/js/vue-cdr-access/tests/unit/thumbnail.spec.js

- Update search pages to use thumbnail component 
- Move permissions into their own util file
https://jira.lib.unc.edu/browse/BXC-4090

Update search pages to use thumbnail component 

---

static/css/sass/cdr_ui_styles.scss
static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/src/components/full_record/aggregateRecord.vue
static/js/vue-cdr-access/src/components/full_record/player.vue
static/js/vue-cdr-access/src/store.js
static/js/vue-cdr-access/tests/unit/displayWrapper.spec.js

* Ensure search results retrieved after brief object on page creation/mounting
* Fix issue where facets would be lost and not come back when navigating between admin units, collections and folders.
* Fix spacing around header in work/files page

Vue bug fixes

---

static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json
static/js/vue-cdr-access/src/components/full_record/fileList.vue

This PR adds a button that clears any previous sorts from the file list.
https://jira.lib.unc.edu/browse/BXC-4036

Bxc 4036 neutral sort

---

static/js/vue-cdr-access/src/components/collectionBrowseWrapper.vue
static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/src/components/error_pages/notAvailable.vue
static/js/vue-cdr-access/src/components/error_pages/notFound.vue
static/js/vue-cdr-access/src/components/header/headerHome.vue
static/js/vue-cdr-access/src/components/header/headerSmall.vue
static/js/vue-cdr-access/src/components/searchWrapper.vue
static/js/vue-cdr-access/src/mixins/errorUtils.js
static/js/vue-cdr-access/src/mixins/headerUtils.js
static/js/vue-cdr-access/src/mixins/loginUrlUtils.js
static/js/vue-cdr-access/src/router.js
static/js/vue-cdr-access/tests/unit/collectionBrowseWrapper.spec.js
static/js/vue-cdr-access/tests/unit/displayWrapper.spec.js
static/js/vue-cdr-access/tests/unit/notAvailable.spec.js
static/js/vue-cdr-access/tests/unit/notFound.spec.js
static/js/vue-cdr-access/tests/unit/searchWrapper.spec.js
static/service-unavailable.html

https://jira.lib.unc.edu/browse/BXC-4164
Depends on: https://gitlab.lib.unc.edu/cdr/boxc-ansible/-/merge_requests/226

Add routing and display for not found, restricted content and 503 errors

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/images/ImageEnhancementsRouter.java

[https://jira.lib.unc.edu/browse/BXC-4078](https://jira.lib.unc.edu/browse/BXC-4078)

BXC-4078 use CdrMimeType instead of jp2

---

static/js/vue-cdr-access/src/router.js

https://jira.lib.unc.edu/browse/BXC-4189

BXC-4189 - Add route to redirect list urls to record

---

static/js/vue-cdr-access/src/main.js
static/js/vue-cdr-access/src/mixins/analyticsUtils.js
static/js/vue-cdr-access/src/mixins/matomoUtils.js

https://jira.lib.unc.edu/browse/BXC-4148
* Update matomo url variable names. Record page view as a page view event, and set a event name for record view

BXC-4148 - Matomo client side event fixes

---

static/js/vue-cdr-access/src/mixins/errorUtils.js
static/js/vue-cdr-access/src/mixins/fullRecordUtils.js
static/js/vue-cdr-access/tests/unit/displayWrapper.spec.js
static/js/vue-cdr-access/tests/unit/notFound.spec.js

https://jira.lib.unc.edu/browse/BXC-4234

Check for 4xx status codes

---

static/js/vue-cdr-access/src/components/facetModal.vue
static/js/vue-cdr-access/tests/unit/facetModal.spec.js

https://jira.lib.unc.edu/browse/BXC-4212

Fix issue with facet results not scoping to their container

---

pom.xml
services-camel-app/pom.xml
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/fulltext/FulltextProcessor.java

https://jira.lib.unc.edu/browse/BXC-4208

Update to tika 2.8

---

static/js/vue-cdr-access/src/components/full_record/player.vue
static/js/vue-cdr-access/tests/unit/player.spec.js

https://jira.lib.unc.edu/browse/BXC-4210
* Suppress pdf viewer for files larger than 200mb. 
* Removed unused neighborList data from test to cut down on confusion.

BXC-4210 - Suppress pdf viewer for files larger than 200mb

---

web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/DownloadImageService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/DownloadImageController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/DownloadImageControllerIT.java

https://jira.lib.unc.edu/browse/BXC-4225
This PR makes the downloaded filename clearer, with the original filename and the size included.

Bxc 4225 access copy download filename

---

static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/tests/unit/displayWrapper.spec.js

https://unclibrary.atlassian.net/browse/BXC-4357

Fix issue with navigation getting stuck in a circular loop

---

static/js/vue-cdr-access/src/components/full_record/aggregateRecord.vue
static/js/vue-cdr-access/src/components/full_record/fileRecord.vue
static/js/vue-cdr-access/src/components/full_record/restrictedContent.vue
static/js/vue-cdr-access/tests/unit/aggregateRecord.spec.js
static/js/vue-cdr-access/tests/unit/fileRecord.spec.js
static/js/vue-cdr-access/tests/unit/restrictedContent.spec.js
web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FullRecordController.java

https://unclibrary.atlassian.net/browse/BXC-4089

Fix issue with embargoes not displaying in the public UI

---

static/js/vue-cdr-access/src/components/full_record/singleUseLink.vue
static/js/vue-cdr-access/tests/unit/singleUseLink.spec.js

https://unclibrary.atlassian.net/browse/BXC-4423

Clear single use links if the url path change

---

static/js/vue-cdr-access/src/translations.js

https://unclibrary.atlassian.net/browse/BXC-4455

BXC-4455 - update exhibit field label

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/GroupedContentObjectSolrRecord.java
static/js/vue-cdr-access/src/components/full_record/aggregateRecord.vue
static/js/vue-cdr-access/src/components/full_record/fileRecord.vue
static/js/vue-cdr-access/src/components/listDisplay.vue
static/js/vue-cdr-access/src/translations.js

- https://unclibrary.atlassian.net/browse/BXC-4463

 Remove collection id from full record pages, and update its label for list display

---

static/js/vue-cdr-access/src/components/full_record/fileList.vue
static/js/vue-cdr-access/src/components/full_record/thumbnail.vue
static/js/vue-cdr-access/src/mixins/permissionUtils.js
static/js/vue-cdr-access/tests/unit/analyticsUtils.spec.js
static/js/vue-cdr-access/tests/unit/fileList.spec.js
static/js/vue-cdr-access/tests/unit/folderRecord.spec.js
static/js/vue-cdr-access/tests/unit/thumbnail.spec.js

https://unclibrary.atlassian.net/browse/BXC-4473

Switch to checking for specific permissions instead of "Public Access" status for displaying lock icon

---

web-common/src/main/java/edu/unc/lib/boxc/web/common/services/XmlDocumentFilteringService.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/services/XmlDocumentFilteringServiceTest.java
web-common/src/test/resources/mods/exclusion_record.xml

https://unclibrary.atlassian.net/browse/BXC-3700

Fix issue with MODS exclusions removing the root element if there are no more child elements

---

web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/AnalyticsTrackerUtil.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/utils/AnalyticsTrackerUtilTest.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/DownloadImageController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/DownloadImageControllerIT.java
web-services-app/src/test/resources/download-image-it-servlet.xml

trying to update paged-display-development branch to main

Update to main

---

web-access-app/src/main/webapp/robots.txt

https://unclibrary.atlassian.net/browse/BXC-4479

BXC-4479 add iiif v3 endpoints to robots.txt

---

etc/solr-config/access/conf/schema.xml
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentStatusFilter.java
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetViewBehaviorFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetViewBehaviorFilterTest.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/indexing/IndexingActionType.java
search-api/src/main/java/edu/unc/lib/boxc/search/api/FacetConstants.java
search-api/src/main/java/edu/unc/lib/boxc/search/api/SearchFieldKey.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/IndexDocumentBean.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/util/IndexingActionUtil.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/viewSettings/ViewSettingRequestProcessor.java
services-camel-app/src/main/webapp/WEB-INF/service-context.xml
services-camel-app/src/main/webapp/WEB-INF/solr-indexing-context.xml
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/viewSettings/ViewSettingRequestProcessorTest.java
static/js/admin/src/ResultObject.js
static/templates/admin/viewSettingsForm.html

This PR allows the view behavior to be indexed in solr for a work and adds facet constants accordingly for the content status filter.
https://unclibrary.atlassian.net/browse/BXC-4428

Bxc 4428 solr updates

---

search-api/src/main/java/edu/unc/lib/boxc/search/api/models/ContentObjectRecord.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/GroupedContentObjectSolrRecord.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/ExportCsvService.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/ExportCsvIT.java
web-services-app/src/test/resources/spring-test/solr-indexing-context.xml

This PR adds a new column to the CSV export for view behavior field in the solr record.
https://unclibrary.atlassian.net/browse/BXC-4434

BXC-4434 finish up csv code and add test

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/AbstractQueryService.java
static/templates/admin/viewSettingsForm.html
web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/AbstractSearchController.java
web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/SerializationUtil.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/IiifV3ManifestService.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/IiifV3ManifestServiceTest.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/IiifV3ManifestControllerTest.java

Adding viewing direction and view behavior to multi-file work manifests.
https://unclibrary.atlassian.net/browse/BXC-4431

Bxc 4431 view behavior manifests

---

web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/ResultEntryController.java

https://unclibrary.atlassian.net/browse/BXC-4518

Add viewBehavior to metadata returned after updating an object

---

static/js/admin/vue-permissions-editor/package-lock.json
static/js/vue-cdr-access/package-lock.json
web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/ResultEntryController.java
web-common/src/main/java/edu/unc/lib/boxc/web/common/auth/filters/StoreUserAccessControlFilter.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/auth/filters/StoreUserAccessControlFilterTest.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/ExportCsvService.java
web-services-app/src/main/webapp/WEB-INF/service-context.xml
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/ExportCsvIT.java
web-services-app/src/test/resources/export-csv-it-servlet.xml

This PR updates the duracloud development branch to current state of the main branch

Update duracloud branch

---

static/css/admin/cdradmin.css
static/js/admin/src/ImportMenu.js
static/js/admin/src/ResultView.js
static/js/admin/src/SearchTags.js
web-admin-app/src/main/webapp/WEB-INF/jsp/common/header.jsp

https://unclibrary.atlassian.net/browse/BXC-4515

Admin interface search tags

---

operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/accessSurrogates/AccessSurrogateRequest.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/accessSurrogates/AccessSurrogateRequestSerializationHelper.java
operations-jms/src/test/java/edu/unc/lib/boxc/operations/jms/accessSurrogates/AccessSurrogateRequestSerializationHelperTest.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/accessSurrogates/AccessSurrogateRequestProcessor.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/accessSurrogates/AccessSurrogateRouter.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/accessSurrogates/AccessSurrogateRequestProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/accessSurrogates/AccessSurrogateRouterTest.java
services-camel-app/src/test/resources/access-surrogates-context.xml
services-camel-app/src/test/resources/config.properties

This PR adds the processor, request, serialization helper, and router (and associated tests) for updating access surrogates.
https://unclibrary.atlassian.net/browse/BXC-4543

Bxc 4543 access surrogate service

---

operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/accessSurrogates/AccessSurrogateRequestSender.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/AccessSurrogateController.java
web-services-app/src/main/webapp/WEB-INF/service-context.xml
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/AccessSurrogateIT.java

This PR adds controller, sender, and test files for the Access Surrogate feature to set or delete access surrogates.
https://unclibrary.atlassian.net/browse/BXC-4544

Bxc 4544 access surrogate api

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestContentObjectsJob.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/ValidateContentModelJob.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestContentObjectsJobIT.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestContentObjectsJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/ValidateContentModelJobTest.java
model-api/src/main/java/edu/unc/lib/boxc/model/api/rdf/Cdr.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequest.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequestSender.java
operations-jms/src/test/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequestSenderTest.java
operations-jms/src/test/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequestSerializationHelperTest.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRequestProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRouterTest.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/StreamingPropertiesController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/StreamingPropertiesIT.java

This PR removes properties in favor of just one that will just point to the StreamReaper Url.
https://unclibrary.atlassian.net/browse/BXC-4566

BXC-4566 removing unneeded properties

---

static/js/vue-cdr-access/src/router.js

https://unclibrary.atlassian.net/browse/BXC-4577

Don't add trailing slash to searches

---

static/css/cdrui_styles.css
static/js/admin/vue-permissions-editor/src/components/patronRoles.vue
static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/src/components/full_record/player.vue
static/js/vue-cdr-access/src/components/full_record/streamingPlayer.vue
static/js/vue-cdr-access/tests/unit/player.spec.js
static/js/vue-cdr-access/tests/unit/streamingPlayer.spec.js

https://unclibrary.atlassian.net/browse/BXC-4440

Duracloud Streaming UI

---

static/js/vue-cdr-access/src/components/aboutRepository.vue
static/js/vue-cdr-access/src/components/dcrFooter.vue
static/js/vue-cdr-access/src/components/error_pages/notFound.vue
static/js/vue-cdr-access/src/components/frontPage.vue
static/js/vue-cdr-access/src/components/full_record/restrictedContent.vue
static/js/vue-cdr-access/src/components/header/headerHome.vue
static/js/vue-cdr-access/src/components/header/headerSmall.vue
static/maintenance.html
static/service-unavailable.html

https://unclibrary.atlassian.net/browse/BXC-4585

Update links to match new library site

---

web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FedoraContentController.java
web-access-app/src/test/java/edu/unc/lib/boxc/web/access/controllers/FedoraContentControllerTest.java

https://unclibrary.atlassian.net/browse/BXC-4592
Specifically check the top level error to see if it is a EofException during download of files. Add a unit test to verify the various exception paths

BXC-4592 - More handling of EofException during download

---

web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/ExportCsvService.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/ExportCsvIT.java

https://unclibrary.atlassian.net/browse/BXC-4564

BXC-4564 - Add access surrogate status to CSV exports

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJob.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJobTest.java
deposit-app/src/test/resources/fitsReports/conflictRankingReport.xml
deposit-app/src/test/resources/fitsReports/conflictTypeReport.xml

https://unclibrary.atlassian.net/browse/BXC-4604
* Adjust FITS mimetype conflict resolution to rank returned options, filter out invalid results.
* Use a temp dir for storing symlinks, since nano time can very occasionally produce the same name

BXC-4604 - Handle symlink mimetypes and rank

---

web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/ExportCsvService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/ExportCsvController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/ExportCsvIT.java

https://unclibrary.atlassian.net/browse/BXC-4600
https://unclibrary.atlassian.net/browse/BXC-4601

Bxc 4600 bxc 4601 update export csv

---

static/js/admin/src/ExportMenu.js
static/js/admin/src/ResultObjectActionMenu.js
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/ExportCsvController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/ExportCsvIT.java

- Admin UI for bulk csv export
- Switch request from post to get to work around some issues with ajax not working well with file downloads
https://unclibrary.atlassian.net/browse/BXC-4602

Admin UI for bulk CSV dowload

---

etc/solr-config/access/conf/schema.xml
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentStatusFilter.java
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetStreamingUrlFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetStreamingUrlFilterTest.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetViewBehaviorFilterTest.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/test/MockRepositoryObjectHelpers.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/indexing/IndexingActionType.java
search-api/src/main/java/edu/unc/lib/boxc/search/api/FacetConstants.java
search-api/src/main/java/edu/unc/lib/boxc/search/api/SearchFieldKey.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/IndexDocumentBean.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRequestProcessor.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/util/IndexingActionUtil.java
services-camel-app/src/main/webapp/WEB-INF/service-context.xml
services-camel-app/src/main/webapp/WEB-INF/solr-indexing-context.xml
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesProcessorTest.java
static/js/admin/src/EditStreamingPropertiesForm.js
static/js/admin/src/ResultObject.js
static/js/admin/src/ResultObjectActionMenu.js
static/templates/admin/editStreamingPropertiesForm.html

This PR indexes the streaming URL property into solr.
https://unclibrary.atlassian.net/browse/BXC-4446

Bxc 4446 index streaming properties

---

operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/streaming/StreamingPropertiesRequest.java
static/css/admin/cdradmin.css
static/js/admin/src/EditStreamingPropertiesForm.js
static/js/admin/src/ResultObjectActionMenu.js
static/js/admin/src/action/DeleteStreamingPropertiesResultAction.js
static/js/vue-cdr-access/src/components/full_record/streamingPlayer.vue
static/templates/admin/editStreamingPropertiesForm.html

- https://unclibrary.atlassian.net/browse/BXC-4615
- https://unclibrary.atlassian.net/browse/BXC-4616

Streaming Admin UI

---

web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/ImageServerV2Service.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/ImageServerV2Controller.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/ImageServerV2ControllerTest.java

https://unclibrary.atlassian.net/browse/BXC-4609

Bxc 4609 iiif endpoint fix

---

deposit-app/src/main/java/edu/unc/lib/boxc/deposit/transfer/TransferBinariesToStorageJob.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/transfer/TransferBinariesToStorageJobTest.java

Relates to https://unclibrary.atlassian.net/browse/BXC-4612

BXC-4612 - Don't try to transfer FITS for streaming only resource

---

static/js/admin/src/ExportMenu.js
static/js/admin/src/ResultObjectActionMenu.js
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/ExportCsvService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/ExportCsvController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/ExportCsvIT.java

Export CSV work excluding parent information for FileObjects

Export csv development

---

web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/ExportCsvService.java
web-services-app/src/main/webapp/WEB-INF/service-context.xml
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/ExportCsvIT.java
web-services-app/src/test/resources/export-csv-it-servlet.xml

https://unclibrary.atlassian.net/browse/BXC-4605

Bxc 4605 csv export parent info

---

indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetDatastreamFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetDatastreamFilterTest.java
indexing-solr/src/test/resources/datastream/techmd_colon_separated_milliseconds.xml
indexing-solr/src/test/resources/datastream/techmd_dot_separated_milliseconds.xml

https://unclibrary.atlassian.net/browse/BXC-4650

Allow milliseconds from seconds parsing to use "." or ":"

---

search-solr/src/main/java/edu/unc/lib/boxc/search/solr/filters/HasPopulatedFieldFilter.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/filters/QueryFilterFactory.java
search-solr/src/test/java/edu/unc/lib/boxc/search/solr/filters/QueryFilterFactoryTest.java
static/js/vue-cdr-access/src/components/full_record/player.vue
static/js/vue-cdr-access/src/components/full_record/streamingPlayer.vue
static/js/vue-cdr-access/tests/unit/streamingPlayer.spec.js
web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FullRecordController.java
web-common/src/main/java/edu/unc/lib/boxc/web/common/services/AccessCopiesService.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/services/AccessCopiesServiceTest.java

https://unclibrary.atlassian.net/browse/BXC-4639

Show streaming player for works with streaming children

---

web-common/src/main/java/edu/unc/lib/boxc/web/common/services/FedoraContentService.java

https://unclibrary.atlassian.net/browse/BXC-4661

Fix issue with moving around in audio/video files

---

static/js/vue-cdr-access/src/components/full_record/restrictedContent.vue
static/js/vue-cdr-access/src/mixins/fullRecordUtils.js
static/js/vue-cdr-access/src/translations.js
static/js/vue-cdr-access/tests/unit/restrictedContent.spec.js

https://unclibrary.atlassian.net/browse/BXC-4684

BXC-4684 add download zip button

---

Makefile
static/js/admin/vue-cdr-admin/src/components/chompb/preIngest.vue
static/js/admin/vue-cdr-admin/tests/unit/chompb/preIngest.spec.js
web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/ChompbController.java
web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/processing/ChompbPreIngestService.java
web-admin-app/src/main/webapp/WEB-INF/service-context.xml
web-admin-app/src/test/resources/server.properties

https://unclibrary.atlassian.net/browse/BXC-4683
* Get results for preingest project list from chompb
* Updates expected data structure to match what chompb returns
* Adds service for listing chompb projects

BXC-4683 - List chompb projects

---

.github/workflows/build.yml
docker-compose.yml

https://unclibrary.atlassian.net/browse/BXC-4743
Hopefully this should help with fedora docker running on apple silicon.

BXC-4743 - Use fcrepo:5.1.1-multiplatform

---

static/js/vue-cdr-access/src/components/full_record/aggregateRecord.vue
static/js/vue-cdr-access/src/components/full_record/fileRecord.vue

https://unclibrary.atlassian.net/browse/BXC-4752

Remove file size and file type from metadata display

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/thumbnails/ImportThumbnailRequestProcessor.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/thumbnails/ThumbnailRouter.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/thumbnails/ImportThumbnailProcessorTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/thumbnails/ThumbnailRouterTest.java

https://unclibrary.atlassian.net/browse/BXC-4737

BXC-4737 cleanup temp imported thumbnail

---

operations/src/main/java/edu/unc/lib/boxc/operations/impl/download/DownloadBulkService.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/download/DownloadBulkServiceTest.java

https://unclibrary.atlassian.net/browse/BXC-4736

Bxc 4736 handle uncaught error

---

static/css/sass/cdr_ui_styles.scss
static/js/vue-cdr-access/index.html
static/js/vue-cdr-access/src/components/full_record/aggregateRecord.vue
static/js/vue-cdr-access/src/components/full_record/fileList.vue
static/js/vue-cdr-access/src/components/full_record/restrictedContent.vue
static/js/vue-cdr-access/src/translations.js
static/js/vue-cdr-access/tests/unit/fileList.spec.js
static/js/vue-cdr-access/tests/unit/restrictedContent.spec.js
static/service-unavailable.html
web-access-app/src/main/webapp/WEB-INF/html/headElements.html

https://unclibrary.atlassian.net/browse/BXC-4754

Move zip download button

---

static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json
static/js/vue-cdr-access/src/components/full_record/aggregateRecord.vue
static/js/vue-cdr-access/src/components/full_record/bulkDownload.vue
static/js/vue-cdr-access/src/components/full_record/fileList.vue
static/js/vue-cdr-access/src/components/full_record/restrictedContent.vue
static/js/vue-cdr-access/tests/unit/bulkDownload.spec.js
static/js/vue-cdr-access/tests/unit/fileList.spec.js
web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FullRecordController.java
web-access-app/src/main/webapp/WEB-INF/solr-search-context.xml
web-common/src/main/java/edu/unc/lib/boxc/web/common/services/WorkFilesizeService.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/services/WorkFilesizeServiceTest.java

https://unclibrary.atlassian.net/browse/BXC-4755

Add a total file size warning to work level zip download

---

static/js/admin/vue-cdr-admin/tests/unit/permissions-editor/patronRoles.spec.js
static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json
static/js/vue-cdr-access/tests/unit/singleUseLink.spec.js

https://unclibrary.atlassian.net/browse/BXC-4766

Fix test that breaks with latest axios version

---

static/js/vue-cdr-access/src/components/full_record/thumbnail.vue

https://unclibrary.atlassian.net/browse/BXC-4760

Bxc 4760 admin unit thumb

---

static/js/vue-cdr-access/src/components/full_record/fileRecord.vue

https://unclibrary.atlassian.net/browse/BXC-4782

Display filesize on file objects

---

operations/src/main/java/edu/unc/lib/boxc/operations/impl/download/DownloadBulkService.java

Forgot to add this to the ticket branch, adding it now

BXC-4771 simplify loop

---

search-solr/src/test/java/edu/unc/lib/boxc/search/solr/filters/QueryFilterFactoryTest.java

https://unclibrary.atlassian.net/browse/BXC-4793
* Make test order independent

BXC-4793 - Fix flapping QueryFilterFactoryTest 

---

.github/workflows/build.yml
.gitmodules
pom.xml
services-camel-app/pom.xml
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/images/ImageDerivativeProcessor.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/images/ImageEnhancementsRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/images/Jp2Processor.java
services-camel-app/src/main/resources/logback.xml
services-camel-app/src/main/webapp/WEB-INF/service-context.xml
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/images/ImageEnhancementsRouterTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/images/Jp2ProcessorTest.java
services-camel-app/src/test/resources/enhancement-router-it-context.xml
services-camel-app/src/test/resources/images-context.xml

[https://unclibrary.atlassian.net/browse/BXC-4762](https://unclibrary.atlassian.net/browse/BXC-4762)
- add jp24u as submodule to box-c
- add jp24u to the build process
- add jp24u dependency to `pom.xml`
- add `runJp24u` method to `ImageDerivativeProcessor` and use `runJp24u` instead of `convertJp2.sh`

BXC-4762 integrate jp24u jar into box-c

---

web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/ChompbController.java
web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/processing/ChompbPreIngestService.java
web-admin-app/src/main/webapp/WEB-INF/service-context.xml
web-admin-app/src/test/java/edu/unc/lib/boxc/web/admin/controllers/ChompbControllerIT.java
web-admin-app/src/test/java/edu/unc/lib/boxc/web/admin/controllers/processing/ChompbPreIngestServiceTest.java

https://unclibrary.atlassian.net/browse/BXC-4804
* Run chompb crop command as a background process rather than making the users request wait for it to complete

BXC-4804 - Velocicroptor in the background

---

static/js/admin/vue-cdr-admin/package-lock.json
static/js/admin/vue-cdr-admin/package.json
static/js/admin/vue-cdr-admin/src/components/chompb/preIngest.vue
static/js/admin/vue-cdr-admin/tests/unit/chompb/preIngest.spec.js
static/js/admin/vue-cdr-admin/tests/unit/chompb/velocicroptorReport.spec.js
web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/processing/ChompbPreIngestService.java
web-admin-app/src/main/webapp/WEB-INF/service-context.xml
web-admin-app/src/test/resources/server.properties

https://unclibrary.atlassian.net/browse/BXC-4690

BXC-4690 - Admin ui buttons for cropping

---

integration/src/test/java/edu/unc/lib/boxc/integration/web/access/EndpointIT.java
static/js/vue-cdr-access/src/components/advancedSearch.vue
static/js/vue-cdr-access/src/components/collectionBrowseWrapper.vue
static/js/vue-cdr-access/src/components/displayWrapper.vue
static/js/vue-cdr-access/src/components/frontPage.vue
static/js/vue-cdr-access/src/components/full_record/fileList.vue
static/js/vue-cdr-access/src/components/full_record/metadataDisplay.vue
static/js/vue-cdr-access/src/components/full_record/player.vue
static/js/vue-cdr-access/src/components/header/headerHome.vue
static/js/vue-cdr-access/src/components/header/headerSmall.vue
static/js/vue-cdr-access/src/components/modalMetadata.vue
static/js/vue-cdr-access/src/components/searchWrapper.vue
static/js/vue-cdr-access/src/router.js
static/js/vue-cdr-access/tests/unit/advancedSearch.spec.js
static/js/vue-cdr-access/tests/unit/collectionBrowseWrapper.spec.js
static/js/vue-cdr-access/tests/unit/displayWrapper.spec.js
static/js/vue-cdr-access/tests/unit/frontPage.spec.js
static/js/vue-cdr-access/tests/unit/metadataDisplay.spec.js
static/js/vue-cdr-access/tests/unit/modalMetadata.spec.js
static/js/vue-cdr-access/tests/unit/searchWrapper.spec.js
web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/AdvancedSearchFormController.java
web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/BasicSearchFormController.java
web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FrontPageController.java
web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FullRecordController.java
web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/SearchActionController.java
web-access-app/src/test/java/edu/unc/lib/boxc/web/access/controllers/FrontPageControllerIT.java
web-common/src/main/java/edu/unc/lib/boxc/web/common/controllers/UserInformationController.java

https://unclibrary.atlassian.net/browse/BXC-4182
Move all controllers in access app under /api/ path, except the content endpoints

BXC-4182- Move all controllers in access app under /api/ path

---

indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/action/DeleteSolrTreeTest.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/test/TestCorpus.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/DownloadImageService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/IiifV3ManifestService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/DownloadImageController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/IiifV3ManifestServiceTest.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/DatastreamRestControllerIT.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/DownloadImageControllerIT.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/IiifV3ManifestControllerTest.java

https://unclibrary.atlassian.net/browse/BXC-4802
Since I updated the Test Corpus and added two new objects, I had to also update the Delete Solr Tree test accordingly.

BXC-4802 updating tests and code for zero byte JP2s

---

static/templates/admin/editThumbnailForm.html

https://unclibrary.atlassian.net/browse/BXC-4759

Remove note about resizing image

---

Makefile
static/js/vue-cdr-access/index.html
static/js/vue-cdr-access/vite.config.js

Related to https://github.com/UNC-Libraries/box-c/pull/1867

BXC-4795 - Fix vuejs references to files

---

web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/processing/ChompbPreIngestService.java
web-admin-app/src/test/java/edu/unc/lib/boxc/web/admin/controllers/processing/ChompbPreIngestServiceTest.java

Handle IO in other threads, and handle errors during job submit

Boxctron background jobs fixes

---

static/js/vue-cdr-access/src/components/full_record/fileRecord.vue
static/js/vue-cdr-access/tests/unit/analyticsUtils.spec.js
static/js/vue-cdr-access/tests/unit/downloadOptions.spec.js
static/js/vue-cdr-access/tests/unit/fileList.spec.js
static/js/vue-cdr-access/tests/unit/fileRecord.spec.js
static/js/vue-cdr-access/tests/unit/objectActions.spec.js
static/js/vue-cdr-access/tests/unit/player.spec.js
web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/SerializationUtil.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/utils/SerializationUtilTest.java

https://unclibrary.atlassian.net/browse/BXC-4800

BXC-4800 - Change param name from filesizeTotal to filesize

---

model-fcrepo/src/test/java/edu/unc/lib/boxc/model/fcrepo/objects/DepositRecordTest.java

https://unclibrary.atlassian.net/browse/BXC-4858

Bxc 4858 deposit record test

---

model-fcrepo/src/test/java/edu/unc/lib/boxc/model/fcrepo/objects/ContentRootObjectTest.java

https://unclibrary.atlassian.net/browse/BXC-4857

BXC-4857 content root object tests

---

model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/services/RepositoryObjectDriver.java
model-fcrepo/src/test/java/edu/unc/lib/boxc/model/fcrepo/services/RepositoryObjectDriverTest.java

https://unclibrary.atlassian.net/browse/BXC-4878

Bxc 4878 repo object driver tests

---

auth-api/src/test/java/edu/unc/lib/boxc/auth/api/services/EmbargoUtilTest.java

https://unclibrary.atlassian.net/browse/BXC-4856

Bxc 4856 embargo util test

---

web-common/src/test/java/edu/unc/lib/boxc/web/common/controllers/ErrorControllerIT.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/controllers/ErrorControllerTest.java

https://unclibrary.atlassian.net/browse/BXC-4853

Bxc 4853 error controller

---

indexing-solr/src/test/resources/datastream/inventoryMods.xml
integration/src/test/resources/access-app.properties
web-common/src/main/java/edu/unc/lib/boxc/web/common/services/FindingAidUrlService.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/services/FindingAidUrlServiceTest.java

[https://unclibrary.atlassian.net/browse/BXC-4893](https://unclibrary.atlassian.net/browse/BXC-4893)
- update finding aid links from `https://finding-aids.lib.unc.edu/40080/` to `https://finding-aids.lib.unc.edu/catalog/40080`
- update finding aid url in test resource

BXC-4893 update finding aid links format

---

web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/ExportCsvServiceTest.java

https://unclibrary.atlassian.net/browse/BXC-4846

Bxc 4846 export csv service test

---

indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/test/TestCorpus.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/DownloadImageService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/DatastreamController.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/DownloadImageController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/DownloadImageControllerIT.java

https://unclibrary.atlassian.net/browse/BXC-4862

Bxc 4862 placeholder bug

---

web-common/src/main/java/edu/unc/lib/boxc/web/common/services/DerivativeContentService.java
web-common/src/test/java/edu/unc/lib/boxc/web/common/services/DerivativeContentServiceTest.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/DatastreamController.java

https://unclibrary.atlassian.net/browse/BXC-4913
* Add range header support for streaming of derivative files.
* Add test coverage for DerivativeContentService

BXC-4913 - Add range header support for streaming of derivative files

---

common-utils/src/main/java/edu/unc/lib/boxc/common/errors/CommandException.java
common-utils/src/main/java/edu/unc/lib/boxc/common/util/CLIUtil.java
common-utils/src/test/java/edu/unc/lib/boxc/common/util/CLIUtilTest.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/validate/ExtractTechnicalMetadataJob.java
pom.xml
services-camel-app/pom.xml

https://unclibrary.atlassian.net/browse/BXC-4934
* Add a timeout for CLI FITS runs, read output in parallel to prevent deadlock, update camel to most recent version

BXC-4934 - Prevent hanging on FITS runs

---

etc/solr-config/access/conf/schema.xml
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetAspaceRefIdFilter.java
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentStatusFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetAspaceRefIdFilterTest.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetContentStatusFilterTest.java
model-api/src/main/java/edu/unc/lib/boxc/model/api/rdf/CdrAspace.java
model-api/src/main/java/edu/unc/lib/boxc/model/api/rdf/CdrView.java
operations-jms/src/main/java/edu/unc/lib/boxc/operations/jms/indexing/IndexingActionType.java
search-api/src/main/java/edu/unc/lib/boxc/search/api/FacetConstants.java
search-api/src/main/java/edu/unc/lib/boxc/search/api/SearchFieldKey.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/IndexDocumentBean.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/util/IndexingActionUtil.java
services-camel-app/src/main/webapp/WEB-INF/solr-indexing-context.xml

https://unclibrary.atlassian.net/browse/BXC-4927

Bxc 4927 aspace ref id solr

---

etc/solr-config/access/conf/schema.xml
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilter.java
indexing-solr/src/test/java/edu/unc/lib/boxc/indexing/solr/filter/SetDescriptiveMetadataFilterTest.java
indexing-solr/src/test/resources/datastream/inventoryMods.xml
search-api/src/main/java/edu/unc/lib/boxc/search/api/SearchFieldKey.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/IndexDocumentBean.java

https://unclibrary.atlassian.net/browse/BXC-4928

BXC-4928 add hook id to filter for solr indexing

---

search-api/src/main/java/edu/unc/lib/boxc/search/api/models/ContentObjectRecord.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/models/GroupedContentObjectSolrRecord.java
search-solr/src/main/java/edu/unc/lib/boxc/search/solr/services/AbstractQueryService.java
static/js/admin/src/EditAspaceRefIdForm.js
static/js/admin/src/ResultObjectActionMenu.js
static/templates/admin/editAspaceRefIdForm.html
web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/AbstractSearchController.java
web-admin-app/src/main/java/edu/unc/lib/boxc/web/admin/controllers/ResultEntryController.java
web-common/src/main/java/edu/unc/lib/boxc/web/common/utils/SerializationUtil.java

https://unclibrary.atlassian.net/browse/BXC-4931

Add admin UI form for updating aspace ref id

---

web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/IngestController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/IngestControllerIT.java

https://unclibrary.atlassian.net/servicedesk/customer/portal/1/LIB-21378
* Resolves issue with non-global admins not being able to stage.

LIB-21378 - Permit staging routes to anyone with staff roles/admin ui access

---

web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/FullRecordController.java

https://unclibrary.atlassian.net/browse/BXC-4960

Add null check for file format

---

operations/src/main/java/edu/unc/lib/boxc/operations/impl/metadata/PushDominoMetadataService.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/metadata/PushDominoMetadataServiceTest.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/DownloadImageService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/ImageServerProxyService.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/ImageServerV2Service.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/DatastreamController.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/DownloadImageController.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/ImageServerProxyController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/ImageServerV2ServiceTest.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/ImageServerProxyControllerTest.java

We were running into some issues getting connections for the image viewer, specifically manifests, so trying to improve resource releasing a little bit in the new domino code and the IIIF services since they are sharing a connection pool.

Try to improve closing of connections, streams, and clients

---

static/js/admin/src/BulkImportRefIdsForm.js
static/js/admin/src/ExportMenu.js
static/js/admin/src/ImportMenu.js
static/js/admin/src/ResultObjectActionMenu.js
static/templates/admin/bulkImportRefIdsForm.html

https://unclibrary.atlassian.net/browse/BXC-4944

UI for bulk importing aspace ref ids

---

static/js/admin/src/ExportMenu.js
static/js/admin/src/ResultObjectActionMenu.js
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/BulkRefIdCsvExporter.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/AspaceRefIdController.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/MemberOrderController.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/utils/CsvUtil.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/BulkRefIdCsvExporterTest.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/AspaceRefIdControllerTest.java

https://unclibrary.atlassian.net/browse/BXC-5003

Bxc 5003 multiple export ids

---

web-services-app/src/main/java/edu/unc/lib/boxc/web/services/rest/modify/EditTitleController.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/rest/modify/EditTitleIT.java

https://unclibrary.atlassian.net/browse/BXC-4961

Bxc 4961 state unmodified bug

---

operations/src/main/java/edu/unc/lib/boxc/operations/api/order/MemberOrderHelper.java
operations/src/main/java/edu/unc/lib/boxc/operations/impl/order/SetOrderValidator.java
operations/src/test/java/edu/unc/lib/boxc/operations/impl/order/SetOrderValidatorTest.java

https://unclibrary.atlassian.net/browse/BXC-4914

BXC-4914 handle NotFound exception when setting member order

---

deposit-app/src/main/webapp/WEB-INF/web.xml
pom.xml
services-camel-app/src/main/webapp/WEB-INF/web.xml
spoof/src/main/webapp/WEB-INF/web.xml
web-access-app/src/main/webapp/WEB-INF/web.xml
web-admin-app/pom.xml
web-admin-app/src/main/webapp/WEB-INF/cdrUI.tld
web-admin-app/src/main/webapp/WEB-INF/jsp/common/header.jsp
web-admin-app/src/main/webapp/WEB-INF/jsp/edit/createContainer.jsp
web-admin-app/src/main/webapp/WEB-INF/jsp/edit/description.jsp
web-admin-app/src/main/webapp/WEB-INF/jsp/error/login.jsp
web-admin-app/src/main/webapp/WEB-INF/jsp/error/nonAdmin.jsp
web-admin-app/src/main/webapp/WEB-INF/jsp/index.jsp
web-admin-app/src/main/webapp/WEB-INF/jsp/search/collectionList.jsp
web-admin-app/src/main/webapp/WEB-INF/jsp/search/navigationBar.jsp
web-admin-app/src/main/webapp/WEB-INF/jsp/search/resultList.jsp
web-admin-app/src/main/webapp/WEB-INF/jsp/search/searchMenu.jsp
web-admin-app/src/main/webapp/WEB-INF/jsp/template/ajaxTemplate.jsp
web-admin-app/src/main/webapp/WEB-INF/jsp/template/default.jsp
web-admin-app/src/main/webapp/WEB-INF/jsp/template/jsonTemplate.jsp
web-admin-app/src/main/webapp/WEB-INF/jsp/util/facetList.jsp
web-admin-app/src/main/webapp/WEB-INF/service-context.xml
web-admin-app/src/main/webapp/WEB-INF/web.xml
web-services-app/src/main/webapp/WEB-INF/service-context.xml
web-services-app/src/main/webapp/WEB-INF/web.xml
web-services-app/src/test/resources/spring-test/cdr-client-container.xml

https://unclibrary.atlassian.net/browse/BXC-4374
* Update jsp dependencies for ee10, schema locations and taglib names
* Remove upload config properties from spring context since they are handled via properties files now. Update name of CommonsMultipartResolver

BXC-4374 - Fix startup errors in jetty 12

---

auth-fcrepo/src/test/java/edu/unc/lib/boxc/auth/fcrepo/services/ContentObjectAccessRestrictionValidatorTest.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/fcrepo4/IngestDepositRecordJob.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/normalize/AbstractMETS2N3BagJob.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/normalize/CDRMETSGraphExtractor.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/normalize/NormalizeFileObjectsJob.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/normalize/Simple2N3BagJob.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/work/DepositEmailHandler.java
deposit-app/src/main/java/edu/unc/lib/boxc/deposit/work/DepositGraphUtils.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/normalize/CDRMETS2N3BagJobTest.java
deposit-app/src/test/java/edu/unc/lib/boxc/deposit/normalize/Simple2N3BagJobTest.java
deposit-utils/src/main/java/edu/unc/lib/boxc/deposit/impl/model/DepositModelManager.java
indexing-solr/src/main/java/edu/unc/lib/boxc/indexing/solr/action/RecursiveTreeIndexer.java
model-api/src/main/java/edu/unc/lib/boxc/model/api/ids/PID.java
model-fcrepo/src/main/java/edu/unc/lib/boxc/model/fcrepo/ids/FedoraPID.java
model-fcrepo/src/test/java/edu/unc/lib/boxc/model/fcrepo/objects/WorkObjectTest.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/BinaryEnhancementProcessor.java

https://unclibrary.atlassian.net/browse/BXC-5004

BXC-5004 update getURI to getRepositoryPath

---

.qlty/qlty.toml

disabling checkstyle and setting pmd to comment mode

adjust qlty plugin modes

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/accessSurrogates/AccessSurrogateRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/aspace/BulkRefIdRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/audio/AudioEnhancementsRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/cdrEvents/CdrEventRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/destroy/DestroyObjectsRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/destroyDerivatives/DestroyDerivativesRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/enhancements/EnhancementRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/exportxml/ExportXMLRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/fulltext/FulltextRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/images/ImageEnhancementsRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/importxml/ImportXMLRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/longleaf/LongleafRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/order/OrderMembersRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/patronAccess/PatronAccessAssignmentRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/routing/MetaServicesRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/solr/SolrRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/solrUpdate/SolrUpdateRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/thumbnails/ThumbnailRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/triplesReindexing/TriplesReindexingRouter.java
services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/viewSettings/ViewSettingRouter.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/aspace/BulkRefIdRouterTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/audio/AudioEnhancementsRouterTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/images/ImageEnhancementsRouterTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/patronAccess/PatronAccessAssignmentRouterTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/solr/SolrRouterTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/streaming/StreamingPropertiesRouterTest.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/thumbnails/ThumbnailRouterTest.java

https://unclibrary.atlassian.net/browse/BXC-5153

BXC-5153 remove 'value =' when there is only one parameter

---

web-access-app/src/main/java/edu/unc/lib/boxc/web/access/controllers/AdvancedSearchFormController.java

https://unclibrary.atlassian.net/browse/BXC-5163

Fix for advanced search not retaining search variables

---

static/js/vue-cdr-access/package-lock.json
static/js/vue-cdr-access/package.json

https://unclibrary.atlassian.net/browse/BXC-5189

Update clover, veaury and pin react to version 18

---

services-camel-app/src/main/java/edu/unc/lib/boxc/services/camel/order/OrderRequestProcessor.java
services-camel-app/src/test/java/edu/unc/lib/boxc/services/camel/order/OrderRequestProcessorTest.java
web-services-app/src/main/java/edu/unc/lib/boxc/web/services/processing/MemberOrderCsvTransformer.java
web-services-app/src/test/java/edu/unc/lib/boxc/web/services/processing/MemberOrderCsvTransformerTest.java

https://unclibrary.atlassian.net/browse/BXC-5191

Bxc 5191 member order nulls

---

web-access-app/src/main/resources/modsExclusionXPaths.json

https://unclibrary.atlassian.net/browse/BXC-5202

Add chompb number to hidden fields
